# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

env:
  SHARED_SECRET: "demo-secret-key-for-examples012345"

tasks:
  default:
    cmds:
      - task -l

  server:
    desc: Run the SLIM server example
    cmds:
      - echo "🚀 Starting SLIM server..."
      - echo "📦 Building project first..."
      - cd ../.. && task build
      - cd ../.. && ./gradlew :runServer {{.CLI_ARGS}}
    vars:
      CLI_ARGS: '{{.CLI_ARGS | default ""}}'

  p2p:alice:
    desc: "Point to Point example - Alice will listen for messages and echo them"
    cmds:
      - cd ../.. && task build
      - |
        cd ../.. && ./gradlew :runPointToPoint --args="--local agntcy/ns/alice --shared-secret $SHARED_SECRET {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  p2p:bob:
    desc: "Point to Point example - Bob will send unencrypted messages to Alice"
    env:
      SLIM_INSTANCE_ID: bob
    cmds:
      - cd ../.. && task build
      - |
        cd ../.. && ./gradlew :runPointToPoint --args="--local agntcy/ns/bob --shared-secret $SHARED_SECRET --remote agntcy/ns/alice --message 'hey there' {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  p2p:mls:bob:
    desc: "Point to Point example - Bob will send encrypted messages to Alice"
    env:
      SLIM_INSTANCE_ID: bob
    cmds:
      - cd ../.. && task build
      - |
        cd ../.. && ./gradlew :runPointToPoint --args="--local agntcy/ns/bob --shared-secret $SHARED_SECRET --remote agntcy/ns/alice --message 'hey there' --enable-mls {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  group:moderator:
    desc: "Group moderator example - Creates a channel, invites participants, and sends encrypted messages"
    cmds:
      - cd ../.. && task build
      - |
        cd ../.. && ./gradlew :runGroup --args="--local agntcy/ns/moderator --shared-secret $SHARED_SECRET --remote agntcy/ns/chat --invites agntcy/ns/client-1 --invites agntcy/ns/client-2 --enable-mls {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  group:client-1:
    desc: "Group client example - Waits to be invited to a channel and receives encrypted messages"
    cmds:
      - cd ../.. && task build
      - |
        cd ../.. && ./gradlew :runGroup --args="--local agntcy/ns/client-1 --shared-secret $SHARED_SECRET {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  group:client-2:
    desc: "Group client example - Waits to be invited to a channel and receives encrypted messages"
    cmds:
      - cd ../.. && task build
      - |
        cd ../.. && ./gradlew :runGroup --args="--local agntcy/ns/client-2 --shared-secret $SHARED_SECRET {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'
