# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

tracing:
  log_level: debug
  display_thread_names: true
  display_thread_ids: true

runtime:
  n_cores: 0
  thread_name: "slim-data-plane"
  drain_timeout: 10s

services:
  slim/0:
    pubsub:
      clients:
        - endpoint: "https://localhost:46357"
          tls:
            ca_file: "./config/crypto/server-ca-cert.pem"
          auth:
            jwt:
              claims:
                audience: "slim"
                issuer: "slim"
                subject: "slim"
              duration: 1h
              key:
                encoding:
                  algorithm: "ES256"
                  pem: |
                    -----BEGIN PRIVATE KEY-----
                    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgHxGmmgX3iqp2IObA
                    xpAHLQG38v8KPjkgvUKL3YUQoruhRANCAATcA5dEBtjnE/T3Dv0dxsjoXDPeMcRS
                    6R6skqjLgcd4jtiMS79ZdKbr0Lu97wh3IuAWdf4pFSRZ+PRHbBNFThVh
                    -----END PRIVATE KEY-----
