version: '3'

tasks:
  build:
    desc: Build the slimrpc examples
    cmds:
      - cargo build --package agntcy-slimrpc-examples

  run-server:
    desc: Run the server example
    cmds:
      - cargo run --package agntcy-slimrpc-examples --bin server

  run-client-unary:
    desc: Run the client example (unary-unary RPC)
    cmds:
      - cargo run --package agntcy-slimrpc-examples --bin client -- --rpc-type unary

  run-client-unary-stream:
    desc: Run the client example (unary-stream RPC)
    cmds:
      - cargo run --package agntcy-slimrpc-examples --bin client -- --rpc-type unary-stream

  run-client-stream-unary:
    desc: Run the client example (stream-unary RPC)
    cmds:
      - cargo run --package agntcy-slimrpc-examples --bin client -- --rpc-type stream-unary

  run-client-stream-stream:
    desc: Run the client example (stream-stream RPC)
    cmds:
      - cargo run --package agntcy-slimrpc-examples --bin client -- --rpc-type stream-stream

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean --package agntcy-slimrpc-examples
