// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.0
// source: controller/v1/controller.proto

package controllerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionType int32

const (
	ConnectionType_CONNECTION_TYPE_LOCAL  ConnectionType = 0
	ConnectionType_CONNECTION_TYPE_REMOTE ConnectionType = 1
)

// Enum value maps for ConnectionType.
var (
	ConnectionType_name = map[int32]string{
		0: "CONNECTION_TYPE_LOCAL",
		1: "CONNECTION_TYPE_REMOTE",
	}
	ConnectionType_value = map[string]int32{
		"CONNECTION_TYPE_LOCAL":  0,
		"CONNECTION_TYPE_REMOTE": 1,
	}
)

func (x ConnectionType) Enum() *ConnectionType {
	p := new(ConnectionType)
	*p = x
	return p
}

func (x ConnectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_v1_controller_proto_enumTypes[0].Descriptor()
}

func (ConnectionType) Type() protoreflect.EnumType {
	return &file_controller_v1_controller_proto_enumTypes[0]
}

func (x ConnectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionType.Descriptor instead.
func (ConnectionType) EnumDescriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{0}
}

type ControlMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_ConfigCommand
	//	*ControlMessage_Ack
	//	*ControlMessage_SubscriptionListRequest
	//	*ControlMessage_SubscriptionListResponse
	//	*ControlMessage_ConnectionListRequest
	//	*ControlMessage_ConnectionListResponse
	//	*ControlMessage_RegisterNodeRequest
	//	*ControlMessage_RegisterNodeResponse
	//	*ControlMessage_DeregisterNodeRequest
	//	*ControlMessage_DeregisterNodeResponse
	//	*ControlMessage_CreateChannelRequest
	//	*ControlMessage_DeleteChannelRequest
	//	*ControlMessage_AddParticipantRequest
	//	*ControlMessage_DeleteParticipantRequest
	//	*ControlMessage_ListChannelRequest
	//	*ControlMessage_ListChannelResponse
	//	*ControlMessage_ListParticipantsRequest
	//	*ControlMessage_ListParticipantsResponse
	//	*ControlMessage_ConfigCommandAck
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_controller_v1_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetConfigCommand() *ConfigurationCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ConfigCommand); ok {
			return x.ConfigCommand
		}
	}
	return nil
}

func (x *ControlMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ControlMessage) GetSubscriptionListRequest() *SubscriptionListRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_SubscriptionListRequest); ok {
			return x.SubscriptionListRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetSubscriptionListResponse() *SubscriptionListResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_SubscriptionListResponse); ok {
			return x.SubscriptionListResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetConnectionListRequest() *ConnectionListRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ConnectionListRequest); ok {
			return x.ConnectionListRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetConnectionListResponse() *ConnectionListResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ConnectionListResponse); ok {
			return x.ConnectionListResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetRegisterNodeRequest() *RegisterNodeRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_RegisterNodeRequest); ok {
			return x.RegisterNodeRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetRegisterNodeResponse() *RegisterNodeResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_RegisterNodeResponse); ok {
			return x.RegisterNodeResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetDeregisterNodeRequest() *DeregisterNodeRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_DeregisterNodeRequest); ok {
			return x.DeregisterNodeRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetDeregisterNodeResponse() *DeregisterNodeResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_DeregisterNodeResponse); ok {
			return x.DeregisterNodeResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetCreateChannelRequest() *CreateChannelRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_CreateChannelRequest); ok {
			return x.CreateChannelRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetDeleteChannelRequest() *DeleteChannelRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_DeleteChannelRequest); ok {
			return x.DeleteChannelRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetAddParticipantRequest() *AddParticipantRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_AddParticipantRequest); ok {
			return x.AddParticipantRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetDeleteParticipantRequest() *DeleteParticipantRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_DeleteParticipantRequest); ok {
			return x.DeleteParticipantRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetListChannelRequest() *ListChannelsRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ListChannelRequest); ok {
			return x.ListChannelRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetListChannelResponse() *ListChannelsResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ListChannelResponse); ok {
			return x.ListChannelResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetListParticipantsRequest() *ListParticipantsRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ListParticipantsRequest); ok {
			return x.ListParticipantsRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetListParticipantsResponse() *ListParticipantsResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ListParticipantsResponse); ok {
			return x.ListParticipantsResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetConfigCommandAck() *ConfigurationCommandAck {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ConfigCommandAck); ok {
			return x.ConfigCommandAck
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_ConfigCommand struct {
	ConfigCommand *ConfigurationCommand `protobuf:"bytes,2,opt,name=config_command,json=configCommand,proto3,oneof"`
}

type ControlMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type ControlMessage_SubscriptionListRequest struct {
	SubscriptionListRequest *SubscriptionListRequest `protobuf:"bytes,4,opt,name=subscription_list_request,json=subscriptionListRequest,proto3,oneof"`
}

type ControlMessage_SubscriptionListResponse struct {
	SubscriptionListResponse *SubscriptionListResponse `protobuf:"bytes,5,opt,name=subscription_list_response,json=subscriptionListResponse,proto3,oneof"`
}

type ControlMessage_ConnectionListRequest struct {
	ConnectionListRequest *ConnectionListRequest `protobuf:"bytes,6,opt,name=connection_list_request,json=connectionListRequest,proto3,oneof"`
}

type ControlMessage_ConnectionListResponse struct {
	ConnectionListResponse *ConnectionListResponse `protobuf:"bytes,7,opt,name=connection_list_response,json=connectionListResponse,proto3,oneof"`
}

type ControlMessage_RegisterNodeRequest struct {
	RegisterNodeRequest *RegisterNodeRequest `protobuf:"bytes,8,opt,name=register_node_request,json=registerNodeRequest,proto3,oneof"`
}

type ControlMessage_RegisterNodeResponse struct {
	RegisterNodeResponse *RegisterNodeResponse `protobuf:"bytes,9,opt,name=register_node_response,json=registerNodeResponse,proto3,oneof"`
}

type ControlMessage_DeregisterNodeRequest struct {
	DeregisterNodeRequest *DeregisterNodeRequest `protobuf:"bytes,10,opt,name=deregister_node_request,json=deregisterNodeRequest,proto3,oneof"`
}

type ControlMessage_DeregisterNodeResponse struct {
	DeregisterNodeResponse *DeregisterNodeResponse `protobuf:"bytes,11,opt,name=deregister_node_response,json=deregisterNodeResponse,proto3,oneof"`
}

type ControlMessage_CreateChannelRequest struct {
	CreateChannelRequest *CreateChannelRequest `protobuf:"bytes,12,opt,name=create_channel_request,json=createChannelRequest,proto3,oneof"`
}

type ControlMessage_DeleteChannelRequest struct {
	DeleteChannelRequest *DeleteChannelRequest `protobuf:"bytes,13,opt,name=delete_channel_request,json=deleteChannelRequest,proto3,oneof"`
}

type ControlMessage_AddParticipantRequest struct {
	AddParticipantRequest *AddParticipantRequest `protobuf:"bytes,14,opt,name=add_participant_request,json=addParticipantRequest,proto3,oneof"`
}

type ControlMessage_DeleteParticipantRequest struct {
	DeleteParticipantRequest *DeleteParticipantRequest `protobuf:"bytes,15,opt,name=delete_participant_request,json=deleteParticipantRequest,proto3,oneof"`
}

type ControlMessage_ListChannelRequest struct {
	ListChannelRequest *ListChannelsRequest `protobuf:"bytes,16,opt,name=list_channel_request,json=listChannelRequest,proto3,oneof"`
}

type ControlMessage_ListChannelResponse struct {
	ListChannelResponse *ListChannelsResponse `protobuf:"bytes,17,opt,name=list_channel_response,json=listChannelResponse,proto3,oneof"`
}

type ControlMessage_ListParticipantsRequest struct {
	ListParticipantsRequest *ListParticipantsRequest `protobuf:"bytes,18,opt,name=list_participants_request,json=listParticipantsRequest,proto3,oneof"`
}

type ControlMessage_ListParticipantsResponse struct {
	ListParticipantsResponse *ListParticipantsResponse `protobuf:"bytes,19,opt,name=list_participants_response,json=listParticipantsResponse,proto3,oneof"`
}

type ControlMessage_ConfigCommandAck struct {
	ConfigCommandAck *ConfigurationCommandAck `protobuf:"bytes,20,opt,name=config_command_ack,json=configCommandAck,proto3,oneof"`
}

func (*ControlMessage_ConfigCommand) isControlMessage_Payload() {}

func (*ControlMessage_Ack) isControlMessage_Payload() {}

func (*ControlMessage_SubscriptionListRequest) isControlMessage_Payload() {}

func (*ControlMessage_SubscriptionListResponse) isControlMessage_Payload() {}

func (*ControlMessage_ConnectionListRequest) isControlMessage_Payload() {}

func (*ControlMessage_ConnectionListResponse) isControlMessage_Payload() {}

func (*ControlMessage_RegisterNodeRequest) isControlMessage_Payload() {}

func (*ControlMessage_RegisterNodeResponse) isControlMessage_Payload() {}

func (*ControlMessage_DeregisterNodeRequest) isControlMessage_Payload() {}

func (*ControlMessage_DeregisterNodeResponse) isControlMessage_Payload() {}

func (*ControlMessage_CreateChannelRequest) isControlMessage_Payload() {}

func (*ControlMessage_DeleteChannelRequest) isControlMessage_Payload() {}

func (*ControlMessage_AddParticipantRequest) isControlMessage_Payload() {}

func (*ControlMessage_DeleteParticipantRequest) isControlMessage_Payload() {}

func (*ControlMessage_ListChannelRequest) isControlMessage_Payload() {}

func (*ControlMessage_ListChannelResponse) isControlMessage_Payload() {}

func (*ControlMessage_ListParticipantsRequest) isControlMessage_Payload() {}

func (*ControlMessage_ListParticipantsResponse) isControlMessage_Payload() {}

func (*ControlMessage_ConfigCommandAck) isControlMessage_Payload() {}

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ConfigData    string                 `protobuf:"bytes,2,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_controller_v1_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{1}
}

func (x *Connection) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Connection) GetConfigData() string {
	if x != nil {
		return x.ConfigData
	}
	return ""
}

type ConnectionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionAck) Reset() {
	*x = ConnectionAck{}
	mi := &file_controller_v1_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionAck) ProtoMessage() {}

func (x *ConnectionAck) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionAck.ProtoReflect.Descriptor instead.
func (*ConnectionAck) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionAck) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectionAck) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type Subscription struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Component_0   string                  `protobuf:"bytes,1,opt,name=component_0,json=component0,proto3" json:"component_0,omitempty"`
	Component_1   string                  `protobuf:"bytes,2,opt,name=component_1,json=component1,proto3" json:"component_1,omitempty"`
	Component_2   string                  `protobuf:"bytes,3,opt,name=component_2,json=component2,proto3" json:"component_2,omitempty"`
	Id            *wrapperspb.UInt64Value `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	ConnectionId  string                  `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	NodeId        *string                 `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_controller_v1_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{3}
}

func (x *Subscription) GetComponent_0() string {
	if x != nil {
		return x.Component_0
	}
	return ""
}

func (x *Subscription) GetComponent_1() string {
	if x != nil {
		return x.Component_1
	}
	return ""
}

func (x *Subscription) GetComponent_2() string {
	if x != nil {
		return x.Component_2
	}
	return ""
}

func (x *Subscription) GetId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Subscription) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Subscription) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

type SubscriptionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionAck) Reset() {
	*x = SubscriptionAck{}
	mi := &file_controller_v1_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionAck) ProtoMessage() {}

func (x *SubscriptionAck) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionAck.ProtoReflect.Descriptor instead.
func (*SubscriptionAck) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{4}
}

func (x *SubscriptionAck) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *SubscriptionAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubscriptionAck) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ConfigurationCommand struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ConnectionsToCreate   []*Connection          `protobuf:"bytes,1,rep,name=connections_to_create,json=connectionsToCreate,proto3" json:"connections_to_create,omitempty"`
	SubscriptionsToSet    []*Subscription        `protobuf:"bytes,2,rep,name=subscriptions_to_set,json=subscriptionsToSet,proto3" json:"subscriptions_to_set,omitempty"`
	SubscriptionsToDelete []*Subscription        `protobuf:"bytes,3,rep,name=subscriptions_to_delete,json=subscriptionsToDelete,proto3" json:"subscriptions_to_delete,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConfigurationCommand) Reset() {
	*x = ConfigurationCommand{}
	mi := &file_controller_v1_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationCommand) ProtoMessage() {}

func (x *ConfigurationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationCommand.ProtoReflect.Descriptor instead.
func (*ConfigurationCommand) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigurationCommand) GetConnectionsToCreate() []*Connection {
	if x != nil {
		return x.ConnectionsToCreate
	}
	return nil
}

func (x *ConfigurationCommand) GetSubscriptionsToSet() []*Subscription {
	if x != nil {
		return x.SubscriptionsToSet
	}
	return nil
}

func (x *ConfigurationCommand) GetSubscriptionsToDelete() []*Subscription {
	if x != nil {
		return x.SubscriptionsToDelete
	}
	return nil
}

type ConfigurationCommandAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessageId   string                 `protobuf:"bytes,1,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	ConnectionsStatus   []*ConnectionAck       `protobuf:"bytes,2,rep,name=connections_status,json=connectionsStatus,proto3" json:"connections_status,omitempty"`
	SubscriptionsStatus []*SubscriptionAck     `protobuf:"bytes,3,rep,name=subscriptions_status,json=subscriptionsStatus,proto3" json:"subscriptions_status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigurationCommandAck) Reset() {
	*x = ConfigurationCommandAck{}
	mi := &file_controller_v1_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationCommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationCommandAck) ProtoMessage() {}

func (x *ConfigurationCommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationCommandAck.ProtoReflect.Descriptor instead.
func (*ConfigurationCommandAck) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigurationCommandAck) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *ConfigurationCommandAck) GetConnectionsStatus() []*ConnectionAck {
	if x != nil {
		return x.ConnectionsStatus
	}
	return nil
}

func (x *ConfigurationCommandAck) GetSubscriptionsStatus() []*SubscriptionAck {
	if x != nil {
		return x.SubscriptionsStatus
	}
	return nil
}

type Ack struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessageId string                 `protobuf:"bytes,1,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	Success           bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Messages          []string               `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_controller_v1_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SubscriptionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionListRequest) Reset() {
	*x = SubscriptionListRequest{}
	mi := &file_controller_v1_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionListRequest) ProtoMessage() {}

func (x *SubscriptionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionListRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionListRequest) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{8}
}

type SubscriptionListResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessageId string                 `protobuf:"bytes,1,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	Entries           []*SubscriptionEntry   `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubscriptionListResponse) Reset() {
	*x = SubscriptionListResponse{}
	mi := &file_controller_v1_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionListResponse) ProtoMessage() {}

func (x *SubscriptionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionListResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionListResponse) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{9}
}

func (x *SubscriptionListResponse) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *SubscriptionListResponse) GetEntries() []*SubscriptionEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SubscriptionEntry struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Component_0       string                  `protobuf:"bytes,1,opt,name=component_0,json=component0,proto3" json:"component_0,omitempty"`
	Component_1       string                  `protobuf:"bytes,2,opt,name=component_1,json=component1,proto3" json:"component_1,omitempty"`
	Component_2       string                  `protobuf:"bytes,3,opt,name=component_2,json=component2,proto3" json:"component_2,omitempty"`
	Id                *wrapperspb.UInt64Value `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	LocalConnections  []*ConnectionEntry      `protobuf:"bytes,5,rep,name=local_connections,json=localConnections,proto3" json:"local_connections,omitempty"`
	RemoteConnections []*ConnectionEntry      `protobuf:"bytes,6,rep,name=remote_connections,json=remoteConnections,proto3" json:"remote_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubscriptionEntry) Reset() {
	*x = SubscriptionEntry{}
	mi := &file_controller_v1_controller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionEntry) ProtoMessage() {}

func (x *SubscriptionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionEntry.ProtoReflect.Descriptor instead.
func (*SubscriptionEntry) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{10}
}

func (x *SubscriptionEntry) GetComponent_0() string {
	if x != nil {
		return x.Component_0
	}
	return ""
}

func (x *SubscriptionEntry) GetComponent_1() string {
	if x != nil {
		return x.Component_1
	}
	return ""
}

func (x *SubscriptionEntry) GetComponent_2() string {
	if x != nil {
		return x.Component_2
	}
	return ""
}

func (x *SubscriptionEntry) GetId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SubscriptionEntry) GetLocalConnections() []*ConnectionEntry {
	if x != nil {
		return x.LocalConnections
	}
	return nil
}

func (x *SubscriptionEntry) GetRemoteConnections() []*ConnectionEntry {
	if x != nil {
		return x.RemoteConnections
	}
	return nil
}

type ConnectionEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConnectionType ConnectionType         `protobuf:"varint,2,opt,name=connection_type,json=connectionType,proto3,enum=controller.proto.v1.ConnectionType" json:"connection_type,omitempty"`
	ConfigData     string                 `protobuf:"bytes,3,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionEntry) Reset() {
	*x = ConnectionEntry{}
	mi := &file_controller_v1_controller_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionEntry) ProtoMessage() {}

func (x *ConnectionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionEntry.ProtoReflect.Descriptor instead.
func (*ConnectionEntry) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectionEntry) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectionEntry) GetConnectionType() ConnectionType {
	if x != nil {
		return x.ConnectionType
	}
	return ConnectionType_CONNECTION_TYPE_LOCAL
}

func (x *ConnectionEntry) GetConfigData() string {
	if x != nil {
		return x.ConfigData
	}
	return ""
}

type ConnectionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionListRequest) Reset() {
	*x = ConnectionListRequest{}
	mi := &file_controller_v1_controller_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionListRequest) ProtoMessage() {}

func (x *ConnectionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionListRequest.ProtoReflect.Descriptor instead.
func (*ConnectionListRequest) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{12}
}

type ConnectionListResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessageId string                 `protobuf:"bytes,1,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	Entries           []*ConnectionEntry     `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectionListResponse) Reset() {
	*x = ConnectionListResponse{}
	mi := &file_controller_v1_controller_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionListResponse) ProtoMessage() {}

func (x *ConnectionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionListResponse.ProtoReflect.Descriptor instead.
func (*ConnectionListResponse) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{13}
}

func (x *ConnectionListResponse) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *ConnectionListResponse) GetEntries() []*ConnectionEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_controller_v1_controller_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{14}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConnectionDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	MtlsRequired  bool                   `protobuf:"varint,2,opt,name=mtls_required,json=mtlsRequired,proto3" json:"mtls_required,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Auth          *string                `protobuf:"bytes,4,opt,name=auth,proto3,oneof" json:"auth,omitempty"`
	Tls           *string                `protobuf:"bytes,5,opt,name=tls,proto3,oneof" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionDetails) Reset() {
	*x = ConnectionDetails{}
	mi := &file_controller_v1_controller_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionDetails) ProtoMessage() {}

func (x *ConnectionDetails) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionDetails.ProtoReflect.Descriptor instead.
func (*ConnectionDetails) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{15}
}

func (x *ConnectionDetails) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ConnectionDetails) GetMtlsRequired() bool {
	if x != nil {
		return x.MtlsRequired
	}
	return false
}

func (x *ConnectionDetails) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ConnectionDetails) GetAuth() string {
	if x != nil && x.Auth != nil {
		return *x.Auth
	}
	return ""
}

func (x *ConnectionDetails) GetTls() string {
	if x != nil && x.Tls != nil {
		return *x.Tls
	}
	return ""
}

type RegisterNodeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ConnectionDetails []*ConnectionDetails   `protobuf:"bytes,2,rep,name=connection_details,json=connectionDetails,proto3" json:"connection_details,omitempty"`
	GroupName         *string                `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3,oneof" json:"group_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_controller_v1_controller_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetConnectionDetails() []*ConnectionDetails {
	if x != nil {
		return x.ConnectionDetails
	}
	return nil
}

func (x *RegisterNodeRequest) GetGroupName() string {
	if x != nil && x.GroupName != nil {
		return *x.GroupName
	}
	return ""
}

type RegisterNodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessageId string                 `protobuf:"bytes,1,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	Success           bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_controller_v1_controller_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterNodeResponse) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeregisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterNodeRequest) Reset() {
	*x = DeregisterNodeRequest{}
	mi := &file_controller_v1_controller_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterNodeRequest) ProtoMessage() {}

func (x *DeregisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterNodeRequest.ProtoReflect.Descriptor instead.
func (*DeregisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{18}
}

func (x *DeregisterNodeRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type DeregisterNodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessageId string                 `protobuf:"bytes,1,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	Success           bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeregisterNodeResponse) Reset() {
	*x = DeregisterNodeResponse{}
	mi := &file_controller_v1_controller_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterNodeResponse) ProtoMessage() {}

func (x *DeregisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterNodeResponse.ProtoReflect.Descriptor instead.
func (*DeregisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{19}
}

func (x *DeregisterNodeResponse) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *DeregisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of moderators for the channel
	Moderators []string `protobuf:"bytes,1,rep,name=moderators,proto3" json:"moderators,omitempty"`
	// The channel name in the form organization/namespace/channel_name
	ChannelName   string `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_controller_v1_controller_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{20}
}

func (x *CreateChannelRequest) GetModerators() []string {
	if x != nil {
		return x.Moderators
	}
	return nil
}

func (x *CreateChannelRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

type DeleteChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel name in the form organization/namespace/channel_name
	ChannelName string `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	// list of moderators for the channel
	Moderators    []string `protobuf:"bytes,2,rep,name=moderators,proto3" json:"moderators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	mi := &file_controller_v1_controller_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteChannelRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *DeleteChannelRequest) GetModerators() []string {
	if x != nil {
		return x.Moderators
	}
	return nil
}

type AddParticipantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel name in the form organization/namespace/channel_name
	ChannelName string `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	// Name of the participant
	ParticipantName string `protobuf:"bytes,2,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	// list of moderators for the channel
	Moderators    []string `protobuf:"bytes,3,rep,name=moderators,proto3" json:"moderators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParticipantRequest) Reset() {
	*x = AddParticipantRequest{}
	mi := &file_controller_v1_controller_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParticipantRequest) ProtoMessage() {}

func (x *AddParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParticipantRequest.ProtoReflect.Descriptor instead.
func (*AddParticipantRequest) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{22}
}

func (x *AddParticipantRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *AddParticipantRequest) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

func (x *AddParticipantRequest) GetModerators() []string {
	if x != nil {
		return x.Moderators
	}
	return nil
}

type DeleteParticipantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel name in the form organization/namespace/channel_name
	ChannelName string `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	// ID of participant
	ParticipantName string `protobuf:"bytes,2,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	// list of moderators for the channel
	Moderators    []string `protobuf:"bytes,3,rep,name=moderators,proto3" json:"moderators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteParticipantRequest) Reset() {
	*x = DeleteParticipantRequest{}
	mi := &file_controller_v1_controller_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteParticipantRequest) ProtoMessage() {}

func (x *DeleteParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteParticipantRequest.ProtoReflect.Descriptor instead.
func (*DeleteParticipantRequest) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteParticipantRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *DeleteParticipantRequest) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

func (x *DeleteParticipantRequest) GetModerators() []string {
	if x != nil {
		return x.Moderators
	}
	return nil
}

type ListChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_controller_v1_controller_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{24}
}

type ListChannelsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessageId string                 `protobuf:"bytes,1,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	// IDs of the channels available in the control plane
	ChannelName   []string `protobuf:"bytes,2,rep,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_controller_v1_controller_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{25}
}

func (x *ListChannelsResponse) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *ListChannelsResponse) GetChannelName() []string {
	if x != nil {
		return x.ChannelName
	}
	return nil
}

type ListParticipantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the channel
	ChannelName   string `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParticipantsRequest) Reset() {
	*x = ListParticipantsRequest{}
	mi := &file_controller_v1_controller_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParticipantsRequest) ProtoMessage() {}

func (x *ListParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParticipantsRequest.ProtoReflect.Descriptor instead.
func (*ListParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{26}
}

func (x *ListParticipantsRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

type ListParticipantsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessageId string                 `protobuf:"bytes,1,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	// list of participants in the channel
	ParticipantName []string `protobuf:"bytes,2,rep,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListParticipantsResponse) Reset() {
	*x = ListParticipantsResponse{}
	mi := &file_controller_v1_controller_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParticipantsResponse) ProtoMessage() {}

func (x *ListParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParticipantsResponse.ProtoReflect.Descriptor instead.
func (*ListParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{27}
}

func (x *ListParticipantsResponse) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *ListParticipantsResponse) GetParticipantName() []string {
	if x != nil {
		return x.ParticipantName
	}
	return nil
}

var File_controller_v1_controller_proto protoreflect.FileDescriptor

const file_controller_v1_controller_proto_rawDesc = "" +
	"\n" +
	"\x1econtroller/v1/controller.proto\x12\x13controller.proto.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8b\x0f\n" +
	"\x0eControlMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12R\n" +
	"\x0econfig_command\x18\x02 \x01(\v2).controller.proto.v1.ConfigurationCommandH\x00R\rconfigCommand\x12,\n" +
	"\x03ack\x18\x03 \x01(\v2\x18.controller.proto.v1.AckH\x00R\x03ack\x12j\n" +
	"\x19subscription_list_request\x18\x04 \x01(\v2,.controller.proto.v1.SubscriptionListRequestH\x00R\x17subscriptionListRequest\x12m\n" +
	"\x1asubscription_list_response\x18\x05 \x01(\v2-.controller.proto.v1.SubscriptionListResponseH\x00R\x18subscriptionListResponse\x12d\n" +
	"\x17connection_list_request\x18\x06 \x01(\v2*.controller.proto.v1.ConnectionListRequestH\x00R\x15connectionListRequest\x12g\n" +
	"\x18connection_list_response\x18\a \x01(\v2+.controller.proto.v1.ConnectionListResponseH\x00R\x16connectionListResponse\x12^\n" +
	"\x15register_node_request\x18\b \x01(\v2(.controller.proto.v1.RegisterNodeRequestH\x00R\x13registerNodeRequest\x12a\n" +
	"\x16register_node_response\x18\t \x01(\v2).controller.proto.v1.RegisterNodeResponseH\x00R\x14registerNodeResponse\x12d\n" +
	"\x17deregister_node_request\x18\n" +
	" \x01(\v2*.controller.proto.v1.DeregisterNodeRequestH\x00R\x15deregisterNodeRequest\x12g\n" +
	"\x18deregister_node_response\x18\v \x01(\v2+.controller.proto.v1.DeregisterNodeResponseH\x00R\x16deregisterNodeResponse\x12a\n" +
	"\x16create_channel_request\x18\f \x01(\v2).controller.proto.v1.CreateChannelRequestH\x00R\x14createChannelRequest\x12a\n" +
	"\x16delete_channel_request\x18\r \x01(\v2).controller.proto.v1.DeleteChannelRequestH\x00R\x14deleteChannelRequest\x12d\n" +
	"\x17add_participant_request\x18\x0e \x01(\v2*.controller.proto.v1.AddParticipantRequestH\x00R\x15addParticipantRequest\x12m\n" +
	"\x1adelete_participant_request\x18\x0f \x01(\v2-.controller.proto.v1.DeleteParticipantRequestH\x00R\x18deleteParticipantRequest\x12\\\n" +
	"\x14list_channel_request\x18\x10 \x01(\v2(.controller.proto.v1.ListChannelsRequestH\x00R\x12listChannelRequest\x12_\n" +
	"\x15list_channel_response\x18\x11 \x01(\v2).controller.proto.v1.ListChannelsResponseH\x00R\x13listChannelResponse\x12j\n" +
	"\x19list_participants_request\x18\x12 \x01(\v2,.controller.proto.v1.ListParticipantsRequestH\x00R\x17listParticipantsRequest\x12m\n" +
	"\x1alist_participants_response\x18\x13 \x01(\v2-.controller.proto.v1.ListParticipantsResponseH\x00R\x18listParticipantsResponse\x12\\\n" +
	"\x12config_command_ack\x18\x14 \x01(\v2,.controller.proto.v1.ConfigurationCommandAckH\x00R\x10configCommandAckB\t\n" +
	"\apayload\"R\n" +
	"\n" +
	"Connection\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1f\n" +
	"\vconfig_data\x18\x02 \x01(\tR\n" +
	"configData\"j\n" +
	"\rConnectionAck\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1a\n" +
	"\berrorMsg\x18\x03 \x01(\tR\berrorMsg\"\xee\x01\n" +
	"\fSubscription\x12\x1f\n" +
	"\vcomponent_0\x18\x01 \x01(\tR\n" +
	"component0\x12\x1f\n" +
	"\vcomponent_1\x18\x02 \x01(\tR\n" +
	"component1\x12\x1f\n" +
	"\vcomponent_2\x18\x03 \x01(\tR\n" +
	"component2\x12,\n" +
	"\x02id\x18\x04 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x02id\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12\x1c\n" +
	"\anode_id\x18\x06 \x01(\tH\x00R\x06nodeId\x88\x01\x01B\n" +
	"\n" +
	"\b_node_id\"\x8e\x01\n" +
	"\x0fSubscriptionAck\x12E\n" +
	"\fsubscription\x18\x01 \x01(\v2!.controller.proto.v1.SubscriptionR\fsubscription\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1a\n" +
	"\berrorMsg\x18\x03 \x01(\tR\berrorMsg\"\x9b\x02\n" +
	"\x14ConfigurationCommand\x12S\n" +
	"\x15connections_to_create\x18\x01 \x03(\v2\x1f.controller.proto.v1.ConnectionR\x13connectionsToCreate\x12S\n" +
	"\x14subscriptions_to_set\x18\x02 \x03(\v2!.controller.proto.v1.SubscriptionR\x12subscriptionsToSet\x12Y\n" +
	"\x17subscriptions_to_delete\x18\x03 \x03(\v2!.controller.proto.v1.SubscriptionR\x15subscriptionsToDelete\"\xf5\x01\n" +
	"\x17ConfigurationCommandAck\x12.\n" +
	"\x13original_message_id\x18\x01 \x01(\tR\x11originalMessageId\x12Q\n" +
	"\x12connections_status\x18\x02 \x03(\v2\".controller.proto.v1.ConnectionAckR\x11connectionsStatus\x12W\n" +
	"\x14subscriptions_status\x18\x03 \x03(\v2$.controller.proto.v1.SubscriptionAckR\x13subscriptionsStatus\"k\n" +
	"\x03Ack\x12.\n" +
	"\x13original_message_id\x18\x01 \x01(\tR\x11originalMessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1a\n" +
	"\bmessages\x18\x03 \x03(\tR\bmessages\"\x19\n" +
	"\x17SubscriptionListRequest\"\x8c\x01\n" +
	"\x18SubscriptionListResponse\x12.\n" +
	"\x13original_message_id\x18\x01 \x01(\tR\x11originalMessageId\x12@\n" +
	"\aentries\x18\x02 \x03(\v2&.controller.proto.v1.SubscriptionEntryR\aentries\"\xcc\x02\n" +
	"\x11SubscriptionEntry\x12\x1f\n" +
	"\vcomponent_0\x18\x01 \x01(\tR\n" +
	"component0\x12\x1f\n" +
	"\vcomponent_1\x18\x02 \x01(\tR\n" +
	"component1\x12\x1f\n" +
	"\vcomponent_2\x18\x03 \x01(\tR\n" +
	"component2\x12,\n" +
	"\x02id\x18\x04 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x02id\x12Q\n" +
	"\x11local_connections\x18\x05 \x03(\v2$.controller.proto.v1.ConnectionEntryR\x10localConnections\x12S\n" +
	"\x12remote_connections\x18\x06 \x03(\v2$.controller.proto.v1.ConnectionEntryR\x11remoteConnections\"\x90\x01\n" +
	"\x0fConnectionEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12L\n" +
	"\x0fconnection_type\x18\x02 \x01(\x0e2#.controller.proto.v1.ConnectionTypeR\x0econnectionType\x12\x1f\n" +
	"\vconfig_data\x18\x03 \x01(\tR\n" +
	"configData\"\x17\n" +
	"\x15ConnectionListRequest\"\x88\x01\n" +
	"\x16ConnectionListResponse\x12.\n" +
	"\x13original_message_id\x18\x01 \x01(\tR\x11originalMessageId\x12>\n" +
	"\aentries\x18\x02 \x03(\v2$.controller.proto.v1.ConnectionEntryR\aentries\"\x16\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xca\x01\n" +
	"\x11ConnectionDetails\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12#\n" +
	"\rmtls_required\x18\x02 \x01(\bR\fmtlsRequired\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x17\n" +
	"\x04auth\x18\x04 \x01(\tH\x00R\x04auth\x88\x01\x01\x12\x15\n" +
	"\x03tls\x18\x05 \x01(\tH\x01R\x03tls\x88\x01\x01B\a\n" +
	"\x05_authB\x06\n" +
	"\x04_tls\"\xb8\x01\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12U\n" +
	"\x12connection_details\x18\x02 \x03(\v2&.controller.proto.v1.ConnectionDetailsR\x11connectionDetails\x12\"\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tH\x00R\tgroupName\x88\x01\x01B\r\n" +
	"\v_group_name\"`\n" +
	"\x14RegisterNodeResponse\x12.\n" +
	"\x13original_message_id\x18\x01 \x01(\tR\x11originalMessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"F\n" +
	"\x15DeregisterNodeRequest\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.controller.proto.v1.NodeR\x04node\"b\n" +
	"\x16DeregisterNodeResponse\x12.\n" +
	"\x13original_message_id\x18\x01 \x01(\tR\x11originalMessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"Y\n" +
	"\x14CreateChannelRequest\x12\x1e\n" +
	"\n" +
	"moderators\x18\x01 \x03(\tR\n" +
	"moderators\x12!\n" +
	"\fchannel_name\x18\x02 \x01(\tR\vchannelName\"Y\n" +
	"\x14DeleteChannelRequest\x12!\n" +
	"\fchannel_name\x18\x01 \x01(\tR\vchannelName\x12\x1e\n" +
	"\n" +
	"moderators\x18\x02 \x03(\tR\n" +
	"moderators\"\x85\x01\n" +
	"\x15AddParticipantRequest\x12!\n" +
	"\fchannel_name\x18\x01 \x01(\tR\vchannelName\x12)\n" +
	"\x10participant_name\x18\x02 \x01(\tR\x0fparticipantName\x12\x1e\n" +
	"\n" +
	"moderators\x18\x03 \x03(\tR\n" +
	"moderators\"\x88\x01\n" +
	"\x18DeleteParticipantRequest\x12!\n" +
	"\fchannel_name\x18\x01 \x01(\tR\vchannelName\x12)\n" +
	"\x10participant_name\x18\x02 \x01(\tR\x0fparticipantName\x12\x1e\n" +
	"\n" +
	"moderators\x18\x03 \x03(\tR\n" +
	"moderators\"\x15\n" +
	"\x13ListChannelsRequest\"i\n" +
	"\x14ListChannelsResponse\x12.\n" +
	"\x13original_message_id\x18\x01 \x01(\tR\x11originalMessageId\x12!\n" +
	"\fchannel_name\x18\x02 \x03(\tR\vchannelName\"<\n" +
	"\x17ListParticipantsRequest\x12!\n" +
	"\fchannel_name\x18\x01 \x01(\tR\vchannelName\"u\n" +
	"\x18ListParticipantsResponse\x12.\n" +
	"\x13original_message_id\x18\x01 \x01(\tR\x11originalMessageId\x12)\n" +
	"\x10participant_name\x18\x02 \x03(\tR\x0fparticipantName*G\n" +
	"\x0eConnectionType\x12\x19\n" +
	"\x15CONNECTION_TYPE_LOCAL\x10\x00\x12\x1a\n" +
	"\x16CONNECTION_TYPE_REMOTE\x10\x012y\n" +
	"\x11ControllerService\x12d\n" +
	"\x12OpenControlChannel\x12#.controller.proto.v1.ControlMessage\x1a#.controller.proto.v1.ControlMessage\"\x00(\x010\x01BNZLgithub.com/agntcy/slim/control-plane/common/proto/controller/v1;controllerv1b\x06proto3"

var (
	file_controller_v1_controller_proto_rawDescOnce sync.Once
	file_controller_v1_controller_proto_rawDescData []byte
)

func file_controller_v1_controller_proto_rawDescGZIP() []byte {
	file_controller_v1_controller_proto_rawDescOnce.Do(func() {
		file_controller_v1_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_v1_controller_proto_rawDesc), len(file_controller_v1_controller_proto_rawDesc)))
	})
	return file_controller_v1_controller_proto_rawDescData
}

var file_controller_v1_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controller_v1_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_controller_v1_controller_proto_goTypes = []any{
	(ConnectionType)(0),              // 0: controller.proto.v1.ConnectionType
	(*ControlMessage)(nil),           // 1: controller.proto.v1.ControlMessage
	(*Connection)(nil),               // 2: controller.proto.v1.Connection
	(*ConnectionAck)(nil),            // 3: controller.proto.v1.ConnectionAck
	(*Subscription)(nil),             // 4: controller.proto.v1.Subscription
	(*SubscriptionAck)(nil),          // 5: controller.proto.v1.SubscriptionAck
	(*ConfigurationCommand)(nil),     // 6: controller.proto.v1.ConfigurationCommand
	(*ConfigurationCommandAck)(nil),  // 7: controller.proto.v1.ConfigurationCommandAck
	(*Ack)(nil),                      // 8: controller.proto.v1.Ack
	(*SubscriptionListRequest)(nil),  // 9: controller.proto.v1.SubscriptionListRequest
	(*SubscriptionListResponse)(nil), // 10: controller.proto.v1.SubscriptionListResponse
	(*SubscriptionEntry)(nil),        // 11: controller.proto.v1.SubscriptionEntry
	(*ConnectionEntry)(nil),          // 12: controller.proto.v1.ConnectionEntry
	(*ConnectionListRequest)(nil),    // 13: controller.proto.v1.ConnectionListRequest
	(*ConnectionListResponse)(nil),   // 14: controller.proto.v1.ConnectionListResponse
	(*Node)(nil),                     // 15: controller.proto.v1.Node
	(*ConnectionDetails)(nil),        // 16: controller.proto.v1.ConnectionDetails
	(*RegisterNodeRequest)(nil),      // 17: controller.proto.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),     // 18: controller.proto.v1.RegisterNodeResponse
	(*DeregisterNodeRequest)(nil),    // 19: controller.proto.v1.DeregisterNodeRequest
	(*DeregisterNodeResponse)(nil),   // 20: controller.proto.v1.DeregisterNodeResponse
	(*CreateChannelRequest)(nil),     // 21: controller.proto.v1.CreateChannelRequest
	(*DeleteChannelRequest)(nil),     // 22: controller.proto.v1.DeleteChannelRequest
	(*AddParticipantRequest)(nil),    // 23: controller.proto.v1.AddParticipantRequest
	(*DeleteParticipantRequest)(nil), // 24: controller.proto.v1.DeleteParticipantRequest
	(*ListChannelsRequest)(nil),      // 25: controller.proto.v1.ListChannelsRequest
	(*ListChannelsResponse)(nil),     // 26: controller.proto.v1.ListChannelsResponse
	(*ListParticipantsRequest)(nil),  // 27: controller.proto.v1.ListParticipantsRequest
	(*ListParticipantsResponse)(nil), // 28: controller.proto.v1.ListParticipantsResponse
	(*wrapperspb.UInt64Value)(nil),   // 29: google.protobuf.UInt64Value
	(*structpb.Struct)(nil),          // 30: google.protobuf.Struct
}
var file_controller_v1_controller_proto_depIdxs = []int32{
	6,  // 0: controller.proto.v1.ControlMessage.config_command:type_name -> controller.proto.v1.ConfigurationCommand
	8,  // 1: controller.proto.v1.ControlMessage.ack:type_name -> controller.proto.v1.Ack
	9,  // 2: controller.proto.v1.ControlMessage.subscription_list_request:type_name -> controller.proto.v1.SubscriptionListRequest
	10, // 3: controller.proto.v1.ControlMessage.subscription_list_response:type_name -> controller.proto.v1.SubscriptionListResponse
	13, // 4: controller.proto.v1.ControlMessage.connection_list_request:type_name -> controller.proto.v1.ConnectionListRequest
	14, // 5: controller.proto.v1.ControlMessage.connection_list_response:type_name -> controller.proto.v1.ConnectionListResponse
	17, // 6: controller.proto.v1.ControlMessage.register_node_request:type_name -> controller.proto.v1.RegisterNodeRequest
	18, // 7: controller.proto.v1.ControlMessage.register_node_response:type_name -> controller.proto.v1.RegisterNodeResponse
	19, // 8: controller.proto.v1.ControlMessage.deregister_node_request:type_name -> controller.proto.v1.DeregisterNodeRequest
	20, // 9: controller.proto.v1.ControlMessage.deregister_node_response:type_name -> controller.proto.v1.DeregisterNodeResponse
	21, // 10: controller.proto.v1.ControlMessage.create_channel_request:type_name -> controller.proto.v1.CreateChannelRequest
	22, // 11: controller.proto.v1.ControlMessage.delete_channel_request:type_name -> controller.proto.v1.DeleteChannelRequest
	23, // 12: controller.proto.v1.ControlMessage.add_participant_request:type_name -> controller.proto.v1.AddParticipantRequest
	24, // 13: controller.proto.v1.ControlMessage.delete_participant_request:type_name -> controller.proto.v1.DeleteParticipantRequest
	25, // 14: controller.proto.v1.ControlMessage.list_channel_request:type_name -> controller.proto.v1.ListChannelsRequest
	26, // 15: controller.proto.v1.ControlMessage.list_channel_response:type_name -> controller.proto.v1.ListChannelsResponse
	27, // 16: controller.proto.v1.ControlMessage.list_participants_request:type_name -> controller.proto.v1.ListParticipantsRequest
	28, // 17: controller.proto.v1.ControlMessage.list_participants_response:type_name -> controller.proto.v1.ListParticipantsResponse
	7,  // 18: controller.proto.v1.ControlMessage.config_command_ack:type_name -> controller.proto.v1.ConfigurationCommandAck
	29, // 19: controller.proto.v1.Subscription.id:type_name -> google.protobuf.UInt64Value
	4,  // 20: controller.proto.v1.SubscriptionAck.subscription:type_name -> controller.proto.v1.Subscription
	2,  // 21: controller.proto.v1.ConfigurationCommand.connections_to_create:type_name -> controller.proto.v1.Connection
	4,  // 22: controller.proto.v1.ConfigurationCommand.subscriptions_to_set:type_name -> controller.proto.v1.Subscription
	4,  // 23: controller.proto.v1.ConfigurationCommand.subscriptions_to_delete:type_name -> controller.proto.v1.Subscription
	3,  // 24: controller.proto.v1.ConfigurationCommandAck.connections_status:type_name -> controller.proto.v1.ConnectionAck
	5,  // 25: controller.proto.v1.ConfigurationCommandAck.subscriptions_status:type_name -> controller.proto.v1.SubscriptionAck
	11, // 26: controller.proto.v1.SubscriptionListResponse.entries:type_name -> controller.proto.v1.SubscriptionEntry
	29, // 27: controller.proto.v1.SubscriptionEntry.id:type_name -> google.protobuf.UInt64Value
	12, // 28: controller.proto.v1.SubscriptionEntry.local_connections:type_name -> controller.proto.v1.ConnectionEntry
	12, // 29: controller.proto.v1.SubscriptionEntry.remote_connections:type_name -> controller.proto.v1.ConnectionEntry
	0,  // 30: controller.proto.v1.ConnectionEntry.connection_type:type_name -> controller.proto.v1.ConnectionType
	12, // 31: controller.proto.v1.ConnectionListResponse.entries:type_name -> controller.proto.v1.ConnectionEntry
	30, // 32: controller.proto.v1.ConnectionDetails.metadata:type_name -> google.protobuf.Struct
	16, // 33: controller.proto.v1.RegisterNodeRequest.connection_details:type_name -> controller.proto.v1.ConnectionDetails
	15, // 34: controller.proto.v1.DeregisterNodeRequest.node:type_name -> controller.proto.v1.Node
	1,  // 35: controller.proto.v1.ControllerService.OpenControlChannel:input_type -> controller.proto.v1.ControlMessage
	1,  // 36: controller.proto.v1.ControllerService.OpenControlChannel:output_type -> controller.proto.v1.ControlMessage
	36, // [36:37] is the sub-list for method output_type
	35, // [35:36] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_controller_v1_controller_proto_init() }
func file_controller_v1_controller_proto_init() {
	if File_controller_v1_controller_proto != nil {
		return
	}
	file_controller_v1_controller_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlMessage_ConfigCommand)(nil),
		(*ControlMessage_Ack)(nil),
		(*ControlMessage_SubscriptionListRequest)(nil),
		(*ControlMessage_SubscriptionListResponse)(nil),
		(*ControlMessage_ConnectionListRequest)(nil),
		(*ControlMessage_ConnectionListResponse)(nil),
		(*ControlMessage_RegisterNodeRequest)(nil),
		(*ControlMessage_RegisterNodeResponse)(nil),
		(*ControlMessage_DeregisterNodeRequest)(nil),
		(*ControlMessage_DeregisterNodeResponse)(nil),
		(*ControlMessage_CreateChannelRequest)(nil),
		(*ControlMessage_DeleteChannelRequest)(nil),
		(*ControlMessage_AddParticipantRequest)(nil),
		(*ControlMessage_DeleteParticipantRequest)(nil),
		(*ControlMessage_ListChannelRequest)(nil),
		(*ControlMessage_ListChannelResponse)(nil),
		(*ControlMessage_ListParticipantsRequest)(nil),
		(*ControlMessage_ListParticipantsResponse)(nil),
		(*ControlMessage_ConfigCommandAck)(nil),
	}
	file_controller_v1_controller_proto_msgTypes[3].OneofWrappers = []any{}
	file_controller_v1_controller_proto_msgTypes[15].OneofWrappers = []any{}
	file_controller_v1_controller_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_v1_controller_proto_rawDesc), len(file_controller_v1_controller_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_v1_controller_proto_goTypes,
		DependencyIndexes: file_controller_v1_controller_proto_depIdxs,
		EnumInfos:         file_controller_v1_controller_proto_enumTypes,
		MessageInfos:      file_controller_v1_controller_proto_msgTypes,
	}.Build()
	File_controller_v1_controller_proto = out.File
	file_controller_v1_controller_proto_goTypes = nil
	file_controller_v1_controller_proto_depIdxs = nil
}
