version: 2

dist: .dist/slimctl

# Skip builds - binaries are pre-built by the reusable workflow
# We'll create archives manually in the GitHub Actions workflow
builds:
  - skip: true

# Disable archives since we're creating them manually
archives:
  - format: binary

# Disable checksums since we're creating them manually  
checksum:
  disable: true

changelog:
  disable: true

homebrew_casks:
  - name: slimctl
    description: "A CLI tool for managing SLIM Devices"
    homepage: "https://github.com/agntcy/slim/control-plane/slimctl"
    directory: Casks
    hooks:
      post:
        # workaround for the problem described here: https://goreleaser.com/customization/homebrew_casks/#signing-and-notarizing
        install: |
          system "chmod", "+x", "#{staged_path}/slimctl"
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slimctl"]
          end

    binaries:
      - slimctl

    url:
      template: "https://github.com/agntcy/slim/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      using: ":homebrew_curl"

    skip_upload: false

    repository:
      owner: agntcy
      name: "slim"

      branch: brew
      token: "{{ .Env.GITHUB_TOKEN }}"

      pull_request:
        enabled: true
        draft: false
