version: 2

dist: .dist/slimctl

builds:
  - main: cmd/main.go
    id: slimctl
    binary: slimctl
    dir: control-plane/slimctl

    env:
      - MAIN_MODULE="github.com/agntcy/slim"

    goos:
      #      - linux
      #      - windows
      - darwin
    ldflags:
      - -X '{{.Env.MAIN_MODULE}}/control-plane/slimctl/internal/cmd/version.semVersion={{.Version}}'
      - -X '{{.Env.MAIN_MODULE}}/control-plane/slimctl/internal/cmd/version.gitCommit={{.Commit}}'
      - -X '{{.Env.MAIN_MODULE}}/control-plane/slimctl/internal/cmd/version.buildDate={{.Date}}'

    hooks:
      pre:
        - cmd: go mod tidy
          dir: control-plane/slimctl
          output: true
        - cmd: task control-plane:gogen
          dir: control-plane
          output: true




archives:
  - name_template: "slimctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "slimctl_checksums.txt"

changelog:
  disable: true


homebrew_casks:
  - name: slimctl
    description: "A CLI tool for managing SLIM Devices"
    homepage: "https://github.com/agntcy/slim/tree/main/control-plane/slimctl"
    directory: Casks

    binaries:
      - slimctl

    url:
      template: "https://github.com/agntcy/slim/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      using: ":homebrew_curl"

    skip_upload: true

    repository:
      owner: agntcy
      branch: brew

      name: "agntcy/slim"



