version: 2

dist: .dist/slimctl

# Disable validation to allow custom tag patterns like slimctl-v1.0.0
# This prevents failures on patch versions or pre-releases
git:
  tag_sort: -version:refname

env:
  - CGO_ENABLED=1

builds:
  - id: slimctl
    main: cmd/main.go
    binary: slimctl
    dir: control-plane/slimctl
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

    ldflags:
      - -X github.com/agntcy/slim/control-plane/slimctl/internal/cmd/version.semVersion={{.Version}}
      - -X github.com/agntcy/slim/control-plane/slimctl/internal/cmd/version.gitCommit={{.Commit}}
      - -X github.com/agntcy/slim/control-plane/slimctl/internal/cmd/version.buildDate={{.Date}}

    # Exclude unsupported combinations
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

    hooks:
      pre:
        - cmd: go mod tidy
          dir: control-plane/slimctl
          output: true
        - cmd: task control-plane:go-bindings:setup TARGETOS={{ .Os }} TARGETARCH={{ .Arch }}
          output: true

archives:
  - name_template: "slimctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "slimctl_checksums.txt"

changelog:
  disable: true

release:
  # Disable GitHub release validation to support custom tag patterns
  disable: false
  # Allow pre-releases (e.g., v1.0.0-rc1, v1.0.0-beta.1)
  prerelease: auto
  # Don't fail on missing tag or version validation
  mode: keep-existing
  # Custom tag format
  name_template: "{{.Tag}}"

brews:
  - name: slimctl
    description: "A CLI tool for managing SLIM Devices"
    homepage: "https://github.com/agntcy/slim"
    
    # Use Casks directory for compatibility
    directory: Casks
    
    repository:
      owner: agntcy
      name: slim
      branch: brew
      token: "{{ .Env.GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
    
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    
    # Only include darwin builds for Homebrew
    ids:
      - slimctl
    
    install: |
      bin.install "slimctl"
