// Code generated by protoc-gen-slimrpc-java. DO NOT EDIT.
// source: example.proto

package com.example_service;

import io.agntcy.slim.bindings.BidiStreamHandler;
import io.agntcy.slim.bindings.Channel;
import io.agntcy.slim.bindings.Context;
import io.agntcy.slim.bindings.App;
import io.agntcy.slim.bindings.Name;
import io.agntcy.slim.bindings.RequestStream;
import io.agntcy.slim.bindings.RequestStreamWriter;
import io.agntcy.slim.bindings.ResponseSink;
import io.agntcy.slim.bindings.ResponseStreamReader;
import io.agntcy.slim.bindings.RpcCode;
import io.agntcy.slim.bindings.RpcException;
import io.agntcy.slim.bindings.Server;
import io.agntcy.slim.bindings.StreamMessage;
import io.agntcy.slim.bindings.UnaryStreamHandler;
import io.agntcy.slim.bindings.UnaryUnaryHandler;
import io.agntcy.slim.bindings.StreamUnaryHandler;
import io.agntcy.slim.bindings.StreamStreamHandler;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.Parser;

import java.time.Duration;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import java.util.function.Function;

public final class TestSlimrpc {
    private TestSlimrpc() {}

    public static final String SERVICE_NAME = "example_service.Test";

    public interface TestClient {
        CompletableFuture<ExampleResponse> ExampleUnaryUnary(ExampleRequest request, Duration timeout, Map<String, String> metadata);
        CompletableFuture<ResponseStreamReader> ExampleUnaryStream(ExampleRequest request, Duration timeout, Map<String, String> metadata);
        ClientRequestStream<ExampleRequest, ExampleResponse> ExampleStreamUnary(Duration timeout, Map<String, String> metadata);
        ClientBidiStream<ExampleRequest> ExampleStreamStream(Duration timeout, Map<String, String> metadata);

    }

    public interface TestClientSync {
        ExampleResponse ExampleUnaryUnary(ExampleRequest request, Duration timeout, Map<String, String> metadata) throws RpcException;
        ResponseStreamReader ExampleUnaryStream(ExampleRequest request, Duration timeout, Map<String, String> metadata) throws RpcException;
        ClientRequestStreamSync<ExampleRequest, ExampleResponse> ExampleStreamUnary(Duration timeout, Map<String, String> metadata) throws RpcException;
        ClientBidiStreamSync<ExampleRequest> ExampleStreamStream(Duration timeout, Map<String, String> metadata) throws RpcException;

    }

    public static final class TestClientImpl implements TestClient {
        private final Channel channel;

        public TestClientImpl(Channel channel) {
            this.channel = channel;
        }

        @Override
        public CompletableFuture<ExampleResponse> ExampleUnaryUnary(ExampleRequest request, Duration timeout, Map<String, String> metadata) {
            return channel.callUnaryAsync(
                    SERVICE_NAME,
                    "ExampleUnaryUnary",
                    request.toByteArray(),
                    timeout,
                    metadata
            ).thenApply(bytes -> parse(bytes, ExampleResponse.parser()));
        }

        @Override
        public CompletableFuture<ResponseStreamReader> ExampleUnaryStream(ExampleRequest request, Duration timeout, Map<String, String> metadata) {
            return channel.callUnaryStreamAsync(
                    SERVICE_NAME,
                    "ExampleUnaryStream",
                    request.toByteArray(),
                    timeout,
                    metadata
            );
        }

        @Override
        public ClientRequestStream<ExampleRequest, ExampleResponse> ExampleStreamUnary(Duration timeout, Map<String, String> metadata) {
            RequestStreamWriter writer = channel.callStreamUnary(
                    SERVICE_NAME,
                    "ExampleStreamUnary",
                    timeout,
                    metadata
            );
            return new ClientRequestStream<>(writer, ExampleRequest::toByteArray, bytes -> parse(bytes, ExampleResponse.parser()));
        }

        @Override
        public ClientBidiStream<ExampleRequest> ExampleStreamStream(Duration timeout, Map<String, String> metadata) {
            BidiStreamHandler handler = channel.callStreamStream(
                    SERVICE_NAME,
                    "ExampleStreamStream",
                    timeout,
                    metadata
            );
            return new ClientBidiStream<>(handler, ExampleRequest::toByteArray);
        }


    }

    public static final class TestClientSyncImpl implements TestClientSync {
        private final Channel channel;

        public TestClientSyncImpl(Channel channel) {
            this.channel = channel;
        }

        @Override
        public ExampleResponse ExampleUnaryUnary(ExampleRequest request, Duration timeout, Map<String, String> metadata) throws RpcException {
            byte[] bytes = channel.callUnary(
                SERVICE_NAME,
                "ExampleUnaryUnary",
                request.toByteArray(),
                timeout,
                metadata
            );
            return parse(bytes, ExampleResponse.parser());
        }

        @Override
        public ResponseStreamReader ExampleUnaryStream(ExampleRequest request, Duration timeout, Map<String, String> metadata) throws RpcException {
            return channel.callUnaryStream(
                SERVICE_NAME,
                "ExampleUnaryStream",
                request.toByteArray(),
                timeout,
                metadata
            );
        }

        @Override
        public ClientRequestStreamSync<ExampleRequest, ExampleResponse> ExampleStreamUnary(Duration timeout, Map<String, String> metadata) throws RpcException {
            RequestStreamWriter writer = channel.callStreamUnary(
                    SERVICE_NAME,
                    "ExampleStreamUnary",
                    timeout,
                    metadata
            );
            return new ClientRequestStreamSync<>(writer, ExampleRequest::toByteArray, bytes -> parse(bytes, ExampleResponse.parser()));
        }

        @Override
        public ClientBidiStreamSync<ExampleRequest> ExampleStreamStream(Duration timeout, Map<String, String> metadata) throws RpcException {
            BidiStreamHandler handler = channel.callStreamStream(
                    SERVICE_NAME,
                    "ExampleStreamStream",
                    timeout,
                    metadata
            );
            return new ClientBidiStreamSync<>(handler, ExampleRequest::toByteArray);
        }


    }

    public interface TestServer {
        CompletableFuture<ExampleResponse> ExampleUnaryUnary(ExampleRequest request, Context context);
        CompletableFuture<Void> ExampleUnaryStream(ExampleRequest request, Context context, ResponseSink sink);
        CompletableFuture<ExampleResponse> ExampleStreamUnary(RequestStream stream, Context context);
        CompletableFuture<Void> ExampleStreamStream(RequestStream stream, Context context, ResponseSink sink);

    }

    public abstract static class UnimplementedTestServer implements TestServer {
        @Override
        public CompletableFuture<ExampleResponse> ExampleUnaryUnary(ExampleRequest request, Context context) {
            return CompletableFuture.failedFuture(new UnsupportedOperationException("Method ExampleUnaryUnary not implemented"));
        }

        @Override
        public CompletableFuture<Void> ExampleUnaryStream(ExampleRequest request, Context context, ResponseSink sink) {
            return CompletableFuture.failedFuture(new UnsupportedOperationException("Method ExampleUnaryStream not implemented"));
        }

        @Override
        public CompletableFuture<ExampleResponse> ExampleStreamUnary(RequestStream stream, Context context) {
            return CompletableFuture.failedFuture(new UnsupportedOperationException("Method ExampleStreamUnary not implemented"));
        }

        @Override
        public CompletableFuture<Void> ExampleStreamStream(RequestStream stream, Context context, ResponseSink sink) {
            return CompletableFuture.failedFuture(new UnsupportedOperationException("Method ExampleStreamStream not implemented"));
        }


    }

    public static void registerTestServer(Server server, TestServer impl) {
        server.registerUnaryUnary(SERVICE_NAME, "ExampleUnaryUnary", new Test_ExampleUnaryUnary_Handler(impl));
        server.registerUnaryStream(SERVICE_NAME, "ExampleUnaryStream", new Test_ExampleUnaryStream_Handler(impl));
        server.registerStreamUnary(SERVICE_NAME, "ExampleStreamUnary", new Test_ExampleStreamUnary_Handler(impl));
        server.registerStreamStream(SERVICE_NAME, "ExampleStreamStream", new Test_ExampleStreamStream_Handler(impl));
    }

    private static final class Test_ExampleUnaryUnary_Handler implements UnaryUnaryHandler {
        private final TestServer impl;

        private Test_ExampleUnaryUnary_Handler(TestServer impl) {
            this.impl = impl;
        }

        @Override
        public CompletableFuture<byte[]> handle(byte[] request, Context context) {
            try {
                ExampleRequest parsed = parse(request, ExampleRequest.parser());
                return impl.ExampleUnaryUnary(parsed, context)
                        .thenApply(resp -> resp.toByteArray());
            } catch (Exception e) {
                return CompletableFuture.failedFuture(e);
            }
        }
    }

    private static final class Test_ExampleUnaryStream_Handler implements UnaryStreamHandler {
        private final TestServer impl;

        private Test_ExampleUnaryStream_Handler(TestServer impl) {
            this.impl = impl;
        }

        @Override
        public CompletableFuture<Void> handle(byte[] request, Context context, ResponseSink sink) {
            try {
                ExampleRequest parsed = parse(request, ExampleRequest.parser());
                return impl.ExampleUnaryStream(parsed, context, sink)
                        .handle((ignored, error) -> {
                            if (error != null) {
                                RpcException rpcErr = toRpcException(error, RpcCode.INTERNAL);
                                return (java.util.concurrent.CompletionStage<Void>) sink.sendErrorAsync(rpcErr)
                                    .thenCompose(v -> CompletableFuture.<Void>failedFuture(rpcErr));
                            }
                            return (java.util.concurrent.CompletionStage<Void>) sink.closeAsync();
                        })
                        .thenCompose((java.util.concurrent.CompletionStage<Void> stage) -> stage);
            } catch (Exception e) {
                RpcException rpcErr = new RpcException.Rpc(
                        RpcCode.INVALID_ARGUMENT,
                        e.getMessage() == null ? "invalid request" : e.getMessage(),
                        null
                );
                return sink.sendErrorAsync(rpcErr)
                    .thenCompose(v -> CompletableFuture.<Void>failedFuture(rpcErr));
            }
        }
    }

    private static final class Test_ExampleStreamUnary_Handler implements StreamUnaryHandler {
        private final TestServer impl;

        private Test_ExampleStreamUnary_Handler(TestServer impl) {
            this.impl = impl;
        }

        @Override
        public CompletableFuture<byte[]> handle(RequestStream stream, Context context) {
            return impl.ExampleStreamUnary(stream, context)
                    .handle((resp, error) -> {
                        if (error != null) {
                            return (java.util.concurrent.CompletionStage<byte[]>) CompletableFuture.<byte[]>failedFuture(
                                toRpcException(error, RpcCode.INTERNAL)
                            );
                        }
                        return (java.util.concurrent.CompletionStage<byte[]>) CompletableFuture.completedFuture(
                                resp.toByteArray()
                        );
                    })
                    .thenCompose((java.util.concurrent.CompletionStage<byte[]> stage) -> stage);
        }
    }

    private static final class Test_ExampleStreamStream_Handler implements StreamStreamHandler {
        private final TestServer impl;

        private Test_ExampleStreamStream_Handler(TestServer impl) {
            this.impl = impl;
        }

        @Override
        public CompletableFuture<Void> handle(RequestStream stream, Context context, ResponseSink sink) {
            return impl.ExampleStreamStream(stream, context, sink)
                    .handle((ignored, error) -> {
                        if (error != null) {
                            RpcException rpcErr = toRpcException(error, RpcCode.INTERNAL);
                            return (java.util.concurrent.CompletionStage<Void>) sink.sendErrorAsync(rpcErr)
                                    .thenCompose(v -> CompletableFuture.<Void>failedFuture(rpcErr));
                        }
                        return (java.util.concurrent.CompletionStage<Void>) sink.closeAsync();
                    })
                    .thenCompose((java.util.concurrent.CompletionStage<Void> stage) -> stage);
        }
    }



    private static <T> T parse(byte[] data, Parser<T> parser) {
        try {
            return parser.parseFrom(data);
        } catch (InvalidProtocolBufferException e) {
            throw new CompletionException(e);
        }
    }

    private static RpcException toRpcException(Throwable error, RpcCode defaultCode) {
        Throwable unwrapped = unwrap(error);
        if (unwrapped instanceof RpcException rpc) {
            return rpc;
        }
        String message = unwrapped.getMessage();
        if (message == null || message.isBlank()) {
            message = unwrapped.toString();
        }
        return new RpcException.Rpc(defaultCode, message, null);
    }

    private static Throwable unwrap(Throwable error) {
        if (error instanceof CompletionException ce && ce.getCause() != null) {
            return ce.getCause();
        }
        return error;
    }

    public static final class ClientRequestStream<ReqT, ResT> {
        private final RequestStreamWriter inner;
        private final Function<ReqT, byte[]> serializer;
        private final Function<byte[], ResT> parser;

        public ClientRequestStream(RequestStreamWriter inner, Function<ReqT, byte[]> serializer, Function<byte[], ResT> parser) {
            this.inner = inner;
            this.serializer = serializer;
            this.parser = parser;
        }

        public CompletableFuture<Void> sendAsync(ReqT request) {
            return inner.sendAsync(serializer.apply(request));
        }

        public CompletableFuture<ResT> finalizeStreamAsync() {
            return inner.finalizeStreamAsync().thenApply(parser);
        }
    }

    public static final class ClientBidiStream<ReqT> {
        private final BidiStreamHandler inner;
        private final Function<ReqT, byte[]> serializer;

        public ClientBidiStream(BidiStreamHandler inner, Function<ReqT, byte[]> serializer) {
            this.inner = inner;
            this.serializer = serializer;
        }

        public CompletableFuture<Void> sendAsync(ReqT request) {
            return inner.sendAsync(serializer.apply(request));
        }

        public CompletableFuture<Void> closeSendAsync() {
            return inner.closeSendAsync();
        }

        public CompletableFuture<StreamMessage> recvAsync() {
            return inner.recvAsync();
        }
    }

    public static final class ClientRequestStreamSync<ReqT, ResT> {
        private final RequestStreamWriter inner;
        private final Function<ReqT, byte[]> serializer;
        private final Function<byte[], ResT> parser;

        public ClientRequestStreamSync(RequestStreamWriter inner, Function<ReqT, byte[]> serializer, Function<byte[], ResT> parser) {
            this.inner = inner;
            this.serializer = serializer;
            this.parser = parser;
        }

        public void send(ReqT request) throws RpcException {
            inner.send(serializer.apply(request));
        }

        public ResT finalizeStream() throws RpcException {
            return parser.apply(inner.finalizeStream());
        }
    }

    public static final class ClientBidiStreamSync<ReqT> {
        private final BidiStreamHandler inner;
        private final Function<ReqT, byte[]> serializer;

        public ClientBidiStreamSync(BidiStreamHandler inner, Function<ReqT, byte[]> serializer) {
            this.inner = inner;
            this.serializer = serializer;
        }

        public void send(ReqT request) throws RpcException {
            inner.send(serializer.apply(request));
        }

        public void closeSend() throws RpcException {
            inner.closeSend();
        }

        public StreamMessage recv() {
            return inner.recv();
        }
    }

    public static final class ClientResponseStreamSync<RespT> {
        private final ResponseStreamReader inner;
        private final Function<byte[], RespT> parser;

        public ClientResponseStreamSync(ResponseStreamReader inner, Function<byte[], RespT> parser) {
            this.inner = inner;
            this.parser = parser;
        }

        public RespT recv() throws RpcException {
            StreamMessage message = inner.next();
            if (message instanceof StreamMessage.End) {
                return null;
            }
            if (message instanceof StreamMessage.Error err) {
                throw err.v1();
            }
            if (message instanceof StreamMessage.Data data) {
                return parser.apply(data.v1());
            }
            throw new IllegalStateException("unknown stream message type");
        }
    }

    public static <RespT> ClientResponseStreamSync<RespT> newClientResponseStreamSync(
            ResponseStreamReader reader,
            Function<byte[], RespT> parser
    ) {
        return new ClientResponseStreamSync<>(reader, parser);
    }

    public interface ServerResponseStreamSync<ReqT> {
        ReqT recv() throws RpcException;
    }

    public interface ServerRequestStreamSync<RespT> {
        void send(RespT response) throws RpcException;
    }

    public interface ServerBidiStreamSync<ReqT, RespT> {
        ReqT recv() throws RpcException;
        void send(RespT response) throws RpcException;
    }

    public static <ReqT> ServerResponseStreamSync<ReqT> newServerResponseStreamSync(
            RequestStream stream,
            Function<byte[], ReqT> parser
    ) {
        return new ServerResponseStreamSyncImpl<>(stream, parser);
    }

    public static <RespT> ServerRequestStreamSync<RespT> newServerRequestStreamSync(
            ResponseSink sink,
            Function<RespT, byte[]> serializer
    ) {
        return new ServerRequestStreamSyncImpl<>(sink, serializer);
    }

    public static <ReqT, RespT> ServerBidiStreamSync<ReqT, RespT> newServerBidiStreamSync(
            RequestStream stream,
            ResponseSink sink,
            Function<byte[], ReqT> parser,
            Function<RespT, byte[]> serializer
    ) {
        return new ServerBidiStreamSyncImpl<>(stream, sink, parser, serializer);
    }

    private static final class ServerResponseStreamSyncImpl<ReqT> implements ServerResponseStreamSync<ReqT> {
        private final RequestStream inner;
        private final Function<byte[], ReqT> parser;

        private ServerResponseStreamSyncImpl(RequestStream inner, Function<byte[], ReqT> parser) {
            this.inner = inner;
            this.parser = parser;
        }

        @Override
        public ReqT recv() throws RpcException {
            StreamMessage message = inner.next();
            if (message instanceof StreamMessage.End) {
                return null;
            }
            if (message instanceof StreamMessage.Error err) {
                throw err.v1();
            }
            if (message instanceof StreamMessage.Data data) {
                return parser.apply(data.v1());
            }
            throw new IllegalStateException("unknown stream message type");
        }
    }

    private static final class ServerRequestStreamSyncImpl<RespT> implements ServerRequestStreamSync<RespT> {
        private final ResponseSink inner;
        private final Function<RespT, byte[]> serializer;

        private ServerRequestStreamSyncImpl(ResponseSink inner, Function<RespT, byte[]> serializer) {
            this.inner = inner;
            this.serializer = serializer;
        }

        @Override
        public void send(RespT response) throws RpcException {
            inner.send(serializer.apply(response));
        }
    }

    private static final class ServerBidiStreamSyncImpl<ReqT, RespT> implements ServerBidiStreamSync<ReqT, RespT> {
        private final RequestStream stream;
        private final ResponseSink sink;
        private final Function<byte[], ReqT> parser;
        private final Function<RespT, byte[]> serializer;

        private ServerBidiStreamSyncImpl(
                RequestStream stream,
                ResponseSink sink,
                Function<byte[], ReqT> parser,
                Function<RespT, byte[]> serializer
        ) {
            this.stream = stream;
            this.sink = sink;
            this.parser = parser;
            this.serializer = serializer;
        }

        @Override
        public ReqT recv() throws RpcException {
            StreamMessage message = stream.next();
            if (message instanceof StreamMessage.End) {
                return null;
            }
            if (message instanceof StreamMessage.Error err) {
                throw err.v1();
            }
            if (message instanceof StreamMessage.Data data) {
                return parser.apply(data.v1());
            }
            throw new IllegalStateException("unknown stream message type");
        }

        @Override
        public void send(RespT response) throws RpcException {
            sink.send(serializer.apply(response));
        }
    }
}

