# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

includes:
  adapter:
    taskfile: ../rust/Taskfile.yaml
    internal: false
  rust:
    taskfile: ../../../tasks/rust.yaml
    internal: true
  example:kotlin:
    taskfile: ./examples/kotlin/Taskfile.yaml
    internal: false

vars:
  BINDINGS_DIR: "{{.TASKFILE_DIR}}/../rust"
  PROFILE: '{{.PROFILE | default "release"}}'
  CURRENT_TARGET:
    sh: 'rustc -vV | sed -n "s|host: ||p"'
  TARGET: "{{.TARGET | default .CURRENT_TARGET}}"
  SERVICE_TARGET: "{{.TASKFILE_DIR}}/../../target/{{.TARGET}}/{{.PROFILE}}"
  LIB_NAME: slim_bindings
  _DEFAULT_LIB_PATH:
    sh: |
      # Detect OS to determine library extension
      OS=$(uname -s 2>/dev/null | tr '[:upper:]' '[:lower:]')
      case "$OS" in
        mingw*|msys*|cygwin*)
          echo "{{.SERVICE_TARGET}}/{{.LIB_NAME}}.lib"
          ;;
        darwin*)
          echo "{{.SERVICE_TARGET}}/lib{{.LIB_NAME}}.dylib"
          ;;
        *)
          echo "{{.SERVICE_TARGET}}/lib{{.LIB_NAME}}.so"
          ;;
      esac
  LIB_PATH: "{{.LIB_PATH | default ._DEFAULT_LIB_PATH}}"

tasks:
  default:
    cmds:
      - task -l

  install-uniffi-bindgen:
    desc: Install uniffi-bindgen CLI tool
    status:
      - which uniffi-bindgen
    cmds:
      - echo "ðŸ“¦ Installing uniffi-bindgen..."
      - cargo install uniffi-bindgen --git https://github.com/mozilla/uniffi-rs.git --tag v0.28.3
      - echo "âœ… uniffi-bindgen installed"

  generate:
    desc: Generate Kotlin bindings from compiled Rust library
    deps:
      - task: adapter:bindings:build:all
        vars:
          PROFILE: release
      - install-uniffi-bindgen
    cmds:
      - echo "ðŸ”§ Generating Kotlin bindings from compiled library..."
      - |
        uniffi-bindgen generate \
          --library '{{.LIB_PATH}}' \
          --language kotlin \
          --out-dir generated
      - task: copy-library
      - task: patch-bindings
      - echo "âœ… Bindings generated in generated/"

  patch-bindings:
    desc: Patch generated bindings to fix Kotlin compatibility issues
    internal: true
    cmds:
      - ./patch-bindings.sh

  copy-library:
    desc: Copy native library to generated directory for JNA loading
    internal: true
    cmds:
      - echo "ðŸ“¦ Copying native library..."
      - |
        mkdir -p generated/jniLibs
        LIB_DIR=$(dirname "{{.LIB_PATH}}")
        
        # Detect OS and architecture
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        
        case "$OS" in
          darwin*)
            OS_DIR="darwin"
            LIB_EXT="dylib"
            ;;
          linux*)
            OS_DIR="linux"
            LIB_EXT="so"
            ;;
          mingw*|msys*|cygwin*)
            OS_DIR="win32"
            LIB_EXT="dll"
            ;;
        esac
        
        case "$ARCH" in
          x86_64|amd64) ARCH_DIR="x86-64" ;;
          arm64|aarch64) ARCH_DIR="aarch64" ;;
        esac
        
        DEST_DIR="generated/jniLibs/${OS_DIR}-${ARCH_DIR}"
        mkdir -p "$DEST_DIR"
        
        if [ -f "{{.LIB_PATH}}" ]; then
          cp "{{.LIB_PATH}}" "$DEST_DIR/"
          echo "âœ… Copied library to $DEST_DIR/"
        else
          echo "âš ï¸  Library not found: {{.LIB_PATH}}"
          exit 1
        fi

  build:
    desc: Build Kotlin code and create executable JARs
    deps:
      - generate
    cmds:
      - echo "ðŸ”¨ Building Kotlin bindings..."
      - ./gradlew build
      - echo "âœ… Build complete"

  clean:
    desc: Clean build artifacts and generated code
    cmds:
      - echo "ðŸ§¹ Cleaning build artifacts..."
      - rm -rf generated/
      - rm -rf build/
      - rm -rf .gradle/
      - ./gradlew clean 2>/dev/null || true
      - echo "âœ… Clean complete"
