# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

tracing:
  log_level: debug
  display_thread_names: true
  display_thread_ids: true

runtime:
  n_cores: 0
  thread_name: "slim-data-plane"
  drain_timeout: 10s

services:
  slim/0:
    dataplane:
      clients:
        - endpoint: "https://localhost:46357"
          tls:
            ca_source:
              type: file
              path: "./config/crypto/server-ca-cert.pem"
          auth:
            type: jwt
            claims:
              audiences: ["slim"]
              issuer: "slim"
              subject: "slim"
            duration: 1h
            key:
              type: encoding
              algorithm: "RS256"
              format: pem
              key:
                file: "./config/crypto/jwt/rsa.pem"
