# SPIFFE trust bundle from the upstream (root) SPIRE server.
# Retrieve with: kubectl -n spire-system get configmap spire-bundle-upstream -o jsonpath='{.data.bundle\.spiffe}'

tags:
  nestedChildFull: true

global:
  spire:
    trustDomain: slim.dev.outshift.ai
    upstreamSpireAddress: external.spire.slim.dev.outshift.ai
    clusterName: gls-cluster-0
    tools:
      kubectl:
        tag: "v1.28.0"

upstreamBundle: '{"keys":[{"use":"x509-svid","kty":"RSA","n":"qiJf-56r0n4eHA_5DfNAnv5o7-4csD9K97Su7oFURDyx9Vwe0_35exhMBiS3AFMvvVL2P6JP5dogNcUmi-Nyw1K8jhJu7ZOAwrKdhNlB7qyExlFdKoNOWNjHYTr9jqk4VRLdqOs3Nd2FNb2h0-S97qTqt9_AgGqiFcMxrFUWQR6rjcbc5H8h1dF0-bDeTHQ17BoIwi5mvmN2p7K5pintst3pyoLry5uf3OPw0L8d5NXpvqMDuzShvPMd0h5L7L-aLJzqsinCOufOUrOWTAOwtA2HTzrQmNGqyqW2j5Luk0Hjs1GkxV24JCIbIKgJTRK6N01K9czvV3eSR9z5Rot7rw","e":"AQAB","x5c":["MIIDxjCCAq6gAwIBAgIQOM79nuwIk6mi6zY3NptMvzANBgkqhkiG9w0BAQsFADBoMQ0wCwYDVQQGEwRBUlBBMRAwDgYDVQQKEwdFeGFtcGxlMRQwEgYDVQQDEwtleGFtcGxlLm9yZzEvMC0GA1UEBRMmNzU1MTE1MjQ5NTc1NDE2OTU1NDE5Nzk2OTYwNjU2ODMzNDQ1NzUwHhcNMjYwNDAyMTUxNTUxWhcNMjYwNDAzMTUxNjAxWjBoMQ0wCwYDVQQGEwRBUlBBMRAwDgYDVQQKEwdFeGFtcGxlMRQwEgYDVQQDEwtleGFtcGxlLm9yZzEvMC0GA1UEBRMmNzU1MTE1MjQ5NTc1NDE2OTU1NDE5Nzk2OTYwNjU2ODMzNDQ1NzUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCqIl/7nqvSfh4cD/kN80Ce/mjv7hywP0r3tK7ugVREPLH1XB7T/fl7GEwGJLcAUy+9UvY/ok/l2iA1xSaL43LDUryOEm7tk4DCsp2E2UHurITGUV0qg05Y2MdhOv2OqThVEt2o6zc13YU1vaHT5L3upOq338CAaqIVwzGsVRZBHquNxtzkfyHV0XT5sN5MdDXsGgjCLma+Y3ansrmmKe2y3enKguvLm5/c4/DQvx3k1em+owO7NKG88x3SHkvsv5osnOqyKcI6585Ss5ZMA7C0DYdPOtCY0arKpbaPku6TQeOzUaTFXbgkIhsgqAlNEro3TUr1zO9Xd5JH3PlGi3uvAgMBAAGjbDBqMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTW9Dp/DCws7GQPA1JaksJHIzHTnjAoBgNVHREEITAfhh1zcGlmZmU6Ly9zbGltLmRldi5vdXRzaGlmdC5haTANBgkqhkiG9w0BAQsFAAOCAQEAeeMf+KLK1F4nmVlBgjwj4WNawFp6HLq2d1jiKo3fa4PhPtfshuzK/IOIpO+f9srTVc0f8NmAQbI80v9Y9ibH+IMPiODEJ/3KGMLowa4T8QUaE2FlIm2nRlRofJ3nZHYifMDtLBhl5G6M/lnayCA/YeOJRBQd6XSxbDCYSsa1URpHZQ2ZswT7js6MBhbrx2B6d44a7X/aSzTNa/hqftZ32k+Bw6fNjdkGv0srA2h1dfXhMrpB8ErUPMzDsirDBzqYNUt81SOFyE4Gb0U7Mm1QK9mbnmGOI2g3L53HpRKh1JkUqKJ6Wpi7uMLEkoSsBINBLpVWiSAEBxhFV2h0Os0Arw=="]},{"use":"jwt-svid","kty":"RSA","kid":"Hafi7JfenmsB2qkjbOdHQBecbOSEgPyE","n":"s3GSznV2sNuMOoyT8mKyWhAxlQ0y2Qxb3QH4mZhqol1UUhIN_VFIMN8jixzcWQ6x9c5AbVSfpm7IiOWAi6kskdDtbve2x1Fsp37va66NGVuHE3nLk7fSXkFMd9w7WAyQQdv3L6fEjkDNdk_9s1hBcMqSgPjGI6-DCSWmKynv6HS3s2ePpmeV4pGiUvvZKT2FGtogkFlnc4hMUjT-SSRWHZLgN-C8fCwdWv7VeAx8XoK1AkFDREWzqyrzKU1UAowAu_EBw9RIWgAD8l51MvlOFFN9e1RV66fYP_pl3sAxzCD1LUo50t-qemTGUgjrgyUJvdT4JQDiMM8oJP0AFGuC-w","e":"AQAB"},{"use":"jwt-svid","kty":"RSA","kid":"Ue2aOsnPqOV76pXJvxrLooNaewTlSe0g","n":"7kQdjWT3ufOU9DM-57VGLYr0XZmATs7qry-bYihgQ7eV6vwLrniHjfu7TcuF8yfGcHw1J8oHM6XMxu2RGi6nAO7C1g_lF-UzoKLJVB2kRDkVjdWKuLOJPqwonp0ZdVHTOBhlsYWF3NmO9mlRKU0PKLBTXtFlGTkfp811zhAD1tfQ7Y1vfvhRuClN7_-zpTL1sCvlsF1B3D3J53Go72k22x8v_JHx9nyvn_OFi2uSKNERvtoEOisV6FULH2q5xIAcXdfB_v5uDZ0QCNb3POWB_hTFRExu16KrqfS0H9ewyFvW5qq_WsW1m5l2A6yhWYY1bO8iNkOpMi0RsiMBxlyMBQ","e":"AQAB"},{"use":"jwt-svid","kty":"RSA","kid":"4rmvf6ka8eXJ8nar9yPvaMvvg70LNWjY","n":"1aDBVHQUDX9WLddSnR-PfXCYNe_QQZ3YuutdTje0dFnVjo-V3gzv5EUSTipIrE0PKqRtmEv6Kqi2vK_XCkvco1kMIEBljIM44WPW2JAEZpPGaJ3UDE8kUfnUuTxTJT6WgYHqE3_JUrffbwT-j8S4PDvbRWG49ZaEld0Zts54-5JmvPpkYXNBLJQLsc6GI0h8_NSDBVGZzbwRfQbZ6XghxcBC3qaetMBGFqTOH4O5UtczHtNH3eI6-uIJdjWK_dhf1YDB_9kRu8lLemGS6BYbBQfflP8wy_9f4PBtYuZaA8VH6SQMOyRAs0XORpbjyvkWmfTG8gbR1zwSLxloe5B6vQ","e":"AQAB"},{"use":"jwt-svid","kty":"RSA","kid":"luXKrcY41Mj0NVA86oEGBcdWkzQnZQR3","n":"3BfJ_dKEeig_K-JvOFzc746zSXU8IsTeJWRi9iSxqFGP1f7Hva8AujmEpm63iklKlK26lQbORlHio3vIRM5pxPQiSRzOX3WsJ9QIzG2AkxEY81mVG4RjJb_Cupmbr8R_tnPV9_Xf_xhMxrv6DCXqhrqZ1EbDtVo7FT1UGxoFmZ5tPk4K0qoz5h9FXD37_j3VQjaBCrdnYHSCFYQCRaGvzEkqJ1ODE3b-G04GYh1kHkEjvQaczYdRI1SJWVWTwpw8_gBsnLPX5DI09KLQx-hD5FQAe75za1OAmyX79QGs8YS_arWzTU_QapTnTgW28kmXJ61gVZwJbC5-viuSP7w2KQ","e":"AQAB"}],"spiffe_sequence":4}'

external-secrets-operator:
  operator:
    enabled: false

  externalSecrets:
    - name: 'join-token'
      secretStoreRef:
        name: "vault-espresso-backend"
        kind: "ClusterSecretStore"
      target:
        name: "join-token"
        template:
          engineVersion: v2
          data:
            join_token: '{{ index . "join-token" }}'
      data:
        - secretKey: join-token
          remoteRef:
              key: "gls/spire"
              property: join-token

spire-nested:
  upstream-spiffe-csi-driver:
    kubeletPath: /var/snap/microk8s/common/var/lib/kubelet

  downstream-spiffe-csi-driver:
    kubeletPath: /var/snap/microk8s/common/var/lib/kubelet

  external-root-spire-server-full:
    controllerManager:
      className: spire-spire

  # This is the spire server local application in the cluster will talk to.
  # It receives its CA from the upstream server.
  internal-spire-server:
    nodeSelector:
      spire-role: bridge
    persistence:
      enabled: true
      storageClass: ceph-block
      size: 8Gi
    spiffe-csi-driver:
      kubeletPath: /var/snap/microk8s/common/var/lib/kubelet
    controllerManager:
      className: spire-spire
    env:
      - name: HTTP_PROXY
        value: http://proxy-wsa.esl.cisco.com:80
      - name: HTTPS_PROXY
        value: http://proxy-wsa.esl.cisco.com:80
      - name: http_proxy
        value: http://proxy-wsa.esl.cisco.com:80
      - name: https_proxy
        value: http://proxy-wsa.esl.cisco.com:80
      - name: NO_PROXY
        value: localhost,127.0.0.1,svc.cluster.local,10.0.0.0/8,192.168.0.0/16,172.16.0.0/16,172.18.0.0/16,kubernetes.default.svc,spire-server,spire-agent,spiffe-csi-driver,spire-controller-manager
      - name: no_proxy
        value: localhost,127.0.0.1,svc.cluster.local,10.0.0.0/8,192.168.0.0/16,172.16.0.0/16,172.18.0.0/16,kubernetes.default.svc,spire-server,spire-agent,spiffe-csi-driver,spire-controller-manager

  # This is the agent used to attest the child spire server against the upstream server
  upstream-spire-agent:
    nodeAttestor:
      k8sPSAT:
        enabled: false
    unsupportedBuiltInPlugins:
      nodeAttestor:
        join_token:
          plugin_data: {}
    extraVolumes:
      - name: join-token-file
        secret:
          secretName: join-token
    extraVolumeMounts:
      - name: join-token-file
        mountPath: /run/spire/join-token
        readOnly: true
    nodeSelector:
      spire-role: bridge
    spiffe-csi-driver:
      kubeletPath: /var/snap/microk8s/common/var/lib/kubelet
    extraEnvVars:
      - name: HTTP_PROXY
        value: http://proxy-wsa.esl.cisco.com:80
      - name: HTTPS_PROXY
        value: http://proxy-wsa.esl.cisco.com:80
      - name: http_proxy
        value: http://proxy-wsa.esl.cisco.com:80
      - name: https_proxy
        value: http://proxy-wsa.esl.cisco.com:80
      - name: NO_PROXY
        value: localhost,127.0.0.1,svc.cluster.local,10.0.0.0/8,192.168.0.0/16,172.16.0.0/16,172.18.0.0/16,kubernetes.default.svc,spire-server,spire-agent,spiffe-csi-driver,spire-controller-manager
      - name: no_proxy
        value: localhost,127.0.0.1,svc.cluster.local,10.0.0.0/8,192.168.0.0/16,172.16.0.0/16,172.18.0.0/16,kubernetes.default.svc,spire-server,spire-agent,spiffe-csi-driver,spire-controller-manager

  # This is the agent used by workloads in the cluster to talk to the local spire server
  downstream-spire-agent-full:
    spiffe-csi-driver:
      kubeletPath: /var/snap/microk8s/common/var/lib/kubelet
    extraEnvVars:
      - name: HTTP_PROXY
        value: http://proxy-wsa.esl.cisco.com:80
      - name: HTTPS_PROXY
        value: http://proxy-wsa.esl.cisco.com:80
      - name: http_proxy
        value: http://proxy-wsa.esl.cisco.com:80
      - name: https_proxy
        value: http://proxy-wsa.esl.cisco.com:80
      - name: NO_PROXY
        value: localhost,127.0.0.1,svc.cluster.local,10.0.0.0/8,192.168.0.0/16,172.16.0.0/16,172.18.0.0/16,kubernetes.default.svc,spire-server,spire-agent,spiffe-csi-driver,spire-controller-manager
      - name: no_proxy
        value: localhost,127.0.0.1,svc.cluster.local,10.0.0.0/8,192.168.0.0/16,172.16.0.0/16,172.18.0.0/16,kubernetes.default.svc,spire-server,spire-agent,spiffe-csi-driver,spire-controller-manager
