# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

vars:
  UV_ARGS: '{{.UV_ARGS | default ""}}'

tasks:
  fix-lint:
    desc: "Automatically fix code style and formatting issues using ruff and mypy"
    cmds:
      - uv run {{.UV_ARGS}} ruff format
      - uv run {{.UV_ARGS}} ruff check --fix

  lint:
    desc: "Check code style, formatting, and type hints without making changes"
    cmds:
      - uv run {{.UV_ARGS}} ruff check
      - uv run {{.UV_ARGS}} ruff format --check
      - uv run {{.UV_ARGS}} mypy --ignore-missing-imports --explicit-package-bases .

  test:
    desc: "Run pytest test suite with optional test path specification"
    cmds:
      - uv run {{.UV_ARGS}} pytest -s {{.TESTS}}

  packaging:
    desc: "Build Python package and generate distribution artifacts"
    cmds:
      - uv build {{.UV_ARGS}}
