apiVersion: v1
kind: Pod
metadata:
  name: bob
spec:
  containers:
  - args:
    - ff
    - --message
    - hello
    - --iterations
    - "10"
    - --local
    - org/ns/bob
    - --remote
    - org/ns/alice
    - --shared-secret
    - secret123
    - --slim
    - '{"endpoint":"http://slim.slim.svc.cluster.local:46357","tls":{"insecure":true}}'
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    image: ghcr.io/agntcy/slim/bindings-examples:latest
    imagePullPolicy: Always
    name: bob
    resources: {}
  serviceAccount: default
  serviceAccountName: default