
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

# taks file for the client applications deployment
tasks:

  sender:deploy:
    desc: Deploy sender client application
    cmds:
      - cmd: |
          echo "Deploying sender client application"
          kubectl apply -f ./sender-pod.yaml

  sender:delete:
    desc: Delete sender client application
    cmds:
      - cmd: |
          echo "Deleting sender client application"
          kubectl delete -f ./sender-pod.yaml

  receiver:deploy:
    desc: Deploy receiver client application
    cmds:
      - cmd: |
          echo "Deploying receiver client application"
          kubectl apply -f ./receiver-pod.yaml

  receiver:delete:
    desc: Delete receiver client application
    cmds:
      - cmd: |
          echo "Deleting receiver client application"
          kubectl delete -f ./receiver-pod.yaml

  spire:sender:deploy:
    desc: Deploy sender application with SPIRE
    cmds:
      - cmd: |
          echo "Deploying sender client application with SPIRE"
          kubectl apply -f with_spire/sender.yaml

  spire:sender:delete:
    desc: Delete sender application with SPIRE
    cmds:
      - cmd: |
          echo "Deleting sender client application with SPIRE"
          kubectl delete -f with_spire/sender.yaml

  spire:receiver:deploy:
    desc: Deploy receiver applications with SPIRE
    cmds:
      - cmd: |
          echo "Deploying receiver client application with SPIRE"
          kubectl apply -f with_spire/receiver.yaml
  
  spire:receiver:delete:
    desc: Delete receiver application with SPIRE
    cmds:
      - cmd: |
          echo "Deleting receiver client application with SPIRE"
          kubectl delete -f with_spire/receiver.yaml