[package]
name = "agntcy-protoc-srpc-plugin"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[[bin]]
name = "protoc-srpc-plugin"
path = "src/bin/main.rs"

[dependencies]
anyhow = { workspace = true }
heck = "0.5.0"
prost = "0.14"
prost-types = "0.14"
