[package]
name = "agntcy-protoc-srpc-plugin"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.98"
bytes.workspace = true
heck = "0.5.0"
prost = "0.14.1"
prost-types = "0.14.1"

[[bin]]
name = "protoc-srpc-plugin"
path = "src/bin/main.rs"
