
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

# This Taskfile includes specific tasks for the naive deployment strategy.

includes:
  templates: 
    taskfile: ../Taskfile.yaml
    dir: ../

  apps: 
    taskfile: ../client_apps/Taskfile.yaml
    dir: ../client_apps

silent: true


tasks:
  default:
    - task templates:slim:check:prerequisites
    - task --list

  slim:controller:deploy:
    desc: Deploy Slim Controller
    cmds:
      - |
        helm upgrade --install slim-control ../../charts/slim-control-plane \
          --namespace {{ .SLIM_NAMESPACE }} \
          --create-namespace \
          --set image.tag="{{ .SLIM_CONTROLLER_IMAGE_TAG }}" \
          --values controller-values.yaml  
          
  slim:deploy:
    desc: Deploy Slim using the StatefulSet deployment strategy

    requires:
      vars: [SLIM_IMAGE_TAG]

    cmds:
      - | 
        helm upgrade --install slim ../../charts/slim \
          --namespace {{ .SLIM_NAMESPACE }} \
          --create-namespace \
          --set slim.image.tag="{{ .SLIM_IMAGE_TAG }}" \
          --values statefulset-values.yaml
