# This file was generated by GoReleaser. DO NOT EDIT.
cask "slimctl" do
  name "slimctl"
  desc "A CLI tool for managing SLIM Devices"
  homepage "https://github.com/lpuskas/slim/tree/main/control-plane/slimctl"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slimctl"

  on_macos do
    on_intel do
      url "https://github.com/lpuskas/slim/releases/download/v#{version}/slimctl_#{version}_darwin_amd64.tar.gz",
        using: :homebrew_curl
      sha256 "483f9c7f3d0a34a019d530fcab245cecac52c1ca87f787fe89770f8e6f88752a"
    end
    on_arm do
      url "https://github.com/lpuskas/slim/releases/download/v#{version}/slimctl_#{version}_darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "b61f4cc40d50339d5c064a82cd86aa8ad3a0155efc410da4381a23c3df0389dc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lpuskas/slim/releases/download/v#{version}/slimctl_#{version}_linux_amd64.tar.gz",
        using: :homebrew_curl
      sha256 "a702cd5c71fe7cf86890bfe979a5547153fa39c5a20ce277ff4329b799774181"
    end
    on_arm do
      url "https://github.com/lpuskas/slim/releases/download/v#{version}/slimctl_#{version}_linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "07eac0557e4d8a48b0a59e3c8c827692016bfe3dc17566aad55dd6a41d7ee192"
    end
  end

  # No zap stanza required
end
