# This file was generated by GoReleaser. DO NOT EDIT.
cask "slimctl" do
  name "slimctl"
  desc "A CLI tool for managing SLIM Devices"
  homepage "https://github.com/agntcy/slim/tree/main/control-plane/slimctl"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slimctl"

  on_macos do
    on_intel do
      url "https://github.com/agntcy/slim/releases/download/v#{version}/slimctl_#{version}_darwin_amd64.tar.gz",
        using: :homebrew_curl
      sha256 "f24de444fb093042447124dfc6a242c32d38b105255e341b0504dca617fd041b"
    end
    on_arm do
      url "https://github.com/agntcy/slim/releases/download/v#{version}/slimctl_#{version}_darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "9c387d6a22bd609d62393ea9e5b89de67c4c0cf2bbe92bb26e99128e25e71745"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agntcy/slim/releases/download/v#{version}/slimctl_#{version}_linux_amd64.tar.gz",
        using: :homebrew_curl
      sha256 "fc4aa7fa07e1f65e47956e1cfad48b50cc11030b6860c2a8bc9d197c12778eb5"
    end
    on_arm do
      url "https://github.com/agntcy/slim/releases/download/v#{version}/slimctl_#{version}_linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "9e1206450268846ad1663252d7baba7db37545a7ab4df93b5c1545283e096cc7"
    end
  end

  # No zap stanza required
end
