# This file was generated by GoReleaser. DO NOT EDIT.
cask "slimctl" do
  name "slimctl"
  desc "A CLI tool for managing SLIM Devices"
  homepage "https://github.com/agntcy/slim/control-plane/slimctl"
  version "slimctl-v0.7.0-SNAPSHOT-35c37ab"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slimctl"

  on_macos do
    on_intel do
      url "https://github.com/agntcy/slim/releases/download/slimctl-v0.7.0/slimctl_#{version}_darwin_amd64.tar.gz",
        using: :homebrew_curl
      sha256 "856ae983e233b6de6409cdc0ce0ad05e451a6ae7b02baf9296dcddc0a0e50584"
    end
    on_arm do
      url "https://github.com/agntcy/slim/releases/download/slimctl-v0.7.0/slimctl_#{version}_darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "d741a515cc430ed33763cbe9e0cd0b32d30e78881f31e56b4e84bfdd9ac06c6c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agntcy/slim/releases/download/slimctl-v0.7.0/slimctl_#{version}_linux_amd64.tar.gz",
        using: :homebrew_curl
      sha256 "2e977139e1589b5d9c80f9cef289e83b22dd2bb390f02d959a21b756650877de"
    end
    on_arm do
      url "https://github.com/agntcy/slim/releases/download/slimctl-v0.7.0/slimctl_#{version}_linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "a197d04034fcaf1c976afa16dbbc05043794ca95fd8006a6114a2ce68f1e2f47"
    end
  end

  postflight do
    system "chmod", "+x", "#{staged_path}/slimctl"
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slimctl"]
    end
  end

  # No zap stanza required
end
