
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

# This Taskfile includes specific tasks for the naive deployment strategy.

includes:
  templates: ../Taskfile.yaml

tasks:

  slim:deploy:
    desc: Deploy Slim using the DaemonSet deployment strategy
    cmds:
      - helm upgrade --install slim ../../charts/slim \
          --namespace slim \
          --create-namespace \
          --values ./deployments/daemonset-values.yaml
