
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

# This Taskfile includes specific tasks for the naive deployment strategy.

includes:
  templates: 
    taskfile: ../Taskfile.yaml
    dir: ../
  
  apps: 
    taskfile: ../client_apps/Taskfile.yaml
    dir: ../client_apps
    internal: true

silent: true

tasks:
  default:
    desc: Check prerequisites and display available tasks
    cmds:
    - task: templates:slim:check:prerequisites
    - task --list

  cluster:up:
    desc: Start a local Kubernetes cluster using Kind
    cmd: kind create cluster --name slim-cluster --config ../slim-cluster.yaml --wait 60s || true

  slim:deploy:
    desc: Deploy Slim using the DaemonSet deployment strategy

    requires:
      vars: [SLIM_IMAGE_TAG]

    cmds:
      - |
        helm upgrade --install slim ../../charts/slim \
          --namespace slim \
          --create-namespace \
          --set slim.image.tag="{{ .SLIM_IMAGE_TAG }}" \
          --values daemonset-values.yaml
  
  controller:deploy:
    desc: Deploy Slim Controller
    cmds:
      - |
        helm upgrade --install slim-control ../../charts/slim-control-plane \
          --namespace {{ .SLIM_NAMESPACE }} \
          --create-namespace \
          --set image.tag="{{ .SLIM_CONTROLLER_IMAGE_TAG }}" \
          --set spire.enabled=false \
          --values controller-values.yaml

  test.sender:deploy:
    desc: Deploy sender application
    vars:
      TEMPLATE: '{{ .TEMPLATE | default "./sender-pod.yaml" }}'  
      NAMESPACE: '{{ .NAMESPACE | default "default" }}'
    cmds:
      - task: apps:k8s:apply
        vars:
          TEMPLATE: '{{ .TEMPLATE }}'
          NAMESPACE: '{{ .NAMESPACE }}'

  test.receiver:deploy:
    desc: Deploy receiver application
    vars:
      TEMPLATE: '{{ .TEMPLATE | default "./receiver-daemonset.yaml" }}'  
      NAMESPACE: '{{ .NAMESPACE | default "default" }}'
    cmds:
      - task: apps:k8s:apply
        vars:
          TEMPLATE: '{{ .TEMPLATE }}'
          NAMESPACE: '{{ .NAMESPACE }}'
            

