
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

# This Taskfile includes specific tasks for the naive deployment strategy.

includes:
  templates: ../Taskfile.yaml

tasks:
  log:strategy:name:
    desc: Display the name of the deployment strategy
    cmds:
      - echo "Naive Deployment Strategy"


  slim:deploy:
    desc: Deploy Slim using the naive deployment strategy
    deps: 
      # - templates:cluster:use-context

    requires:
      vars: [SLIM_IMAGE_TAG]

    cmds:
      - cmd: |
          helm upgrade slim ../../charts/slim \
            --namespace slim \
            --create-namespace \
            --install \
            --set slim.image.tag="{{ .SLIM_IMAGE_TAG }}" \
            --values naive-values.yaml \
  
  slim:show-logs:
    desc: Show logs for Slim components in the naive deployment
    cmds:
      - kubectl logs -l app.kubernetes.io/name=slim -n slim --tail=100 -f