
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

# This Taskfile includes specific tasks for the naive deployment strategy.

includes:
  templates: 
    taskfile: ../Taskfile.yaml
    internal: true

  apps: 
    taskfile: ../client_apps/Taskfile.yaml
    dir: ../client_apps
    internal: true

silent: true

vars:
  STRATEGY: "naive"

tasks:
  default:
    cmds:
    - task: templates:default
  
  cluster:up:
    desc: Start a local Kubernetes cluster using Kind
    cmds:
      - task: templates:cluster:up
  
  cluster:down:
    desc: Delete the local Kubernetes cluster
    cmds:
      - task: templates:cluster:down

  slim:deploy:
    desc: Deploy Slim using the naive deployment strategy

    requires:
      vars: 
        -  SLIM_IMAGE_TAG

    cmds:
      - cmd: |
          helm upgrade slim ../../charts/slim \
            --namespace slim \
            --create-namespace \
            --install \
            --set slim.image.tag="{{ .SLIM_IMAGE_TAG }}" \
            --values naive-values.yaml \


  test.receiver:deploy:
    desc: Deploy receiver application
    cmds:
      - task: apps:k8s:apply
        vars:
          TEMPLATE: '{{ .TEMPLATE | default "./receiver-pod.yaml" }}'  
          NAMESPACE: '{{ .NAMESPACE | default "default" }}'


  test.sender:deploy:
    desc: Deploy sender application
    cmds:
      - task: apps:k8s:apply
        vars:
          TEMPLATE: '{{ .TEMPLATE | default "./sender-pod.yaml" }}'  
          NAMESPACE: '{{ .NAMESPACE | default "default" }}'

  
  slim:show-logs:
    desc: Show logs for Slim components in the naive deployment
    cmds:
      - kubectl logs -l app.kubernetes.io/name=slim -n slim --tail=100 -f