# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

tracing:
  log_level: info
  display_thread_names: true
  display_thread_ids: true

runtime:
  n_cores: 0
  thread_name: "slim-data-plane"
  drain_timeout: 10s

services:
  slim/0:
    dataplane:
      clients:
        - endpoint: "https://external-slim-instance-address:46357"
          tls:
            insecure_skip_verify: true
          # You can configure the proxy settings here or by specifying the usual
          # HTTP_PROXY/HTTPS_PROXY/NO_PROXY environment variable.
          # The value specified in the configuration has precedence
          proxy:
            # At the moment we only support http:// connections to proxies
            url: http://your-http-proxy:80
