# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---

version: '3'

includes:
  python:
    taskfile: ../../../../tasks/python.yaml
    vars:
      UV_ARGS: '--package slimrpc'

tasks:
  run-server:
    desc: "Run the Python SlimRPC server example"
    cmds:
      - uv run simple-server

  run-client:
    desc: "Run the Python SlimRPC client example"
    cmds:
      - uv run simple-client
