# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

env:
  SHARED_SECRET: "demo-secret-key-for-examples012345"

tasks:
  default:
    cmds:
      - task -l

  install:bindings:
    desc: Install Java bindings JAR to local Maven repository
    cmds:
      - echo "📦 Installing Java bindings to Maven local repository..."
      - |
        if [ ! -f ../target/slim-bindings-java-0.7.0.jar ]; then
          echo "⚠️  Java bindings JAR not found, building first..."
          cd .. && task build
        fi
      - |
        mvn install:install-file \
          -Dfile=../target/slim-bindings-java-0.7.0.jar \
          -DgroupId=io.agntcy.slim \
          -DartifactId=slim-bindings-java \
          -Dversion=0.7.0 \
          -Dpackaging=jar \
          -DgeneratePom=true
      - echo "✅ Java bindings installed to ~/.m2/repository/io/agntcy/slim/slim-bindings-java/0.7.0/"

  compile:
    desc: Compile Java examples
    deps:
      - install:bindings
    cmds:
      - echo "🔨 Compiling Java examples..."
      - mvn clean compile
      - echo "✅ Java compilation complete"

  server:
    desc: Run the SLIM server example
    deps:
      - compile
    cmds:
      - echo "🚀 Starting SLIM server..."
      - mvn exec:java@server -Dexec.args="{{.CLI_ARGS}}"
    vars:
      CLI_ARGS: '{{.CLI_ARGS | default ""}}'

  p2p:alice:
    desc: "Point to Point example - Alice listens for messages and echoes them"
    deps:
      - compile
    cmds:
      - |
        mvn exec:java@p2p \
          -Dexec.args="--local agntcy/ns/alice --shared-secret $SHARED_SECRET {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  p2p:bob:
    desc: "Point to Point example - Bob sends unencrypted messages to Alice"
    deps:
      - compile
    cmds:
      - |
        mvn exec:java@p2p \
          -Dexec.args="--local agntcy/ns/bob --shared-secret $SHARED_SECRET --remote agntcy/ns/alice --message 'hello from Java' --iterations 5 {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  p2p:mls:bob:
    desc: "Point to Point example - Bob sends encrypted messages to Alice"
    deps:
      - compile
    cmds:
      - |
        mvn exec:java@p2p \
          -Dexec.args="--local agntcy/ns/bob --shared-secret $SHARED_SECRET --remote agntcy/ns/alice --message 'hello from Java (MLS)' --iterations 5 --enable-mls {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  group:moderator:
    desc: "Group moderator - Creates channel, invites participants"
    deps:
      - compile
    cmds:
      - |
        mvn exec:java@group \
          -Dexec.args="--local agntcy/ns/moderator --shared-secret $SHARED_SECRET --remote agntcy/ns/chat --invites agntcy/ns/client-1 --invites agntcy/ns/client-2 {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  group:client-1:
    desc: "Group participant - Waits for invitation"
    deps:
      - compile
    cmds:
      - |
        mvn exec:java@group \
          -Dexec.args="--local agntcy/ns/client-1 --shared-secret $SHARED_SECRET {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  group:client-2:
    desc: "Group participant - Waits for invitation"
    deps:
      - compile
    cmds:
      - |
        mvn exec:java@group \
          -Dexec.args="--local agntcy/ns/client-2 --shared-secret $SHARED_SECRET {{.EXTRA_ARGS}}"
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  clean:
    desc: Clean Maven build artifacts
    cmds:
      - echo "🧹 Cleaning Java build artifacts..."
      - mvn clean
      - echo "✅ Clean complete"
