// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

//! DPoP (RFC 9449) proofs, RFC 7638 JWK thumbprints, and the key attestation
//! that binds an app-supplied MLS signature key to a DPoP-bound identity key.
//!
//! # Two keys, not one
//!
//! - **`K_pop`, the identity key.** Generated once by `slimctl login`, proved to
//!   the IdP at the token exchange, and named by the token's `cnf.jkt`. Always
//!   P-256, since only JOSE constrains it. Never handed to `mls-rs`.
//! - **`K_leaf`, the MLS leaf key.** Generated by the `mls-rs` crypto provider
//!   under the active ciphersuite, whenever it likes, and installed through
//!   `set_signature_keys`. Rotates freely.
//!
//! `cnf.jkt` is written by the IdP at issuance and cannot be recomputed
//! locally, so a token can only ever confirm the one key its grant was minted
//! under. Binding `K_leaf` to it directly therefore forces the login to own MLS
//! key generation — which breaks rotation, snapshot restore, and any app that
//! supplies its own key through slim-sdk.
//!
//! Instead `K_pop` signs a short-lived [attestation](build_key_attestation)
//! naming `K_leaf`, and the credential carries both:
//!
//! ```text
//! <access token> ~ <attestation JWS>
//! ```
//!
//! A verifier then walks four links, each independently cryptographic:
//!
//! ```text
//! IdP JWKS ──signs──> access token {sub, cnf.jkt}
//!                          │  jkt: SHA-256 digest commitment
//!                          ▼
//!                        K_pop ──signs──> attestation {pubkey: K_leaf}
//!                                              │  byte equality
//!                                              ▼
//!                                 LeafNode.signature_key ──> MLS TBS signatures
//! ```
//!
//! Why an envelope signed by `K_leaf` itself would *not* do: every group member
//! holds the whole ratchet tree, so any member can read a peer's credential
//! verbatim, strip the envelope, and re-sign it under their own key. Only a
//! signature by a key the IdP already vouched for distinguishes the owner's
//! choice of `K_leaf` from an onlooker's.
//!
//! Ciphersuite comes from the public key length, as in
//! [`crate::utils::sign_header_aad`]: 32 → Ed25519/`EdDSA`, 33 or 65 → P-256/`ES256`.
//! That dispatch governs `K_pop` and the signing of proofs; `K_leaf` rides
//! inside the attestation payload as opaque bytes and is unconstrained by JOSE.
//!
//! Avoids `jsonwebtoken` and `reqwest` so it compiles for wasm32, where
//! `validate_member` still needs thumbprints.

use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD as B64URL;
use rand::RngExt;
use sha2::{Digest, Sha256};

use crate::errors::AuthError;

/// `typ` of a key attestation. Distinct from `dpop+jwt` so a proof captured
/// from a token-endpoint request cannot be replayed as an attestation, or the
/// reverse: both are a JWS with a `jwk` header over an app-held key, and only
/// `typ` separates them.
pub const ATTESTATION_TYP: &str = "slim-key-att+jwt";

/// Lifetime of a minted attestation. Matches the credential TTL SHADI uses:
/// short enough that a bounded replay window is the only exposure of a `K_leaf`
/// binding, cheap enough to re-sign on demand (one ECDSA operation).
pub const ATTESTATION_TTL_SECS: u64 = 300;

/// Re-sign this far before `exp`, so a credential handed out now is still valid
/// by the time it reaches a peer.
#[cfg(not(target_arch = "wasm32"))]
const ATTESTATION_REFRESH_BUFFER_SECS: u64 = 30;

/// Verifier-side ceiling on `exp - iat`, independent of what the signer asked
/// for. Bounds how long a compromised `K_leaf` stays attested even if whoever
/// signed the attestation chose a long lifetime.
const ATTESTATION_MAX_TTL_SECS: u64 = 3600;

/// Tolerance for clock skew between signer and verifier, applied at both ends
/// of the validity window.
const ATTESTATION_CLOCK_SKEW_SECS: u64 = 60;

fn now_secs() -> u64 {
    web_time::SystemTime::now()
        .duration_since(web_time::SystemTime::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

/// The RFC 7638 canonical JWK of an MLS public key, plus its JOSE `alg`.
///
/// Required members only, lexicographically ordered, no whitespace. Serves as
/// both the thumbprint hash input and a proof's `jwk` header member.
fn canonical_jwk(public_key: &[u8]) -> Result<(String, &'static str), AuthError> {
    use crate::utils::KeyCurve;

    match KeyCurve::from_public_key_len(public_key.len()) {
        Some(KeyCurve::Ed25519) => Ok((
            format!(
                r#"{{"crv":"Ed25519","kty":"OKP","x":"{}"}}"#,
                B64URL.encode(public_key)
            ),
            "EdDSA",
        )),
        // Decompress first: one key must not thumbprint differently depending on
        // which SEC1 encoding the provider handed back.
        Some(KeyCurve::P256) => {
            let verifying_key = crate::utils::p256_verifying_key(public_key)?;
            let point = verifying_key.to_encoded_point(false);
            let x = point.x().ok_or(AuthError::DpopUnsupportedKeyType)?;
            let y = point.y().ok_or(AuthError::DpopUnsupportedKeyType)?;
            Ok((
                format!(
                    r#"{{"crv":"P-256","kty":"EC","x":"{}","y":"{}"}}"#,
                    B64URL.encode(x),
                    B64URL.encode(y)
                ),
                "ES256",
            ))
        }
        None => Err(AuthError::DpopUnsupportedKeyType),
    }
}

/// RFC 7638 JWK thumbprint of an MLS public key — the value an IdP puts in
/// `cnf.jkt`, and what a peer recomputes to check the binding.
pub fn jwk_thumbprint(public_key: &[u8]) -> Result<String, AuthError> {
    let (jwk, _) = canonical_jwk(public_key)?;
    Ok(B64URL.encode(Sha256::digest(jwk.as_bytes())))
}

/// Read `cnf.jkt` from an access token, or `None` if it is unbound.
///
/// Unverified by design: only ever compared against a key the caller already
/// holds. `OidcVerifier` validates peer credentials against JWKS separately.
pub fn token_confirmation(access_token: &str) -> Option<String> {
    let payload = access_token.split('.').nth(1)?;
    let claims: serde_json::Value = serde_json::from_slice(&B64URL.decode(payload).ok()?).ok()?;
    claims.get("cnf")?.get("jkt")?.as_str().map(str::to_owned)
}

/// Build a DPoP proof JWT binding an HTTP request to the MLS signing key.
///
/// `htm` is the HTTP method (e.g. `POST`) and `htu` the target URI; per RFC 9449
/// §4.2 the query and fragment are stripped from `htu` before signing.
///
/// `nonce` answers a `use_dpop_nonce` challenge (RFC 9449 §8); pass `None` on
/// the first attempt.
pub fn build_proof(
    private_key: &[u8],
    public_key: &[u8],
    htm: &str,
    htu: &str,
    nonce: Option<&str>,
) -> Result<String, AuthError> {
    let (jwk, alg) = canonical_jwk(public_key)?;

    let htu = htu.split(['?', '#']).next().unwrap_or(htu);

    let iat = web_time::SystemTime::now()
        .duration_since(web_time::SystemTime::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    let mut jti_bytes = [0u8; 16];
    rand::rng().fill(&mut jti_bytes);

    let header = format!(r#"{{"typ":"dpop+jwt","alg":"{alg}","jwk":{jwk}}}"#);
    // `htu` comes from a discovery document, so let serde escape it.
    let mut payload = serde_json::json!({
        "htm": htm,
        "htu": htu,
        "iat": iat,
        "jti": B64URL.encode(jti_bytes),
    });
    if let (Some(nonce), Some(obj)) = (nonce, payload.as_object_mut()) {
        obj.insert("nonce".to_string(), serde_json::Value::String(nonce.into()));
    }
    let payload = payload.to_string();

    sign_compact(&header, &payload, private_key, public_key)
}

/// Assemble a JWS compact serialization from an already-rendered protected
/// header and payload. Shared by [`build_proof`] and
/// [`build_key_attestation`] so the two objects cannot drift in how they are
/// signed — only in what they say.
fn sign_compact(
    header: &str,
    payload: &str,
    private_key: &[u8],
    public_key: &[u8],
) -> Result<String, AuthError> {
    let signing_input = format!(
        "{}.{}",
        B64URL.encode(header.as_bytes()),
        B64URL.encode(payload.as_bytes())
    );
    let signature = sign_jws(signing_input.as_bytes(), private_key, public_key)?;
    Ok(format!("{signing_input}.{}", B64URL.encode(signature)))
}

/// Sign JWS signing input. JOSE wants fixed-width `R || S` for `ES256`, not the
/// DER encoding [`crate::utils::sign_header_aad`] produces.
fn sign_jws(
    signing_input: &[u8],
    private_key: &[u8],
    public_key: &[u8],
) -> Result<Vec<u8>, AuthError> {
    use crate::utils::KeyCurve;

    match KeyCurve::from_public_key_len(public_key.len()) {
        Some(KeyCurve::Ed25519) => {
            use ed25519_dalek::Signer;

            let key = crate::utils::ed25519_signing_key(private_key, public_key)?;
            Ok(key.sign(signing_input).to_bytes().to_vec())
        }
        Some(KeyCurve::P256) => {
            use p256::ecdsa::Signature;
            use p256::ecdsa::signature::Signer as _;

            let key = crate::utils::p256_signing_key(private_key, public_key)?;
            let signature: Signature = key.sign(signing_input);
            Ok(signature.to_bytes().to_vec())
        }
        None => Err(AuthError::DpopUnsupportedKeyType),
    }
}

/// Verify JWS signing input against a public key. Counterpart of [`sign_jws`],
/// so JOSE's fixed-width `R || S` is what is expected for `ES256` — not the DER
/// encoding [`crate::utils::verify_header_aad`] parses.
fn verify_jws(signing_input: &[u8], signature: &[u8], public_key: &[u8]) -> Result<(), AuthError> {
    use crate::utils::KeyCurve;

    match KeyCurve::from_public_key_len(public_key.len()) {
        Some(KeyCurve::Ed25519) => {
            use ed25519_dalek::{Signature, Verifier, VerifyingKey};

            let key = VerifyingKey::from_bytes(
                public_key
                    .try_into()
                    .map_err(|_| AuthError::DpopUnsupportedKeyType)?,
            )
            .map_err(|_| AuthError::DpopUnsupportedKeyType)?;
            let signature = Signature::from_slice(signature)
                .map_err(|_| AuthError::AttestationSignatureInvalid)?;
            key.verify(signing_input, &signature)
                .map_err(|_| AuthError::AttestationSignatureInvalid)
        }
        Some(KeyCurve::P256) => {
            use p256::ecdsa::Signature;
            use p256::ecdsa::signature::Verifier as _;

            let key = crate::utils::p256_verifying_key(public_key)?;
            let signature = Signature::from_slice(signature)
                .map_err(|_| AuthError::AttestationSignatureInvalid)?;
            key.verify(signing_input, &signature)
                .map_err(|_| AuthError::AttestationSignatureInvalid)
        }
        None => Err(AuthError::DpopUnsupportedKeyType),
    }
}

/// Recover raw public key bytes from a JWK, inverse of [`canonical_jwk`].
///
/// Only the key material is read (`x`, and `y` for EC), so extra members are
/// ignored — the caller re-derives the canonical form from the bytes returned
/// here, which is what makes a thumbprint comparison immune to a JWK dressed up
/// with unexpected fields.
fn public_key_from_jwk(jwk: &serde_json::Value) -> Result<Vec<u8>, AuthError> {
    let member = |name: &str| -> Result<Vec<u8>, AuthError> {
        let encoded =
            jwk.get(name)
                .and_then(|v| v.as_str())
                .ok_or(AuthError::AttestationMalformed(
                    "jwk is missing a coordinate",
                ))?;
        let decoded = B64URL
            .decode(encoded)
            .map_err(|_| AuthError::AttestationMalformed("jwk coordinate is not base64url"))?;
        if decoded.len() != 32 {
            return Err(AuthError::AttestationMalformed(
                "jwk coordinate is not 32 bytes",
            ));
        }
        Ok(decoded)
    };

    let kty = jwk.get("kty").and_then(|v| v.as_str());
    let crv = jwk.get("crv").and_then(|v| v.as_str());

    match (kty, crv) {
        (Some("OKP"), Some("Ed25519")) => member("x"),
        (Some("EC"), Some("P-256")) => {
            // Uncompressed SEC1: `p256_verifying_key` accepts this, and
            // `canonical_jwk` decompresses before hashing, so the thumbprint of
            // the result matches whichever encoding the peer's provider used.
            let mut point = Vec::with_capacity(65);
            point.push(0x04);
            point.extend_from_slice(&member("x")?);
            point.extend_from_slice(&member("y")?);
            Ok(point)
        }
        _ => Err(AuthError::DpopUnsupportedKeyType),
    }
}

/// A verified key attestation.
pub struct KeyAttestation {
    /// RFC 7638 thumbprint of the key that signed it — compare against the
    /// access token's `cnf.jkt` to establish that the IdP vouched for the
    /// signer.
    pub signer_jkt: String,
    /// The MLS leaf public key the signer attested. Compare against the
    /// presented `LeafNode.signature_key`.
    pub leaf_public_key: Vec<u8>,
}

/// Sign a statement that the holder of `K_pop` chose `leaf_public_key` as its
/// MLS leaf key, valid for [`ATTESTATION_TTL_SECS`].
///
/// `K_pop` goes into the protected header as `jwk`, so the object is
/// self-describing and a verifier needs no key distribution — it recomputes the
/// thumbprint and checks it against `cnf.jkt`.
///
/// `leaf_public_key` is carried as opaque bytes: it is never parsed as a JWK, so
/// any curve the MLS ciphersuite uses is fine, including ones with no JOSE
/// mapping.
pub fn build_key_attestation(
    pop_private_key: &[u8],
    pop_public_key: &[u8],
    leaf_public_key: &[u8],
) -> Result<String, AuthError> {
    let (jwk, alg) = canonical_jwk(pop_public_key)?;

    let iat = now_secs();
    let mut jti_bytes = [0u8; 16];
    rand::rng().fill(&mut jti_bytes);

    let header = format!(r#"{{"typ":"{ATTESTATION_TYP}","alg":"{alg}","jwk":{jwk}}}"#);
    let payload = serde_json::json!({
        "pubkey": B64URL.encode(leaf_public_key),
        "iat": iat,
        "exp": iat + ATTESTATION_TTL_SECS,
        "jti": B64URL.encode(jti_bytes),
    })
    .to_string();

    sign_compact(&header, &payload, pop_private_key, pop_public_key)
}

/// Verify a key attestation and return who signed it and what they attested.
///
/// Establishes only that the holder of the key in the protected header chose
/// this MLS key, recently. The caller MUST still check
/// [`KeyAttestation::signer_jkt`] against the access token's `cnf.jkt` — without
/// that step this proves possession of an arbitrary key, which is exactly the
/// forgery the module doc describes.
pub fn verify_key_attestation(attestation: &str) -> Result<KeyAttestation, AuthError> {
    let mut parts = attestation.split('.');
    let (Some(header_b64), Some(payload_b64), Some(signature_b64), None) =
        (parts.next(), parts.next(), parts.next(), parts.next())
    else {
        return Err(AuthError::AttestationMalformed(
            "not a three-part JWS compact serialization",
        ));
    };

    let decode = |part: &str| -> Result<Vec<u8>, AuthError> {
        B64URL
            .decode(part)
            .map_err(|_| AuthError::AttestationMalformed("JWS part is not base64url"))
    };
    let header: serde_json::Value = serde_json::from_slice(&decode(header_b64)?)
        .map_err(|_| AuthError::AttestationMalformed("header is not JSON"))?;

    // Domain separation: a `dpop+jwt` proof is the same shape over the same key.
    if header.get("typ").and_then(|v| v.as_str()) != Some(ATTESTATION_TYP) {
        return Err(AuthError::AttestationMalformed("unexpected typ"));
    }
    // JOSE requires rejecting a `crit` member that is not understood, and this
    // implementation understands none.
    if header.get("crit").is_some() {
        return Err(AuthError::AttestationMalformed("unsupported crit member"));
    }

    let jwk = header
        .get("jwk")
        .ok_or(AuthError::AttestationMalformed("header has no jwk"))?;
    let signer_public_key = public_key_from_jwk(jwk)?;

    // `alg` from the key, never from the header — the header is attacker-supplied
    // and a mismatch is how algorithm-confusion attacks start.
    let (_, expected_alg) = canonical_jwk(&signer_public_key)?;
    if header.get("alg").and_then(|v| v.as_str()) != Some(expected_alg) {
        return Err(AuthError::AttestationMalformed(
            "alg does not match the advertised jwk",
        ));
    }

    let signature = decode(signature_b64)?;
    let signing_input = format!("{header_b64}.{payload_b64}");
    verify_jws(signing_input.as_bytes(), &signature, &signer_public_key)?;

    // Only now is the payload trustworthy.
    let payload: serde_json::Value = serde_json::from_slice(&decode(payload_b64)?)
        .map_err(|_| AuthError::AttestationMalformed("payload is not JSON"))?;

    let iat = payload
        .get("iat")
        .and_then(|v| v.as_u64())
        .ok_or(AuthError::AttestationMalformed("payload has no iat"))?;
    let exp = payload
        .get("exp")
        .and_then(|v| v.as_u64())
        .ok_or(AuthError::AttestationMalformed("payload has no exp"))?;
    if exp.saturating_sub(iat) > ATTESTATION_MAX_TTL_SECS {
        return Err(AuthError::AttestationMalformed("lifetime exceeds the cap"));
    }
    let now = now_secs();
    if now + ATTESTATION_CLOCK_SKEW_SECS < iat || now > exp + ATTESTATION_CLOCK_SKEW_SECS {
        return Err(AuthError::AttestationNotCurrent);
    }

    let leaf_public_key = payload
        .get("pubkey")
        .and_then(|v| v.as_str())
        .ok_or(AuthError::AttestationMalformed("payload has no pubkey"))?;
    let leaf_public_key = B64URL
        .decode(leaf_public_key)
        .map_err(|_| AuthError::AttestationMalformed("pubkey is not base64url"))?;
    if leaf_public_key.is_empty() {
        return Err(AuthError::AttestationMalformed("pubkey is empty"));
    }

    Ok(KeyAttestation {
        signer_jkt: jwk_thumbprint(&signer_public_key)?,
        leaf_public_key,
    })
}

/// The identity key a credential is DPoP-bound to, plus the MLS leaf key it
/// currently attests.
///
/// One per identity, shared behind a lock across an app and every session cloned
/// from it, so an MLS key rotation is visible to all of them at once. Holding
/// both halves here is what keeps them from drifting: `K_pop` is installed once
/// from the credentials store and never replaced, `K_leaf` is replaced as often
/// as `mls-rs` likes, and the cached attestation is invalidated by either.
#[cfg(not(target_arch = "wasm32"))]
pub(crate) struct IdentityKey {
    /// `K_pop` as `(secret, public)`. Signs DPoP proofs and attestations.
    pop: (Vec<u8>, Vec<u8>),
    /// `K_leaf` as `(secret, public)`. `mls-rs` reads the secret back out
    /// through `get_signature_keys`; the public half is what gets attested.
    ///
    /// Seeded at construction, as `SignerJwt` and the SPIRE manager also do, so
    /// the credential is complete before any MLS group exists: control messages
    /// carry an e2e header signature from the app's very first message, and a
    /// peer needs a `pubkey` claim to verify it.
    leaf: (Vec<u8>, Vec<u8>),
    /// Whether the MLS layer has replaced the seeded key with one of its own.
    ///
    /// Reported as `mls_signature_keys_installed`, which the MLS layer branches
    /// on to decide whether to adopt an installed key or generate one. It must
    /// generate: the seeded key follows the compile-time curve feature, while
    /// the MLS ciphersuite is chosen at runtime. Conflating the two is what
    /// makes `enforce_pqc` reject a P-256 key at startup.
    leaf_from_mls: bool,
    /// Last minted attestation, with the key it names and its `exp`.
    cached: Option<(String, Vec<u8>, u64)>,
}

#[cfg(not(target_arch = "wasm32"))]
impl IdentityKey {
    /// Rejects a `K_pop` with no JOSE mapping here, rather than at every later
    /// signing attempt once a credential is already in flight.
    pub(crate) fn new(private_key: Vec<u8>, public_key: Vec<u8>) -> Result<Self, AuthError> {
        jwk_thumbprint(&public_key)?;
        Ok(Self {
            pop: (private_key, public_key),
            leaf: crate::utils::generate_mls_signature_keys()?,
            leaf_from_mls: false,
            cached: None,
        })
    }

    /// `K_pop`, for proofing a token request.
    pub(crate) fn pop_keys(&self) -> &(Vec<u8>, Vec<u8>) {
        &self.pop
    }

    /// Adopt the MLS leaf key the MLS layer just generated. Unconditional by
    /// design: a rotation is a new attestation, not a new login.
    ///
    /// No cache invalidation needed — [`Self::attestation`] compares the cached
    /// entry against the installed key on every call.
    pub(crate) fn install_leaf(&mut self, private_key: Vec<u8>, public_key: Vec<u8>) {
        self.leaf = (private_key, public_key);
        self.leaf_from_mls = true;
    }

    pub(crate) fn leaf_keys(&self) -> (Vec<u8>, Vec<u8>) {
        self.leaf.clone()
    }

    /// Whether the MLS layer has installed its own ciphersuite-correct key, as
    /// opposed to the pair seeded at construction.
    pub(crate) fn leaf_installed_by_mls(&self) -> bool {
        self.leaf_from_mls
    }

    /// A currently-valid attestation over the installed leaf key, minting one if
    /// the cache is empty, stale, or names a key that has since been replaced.
    pub(crate) fn attestation(&mut self) -> Result<String, AuthError> {
        let leaf_public = self.leaf.1.clone();

        let now = now_secs();
        if let Some((jws, named, exp)) = &self.cached
            && named == &leaf_public
            && *exp > now + ATTESTATION_REFRESH_BUFFER_SECS
        {
            return Ok(jws.clone());
        }

        let jws = build_key_attestation(&self.pop.0, &self.pop.1, &leaf_public)?;
        self.cached = Some((jws.clone(), leaf_public, now + ATTESTATION_TTL_SECS));
        Ok(jws)
    }
}

/// Shared, lock-guarded home for an optional [`IdentityKey`], factored out of
/// `OidcTokenProvider` and `RefreshTokenProvider` — both held one independently
/// and re-implemented the same install/query/attestation logic over it, which
/// had already started drifting (only one of the two checked a delegate first).
/// Cloning shares the same underlying key, same as the `Arc` each provider
/// wrapped it in before.
#[cfg(not(target_arch = "wasm32"))]
#[derive(Clone, Default)]
pub(crate) struct IdentitySlot(std::sync::Arc<parking_lot::RwLock<Option<IdentityKey>>>);

#[cfg(not(target_arch = "wasm32"))]
impl IdentitySlot {
    /// Install the identity key a credential is DPoP-bound to. Re-installing
    /// the same key is a no-op: replacing the slot here would discard any MLS
    /// leaf key already installed under it.
    pub(crate) fn install_identity_keys(
        &self,
        private_key: Vec<u8>,
        public_key: Vec<u8>,
    ) -> Result<(), AuthError> {
        let mut guard = self.0.write();
        if guard.as_ref().is_some_and(|k| k.pop_keys().1 == public_key) {
            return Ok(());
        }
        *guard = Some(IdentityKey::new(private_key, public_key)?);
        Ok(())
    }

    /// Take ownership of an identity key (and whatever leaf key it already
    /// attests) — unconditional, for a caller that is becoming its sole owner.
    pub(crate) fn adopt(&self, identity: IdentityKey) {
        *self.0.write() = Some(identity);
    }

    /// Hand the installed key to a new owner, leaving this slot empty.
    pub(crate) fn take(&self) -> Option<IdentityKey> {
        self.0.write().take()
    }

    /// Whether a DPoP-bound identity key is installed.
    pub(crate) fn is_installed(&self) -> bool {
        self.0.read().is_some()
    }

    /// Install the MLS leaf key to attest under the identity key. Unconditional:
    /// the leaf key is not what `cnf.jkt` names, so it may be replaced as often
    /// as `mls-rs` likes.
    pub(crate) fn install_signature_keys(
        &self,
        private_key: Vec<u8>,
        public_key: Vec<u8>,
    ) -> Result<(), AuthError> {
        self.0
            .write()
            .as_mut()
            .ok_or(AuthError::AttestationNoIdentityKey)?
            .install_leaf(private_key, public_key);
        Ok(())
    }

    /// The MLS leaf key, but only once the MLS layer has installed its own —
    /// never the pair seeded at construction.
    pub(crate) fn mls_installed_leaf_keys(&self) -> Option<(Vec<u8>, Vec<u8>)> {
        let guard = self.0.read();
        let key = guard.as_ref()?;
        key.leaf_installed_by_mls().then(|| key.leaf_keys())
    }

    /// The MLS leaf key, installed or seeded at construction — `None` only
    /// when no identity key exists at all.
    pub(crate) fn get_signature_keys(&self) -> Result<(Vec<u8>, Vec<u8>), AuthError> {
        self.0
            .read()
            .as_ref()
            .map(|k| k.leaf_keys())
            .ok_or(AuthError::MlsNotSupported)
    }

    /// Whether the *MLS layer* installed its own leaf key, as opposed to the
    /// pair seeded at construction.
    pub(crate) fn mls_signature_keys_installed(&self) -> bool {
        self.0.read().as_ref().is_some_and(|k| k.leaf_installed_by_mls())
    }

    /// `K_pop`, for proofing a token request. `None` for a plain bearer
    /// identity with no DPoP binding.
    pub(crate) fn pop_keys(&self) -> Option<(Vec<u8>, Vec<u8>)> {
        self.0.read().as_ref().map(|k| k.pop_keys().clone())
    }

    /// A currently-valid attestation over the installed leaf key, or `None`
    /// when no identity key exists (a plain bearer identity).
    pub(crate) fn mint_attestation(&self) -> Result<Option<String>, AuthError> {
        self.0.write().as_mut().map(|k| k.attestation()).transpose()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    /// RFC 7638 §3.1 worked example. It uses an RSA key, which MLS never
    /// produces, so exercise the hash-and-encode step directly against the
    /// canonical JSON the RFC prints to pin down that half of the algorithm.
    #[test]
    fn rfc7638_thumbprint_vector() {
        let canonical = r#"{"e":"AQAB","kty":"RSA","n":"0vx7agoebGcQSuuPiLJXZptN9nndrQmbXEps2aiAFbWhM78LhWx4cbbfAAtVT86zwu1RK7aPFFxuhDR1L6tSoc_BJECPebWKRXjBZCiFV4n3oknjhMstn64tZ_2W-5JsGY4Hc5n9yBXArwl93lqt7_RN5w6Cf0h4QyQ5v-65YGjQR0_FDW2QvzqY368QQMicAtaSqzs8KJZgnYb9c7d0zgdAZHzu6qMQvRL5hajrn1n91CbOpbISD08qNLyrdkt-bFTWhAI4vMQFh6WeZu0fM4lFd2NcRwr3XPksINHaQ-G_xBniIqbw0Ls1jF44-csFCur-kEgU8awapJzKnqDKgw"}"#;
        assert_eq!(
            B64URL.encode(Sha256::digest(canonical.as_bytes())),
            "NzbLsXh8uDCcd-6MNwXF4W_7noWXFZAfHkxZsRGC9Xs"
        );
    }

    /// A key handed back compressed and uncompressed is one key, so it must
    /// yield one thumbprint — otherwise `cnf.jkt` would fail to match whenever
    /// the token side and the MLS side disagreed on point encoding.
    #[test]
    fn p256_thumbprint_is_encoding_independent() {
        let (_, compressed, uncompressed) = test_p256_keys();
        assert_eq!(
            jwk_thumbprint(&compressed).unwrap(),
            jwk_thumbprint(&uncompressed).unwrap()
        );
    }

    #[test]
    fn distinct_keys_get_distinct_thumbprints() {
        let (_, a, _) = test_p256_keys();
        let (_, b, _) = test_p256_keys();
        assert_ne!(jwk_thumbprint(&a).unwrap(), jwk_thumbprint(&b).unwrap());
    }

    #[test]
    fn unsupported_key_length_rejected() {
        assert!(matches!(
            jwk_thumbprint(&[0u8; 20]),
            Err(AuthError::DpopUnsupportedKeyType)
        ));
    }

    /// The proof must verify under the very key whose thumbprint it advertises —
    /// that identity is the whole point of the binding.
    #[test]
    fn p256_proof_verifies_against_advertised_key() {
        use p256::ecdsa::Signature;
        use p256::ecdsa::signature::Verifier;

        let (secret, public, _) = test_p256_keys();
        let proof = build_proof(&secret, &public, "POST", "https://idp/token?x=1#f", None).unwrap();

        let parts: Vec<&str> = proof.split('.').collect();
        assert_eq!(parts.len(), 3);

        let header: Value = serde_json::from_slice(&B64URL.decode(parts[0]).unwrap()).unwrap();
        assert_eq!(header["typ"], "dpop+jwt");
        assert_eq!(header["alg"], "ES256");
        // The advertised jwk is the presented key.
        assert_eq!(
            B64URL.encode(Sha256::digest(
                serde_json::to_string(&header["jwk"]).unwrap().as_bytes()
            )),
            jwk_thumbprint(&public).unwrap()
        );

        let payload: Value = serde_json::from_slice(&B64URL.decode(parts[1]).unwrap()).unwrap();
        assert_eq!(payload["htm"], "POST");
        // Query and fragment stripped per RFC 9449 §4.2.
        assert_eq!(payload["htu"], "https://idp/token");
        assert!(payload["iat"].as_u64().unwrap() > 0);
        assert!(!payload["jti"].as_str().unwrap().is_empty());

        let signature = Signature::from_slice(&B64URL.decode(parts[2]).unwrap()).unwrap();
        crate::utils::p256_verifying_key(&public)
            .unwrap()
            .verify(format!("{}.{}", parts[0], parts[1]).as_bytes(), &signature)
            .unwrap();
    }

    #[test]
    fn ed25519_proof_verifies_against_advertised_key() {
        use ed25519_dalek::{Signature, Verifier, VerifyingKey};

        let (secret, public) = test_ed25519_keys();
        let proof = build_proof(&secret, &public, "POST", "https://idp/token", None).unwrap();

        let parts: Vec<&str> = proof.split('.').collect();
        let header: Value = serde_json::from_slice(&B64URL.decode(parts[0]).unwrap()).unwrap();
        assert_eq!(header["alg"], "EdDSA");
        assert_eq!(header["jwk"]["kty"], "OKP");

        let signature = Signature::from_slice(&B64URL.decode(parts[2]).unwrap()).unwrap();
        VerifyingKey::from_bytes(public[..].try_into().unwrap())
            .unwrap()
            .verify(format!("{}.{}", parts[0], parts[1]).as_bytes(), &signature)
            .unwrap();
    }

    /// Two proofs from one key must differ, or the IdP's `jti` replay cache
    /// rejects the second request.
    #[test]
    fn proofs_are_unique_per_call() {
        let (secret, public, _) = test_p256_keys();
        let a = build_proof(&secret, &public, "POST", "https://idp/token", None).unwrap();
        let b = build_proof(&secret, &public, "POST", "https://idp/token", None).unwrap();
        assert_ne!(a, b);
    }

    fn test_p256_keys() -> (Vec<u8>, Vec<u8>, Vec<u8>) {
        use p256::SecretKey;
        use p256::elliptic_curve::rand_core::OsRng;

        let secret_key = SecretKey::random(&mut OsRng);
        let verifying_key = p256::ecdsa::SigningKey::from(&secret_key);
        let verifying_key = verifying_key.verifying_key();
        (
            secret_key.to_bytes().to_vec(),
            verifying_key.to_encoded_point(true).as_bytes().to_vec(),
            verifying_key.to_encoded_point(false).as_bytes().to_vec(),
        )
    }

    fn test_ed25519_keys() -> (Vec<u8>, Vec<u8>) {
        use ed25519_dalek::SigningKey;

        let mut seed = [0u8; 32];
        rand::rng().fill(&mut seed);
        let signing_key = SigningKey::from_bytes(&seed);
        let public = signing_key.verifying_key().to_bytes().to_vec();
        (seed.to_vec(), public)
    }

    // ---------------------------------------------------------------------
    // Key attestations
    // ---------------------------------------------------------------------

    /// The happy path: what the signer says is what the verifier reads back, and
    /// the signer is identified by the thumbprint the IdP would have bound.
    #[test]
    fn attestation_round_trips() {
        let (pop_secret, pop_public, _) = test_p256_keys();
        let (_, leaf_public) = test_ed25519_keys();

        let jws = build_key_attestation(&pop_secret, &pop_public, &leaf_public).unwrap();
        let attested = verify_key_attestation(&jws).unwrap();

        assert_eq!(attested.leaf_public_key, leaf_public);
        assert_eq!(attested.signer_jkt, jwk_thumbprint(&pop_public).unwrap());
    }

    /// An Ed25519 identity key must work too — the curve is chosen by whatever
    /// generated the login key, and `EdDSA` is a valid DPoP algorithm.
    #[test]
    fn attestation_round_trips_with_an_ed25519_signer() {
        let (pop_secret, pop_public) = test_ed25519_keys();
        let (_, leaf_public, _) = test_p256_keys();

        let jws = build_key_attestation(&pop_secret, &pop_public, &leaf_public).unwrap();
        let attested = verify_key_attestation(&jws).unwrap();
        assert_eq!(attested.leaf_public_key, leaf_public);
    }

    /// The leaf key is opaque payload bytes, never parsed as a JWK, so a
    /// ciphersuite with no JOSE mapping is still attestable. This is what lets
    /// the MLS ciphersuite and the DPoP algorithm stop constraining each other.
    #[test]
    fn attestation_accepts_a_leaf_key_with_no_jose_mapping() {
        let (pop_secret, pop_public, _) = test_p256_keys();
        // 48 bytes: `KeyCurve::from_public_key_len` returns None for this.
        let leaf_public = vec![3u8; 48];
        assert!(jwk_thumbprint(&leaf_public).is_err());

        let jws = build_key_attestation(&pop_secret, &pop_public, &leaf_public).unwrap();
        assert_eq!(
            verify_key_attestation(&jws).unwrap().leaf_public_key,
            leaf_public
        );
    }

    /// Any edit to the signed material must fail, or the leaf key it names could
    /// be swapped after signing.
    #[test]
    fn tampering_with_the_payload_is_rejected() {
        let (pop_secret, pop_public, _) = test_p256_keys();
        let (_, victim_leaf) = test_ed25519_keys();
        let (_, attacker_leaf) = test_ed25519_keys();

        let jws = build_key_attestation(&pop_secret, &pop_public, &victim_leaf).unwrap();
        let mut parts = jws.split('.');
        let header = parts.next().unwrap();
        let signature = parts.nth(1).unwrap();

        // Re-encode the payload naming the attacker's key, keep the signature.
        let forged_payload = B64URL.encode(
            serde_json::json!({
                "pubkey": B64URL.encode(&attacker_leaf),
                "iat": now_secs(),
                "exp": now_secs() + ATTESTATION_TTL_SECS,
                "jti": "x",
            })
            .to_string(),
        );

        assert!(matches!(
            verify_key_attestation(&format!("{header}.{forged_payload}.{signature}")),
            Err(AuthError::AttestationSignatureInvalid)
        ));
    }

    /// Swapping the advertised key for the attacker's own does verify — which is
    /// exactly why the caller must compare `signer_jkt` to `cnf.jkt`. Asserted
    /// here so the split of responsibility is pinned by a test.
    #[test]
    fn a_self_consistent_attestation_from_any_key_verifies() {
        let (attacker_secret, attacker_public, _) = test_p256_keys();
        let (_, attacker_leaf) = test_ed25519_keys();

        let jws =
            build_key_attestation(&attacker_secret, &attacker_public, &attacker_leaf).unwrap();
        let attested = verify_key_attestation(&jws).unwrap();

        // Verification alone proves possession of *a* key, nothing about whose.
        assert_eq!(
            attested.signer_jkt,
            jwk_thumbprint(&attacker_public).unwrap()
        );
    }

    /// A DPoP proof is the same shape over the same key. Without the `typ` check
    /// one captured from a token request would pass as an attestation.
    #[test]
    fn a_dpop_proof_is_not_an_attestation() {
        let (secret, public, _) = test_p256_keys();
        let proof = build_proof(&secret, &public, "POST", "https://idp/token", None).unwrap();

        assert!(matches!(
            verify_key_attestation(&proof),
            Err(AuthError::AttestationMalformed(_))
        ));
    }

    /// JOSE requires rejecting a `crit` member that is not understood, and this
    /// implementation understands none.
    #[test]
    fn an_unknown_crit_member_is_rejected() {
        let (secret, public, _) = test_p256_keys();
        let (jwk, alg) = canonical_jwk(&public).unwrap();
        let header =
            format!(r#"{{"typ":"{ATTESTATION_TYP}","alg":"{alg}","crit":["exp"],"jwk":{jwk}}}"#);
        let payload = serde_json::json!({
            "pubkey": B64URL.encode([1u8; 32]),
            "iat": now_secs(),
            "exp": now_secs() + ATTESTATION_TTL_SECS,
        })
        .to_string();
        let jws = sign_compact(&header, &payload, &secret, &public).unwrap();

        assert!(matches!(
            verify_key_attestation(&jws),
            Err(AuthError::AttestationMalformed("unsupported crit member"))
        ));
    }

    /// `alg` comes from the advertised key, never from the attacker-supplied
    /// header — a mismatch is where algorithm-confusion attacks start.
    #[test]
    fn alg_must_match_the_advertised_key() {
        let (secret, public, _) = test_p256_keys();
        let (jwk, _) = canonical_jwk(&public).unwrap();
        // P-256 key, but the header claims EdDSA.
        let header = format!(r#"{{"typ":"{ATTESTATION_TYP}","alg":"EdDSA","jwk":{jwk}}}"#);
        let payload = serde_json::json!({
            "pubkey": B64URL.encode([1u8; 32]),
            "iat": now_secs(),
            "exp": now_secs() + ATTESTATION_TTL_SECS,
        })
        .to_string();
        let jws = sign_compact(&header, &payload, &secret, &public).unwrap();

        assert!(matches!(
            verify_key_attestation(&jws),
            Err(AuthError::AttestationMalformed(
                "alg does not match the advertised jwk"
            ))
        ));
    }

    /// Expiry is the only thing bounding the replay window on a key binding.
    #[test]
    fn an_expired_attestation_is_rejected() {
        let (secret, public, _) = test_p256_keys();
        let (jwk, alg) = canonical_jwk(&public).unwrap();
        let header = format!(r#"{{"typ":"{ATTESTATION_TYP}","alg":"{alg}","jwk":{jwk}}}"#);
        let stale = now_secs() - ATTESTATION_TTL_SECS - ATTESTATION_CLOCK_SKEW_SECS - 10;
        let payload = serde_json::json!({
            "pubkey": B64URL.encode([1u8; 32]),
            "iat": stale,
            "exp": stale + ATTESTATION_TTL_SECS,
        })
        .to_string();
        let jws = sign_compact(&header, &payload, &secret, &public).unwrap();

        assert!(matches!(
            verify_key_attestation(&jws),
            Err(AuthError::AttestationNotCurrent)
        ));
    }

    /// A signer must not be able to opt out of the replay bound by choosing a
    /// long lifetime; the ceiling is the verifier's to enforce.
    #[test]
    fn an_over_long_lifetime_is_rejected() {
        let (secret, public, _) = test_p256_keys();
        let (jwk, alg) = canonical_jwk(&public).unwrap();
        let header = format!(r#"{{"typ":"{ATTESTATION_TYP}","alg":"{alg}","jwk":{jwk}}}"#);
        let iat = now_secs();
        let payload = serde_json::json!({
            "pubkey": B64URL.encode([1u8; 32]),
            "iat": iat,
            "exp": iat + ATTESTATION_MAX_TTL_SECS + 1,
        })
        .to_string();
        let jws = sign_compact(&header, &payload, &secret, &public).unwrap();

        assert!(matches!(
            verify_key_attestation(&jws),
            Err(AuthError::AttestationMalformed("lifetime exceeds the cap"))
        ));
    }

    #[test]
    fn structurally_broken_attestations_are_rejected() {
        for garbage in ["", "a", "a.b", "a.b.c", "a.b.c.d", "!.!.!"] {
            assert!(
                verify_key_attestation(garbage).is_err(),
                "accepted {garbage:?}"
            );
        }
    }

    /// A JWK dressed up with extra members must not shift the thumbprint: the
    /// verifier re-derives the canonical form from the key material alone.
    #[test]
    fn extra_jwk_members_do_not_change_the_thumbprint() {
        let (secret, public, _) = test_p256_keys();
        let (jwk, alg) = canonical_jwk(&public).unwrap();
        let padded = jwk.replace(r#"{"crv""#, r#"{"kid":"decoration","use":"sig","crv""#);
        let header = format!(r#"{{"typ":"{ATTESTATION_TYP}","alg":"{alg}","jwk":{padded}}}"#);
        let payload = serde_json::json!({
            "pubkey": B64URL.encode([1u8; 32]),
            "iat": now_secs(),
            "exp": now_secs() + ATTESTATION_TTL_SECS,
        })
        .to_string();
        let jws = sign_compact(&header, &payload, &secret, &public).unwrap();

        assert_eq!(
            verify_key_attestation(&jws).unwrap().signer_jkt,
            jwk_thumbprint(&public).unwrap()
        );
    }

    // ---------------------------------------------------------------------
    // IdentityKey — native only, like the providers that own one
    // ---------------------------------------------------------------------

    /// A leaf key is seeded at construction, so the credential is complete
    /// before any MLS group exists — control messages are signed with it from the
    /// app's first message, and a peer needs a `pubkey` claim to verify them.
    #[test]
    fn identity_key_seeds_a_leaf_at_construction() {
        let (secret, public, _) = test_p256_keys();
        let mut key = IdentityKey::new(secret, public).unwrap();

        let (leaf_secret, leaf_public) = key.leaf_keys();
        assert!(!leaf_secret.is_empty() && !leaf_public.is_empty());

        let attested = verify_key_attestation(&key.attestation().unwrap()).unwrap();
        assert_eq!(attested.leaf_public_key, leaf_public);

        // ...but it must not look like a key the MLS layer chose, or `build_client`
        // adopts a key generated for the compile-time curve instead of the
        // runtime ciphersuite.
        assert!(!key.leaf_installed_by_mls());
    }

    /// The cache is what keeps this to one signature per TTL rather than one per
    /// `get_token`.
    #[test]
    fn identity_key_reuses_a_fresh_attestation() {
        let (secret, public, _) = test_p256_keys();
        let (leaf_secret, leaf_public) = test_ed25519_keys();
        let mut key = IdentityKey::new(secret, public).unwrap();
        key.install_leaf(leaf_secret, leaf_public);

        let first = key.attestation().unwrap();
        let second = key.attestation().unwrap();
        assert_eq!(first, second, "a fresh attestation must be reused");
    }

    /// ...but a rotation must invalidate it, or peers would be handed an
    /// attestation naming a key the leaf no longer uses.
    #[test]
    fn identity_key_re_signs_after_a_leaf_rotation() {
        let (secret, public, _) = test_p256_keys();
        let (leaf_secret, leaf_public) = test_ed25519_keys();
        let mut key = IdentityKey::new(secret, public).unwrap();
        key.install_leaf(leaf_secret, leaf_public);
        let before = key.attestation().unwrap();

        let (new_secret, new_public) = test_ed25519_keys();
        key.install_leaf(new_secret, new_public.clone());
        assert!(key.leaf_installed_by_mls());
        let after = key.attestation().unwrap();

        assert_ne!(before, after);
        assert_eq!(
            verify_key_attestation(&after).unwrap().leaf_public_key,
            new_public
        );
    }

    /// An identity key with no JOSE mapping cannot sign a proof or an
    /// attestation, so it is refused at construction.
    #[test]
    fn identity_key_rejects_an_unmappable_key() {
        assert!(matches!(
            IdentityKey::new(vec![0u8; 32], vec![0u8; 20]),
            Err(AuthError::DpopUnsupportedKeyType)
        ));
    }
}
