fn main() {
    // When using proc macros, the scaffolding is generated by the macros themselves
    // via uniffi::setup_scaffolding!() in the source code.
    // We just need to tell cargo to rerun if the source file changes.
    println!("cargo:rerun-if-changed=src/bindings/uniffi_bindings.rs");
}

