# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---

name: Setup Task with Cache
description: Setup Task (go-task/task) via arduino/setup-task
inputs:
  version:
    description: 'Task version to install (e.g., "3.39.2", "latest")'
    required: false
    default: 'v3.48.0'
  github-token:
    description: 'GitHub token for API requests'
    required: false
    default: ${{ github.token }}

outputs:
  version:
    description: 'The actual version of Task that was installed'
    value: ${{ inputs.version }}

runs:
  using: "composite"
  steps:
    - name: Setup Taskfile
      uses: ./.github/actions/setup-task
