{{- if .Values.spire.upstream.enabled }}
{{- $upstreamAgent := index .Values.spire "upstream-spire-agent" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-agent-upstream" .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  agent.conf: |
    agent {
      data_dir = "/var/lib/spire"
      log_level = {{ default "info" $upstreamAgent.logLevel | quote }}
      log_format = {{ default "text" $upstreamAgent.logFormat | quote }}
      {{- $rebootstrap := default "always" $upstreamAgent.rebootstrapMode }}
      {{- if $upstreamAgent.insecureBootstrap }}
      rebootstrap_mode = "never"
      {{- else }}
      rebootstrap_mode = {{ $rebootstrap | quote }}
      {{- end }}
      rebootstrap_delay = {{ default "10m" $upstreamAgent.rebootstrapDelay | quote }}
      server_address = {{ .Values.spire.global.spire.upstreamSpireAddress | quote }}
      server_port = {{ default 443 $upstreamAgent.server.port | quote }}
      socket_path = "/tmp/spire-agent/public/spire-agent.sock"
      {{- if $upstreamAgent.insecureBootstrap }}
      insecure_bootstrap = true
      {{- else if $upstreamAgent.trustBundlePath }}
      trust_bundle_path = {{ $upstreamAgent.trustBundlePath | quote }}
      trust_bundle_format = {{ default "pem" $upstreamAgent.trustBundleFormat | quote }}
      {{- else }}
      trust_bundle_url = {{ $upstreamAgent.trustBundleURL | quote }}
      trust_bundle_format = {{ default "spiffe" $upstreamAgent.trustBundleFormat | quote }}
      {{- end }}
      trust_domain = {{ .Values.spire.global.spire.trustDomain | quote }}
    }

    plugins {
      NodeAttestor "join_token" {
        plugin_data {}
      }
      KeyManager "memory" {
        plugin_data {}
      }
      WorkloadAttestor "k8s" {
        plugin_data {
          skip_kubelet_verification = true
          disable_container_selectors = false
          use_new_container_locator = true
          verbose_container_locator_logs = false
        }
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = {{ default 9981 $upstreamAgent.healthChecks.port | quote }}
      live_path = "/live"
      ready_path = "/ready"
    }
{{- end }}