[package]
name = "agntcy-slim-testing"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
publish = false

[lib]
name = "slim_testing"

[[bin]]
name = "workload-gen"
path = "src/bin/workload-gen.rs"

[[bin]]
name = "subscriber"
path = "src/bin/subscriber.rs"

[[bin]]
name = "publisher"
path = "src/bin/publisher.rs"

[[bin]]
name = "channel"
path = "src/bin/channel.rs"

[[bin]]
name = "test-group"
path = "src/bin/test_group.rs"

[[bin]]
name = "test-p2p"
path = "src/bin/test_p2p.rs"

[dependencies]
agntcy-slim = { workspace = true }
agntcy-slim-auth = { workspace = true }
agntcy-slim-config = { workspace = true }
agntcy-slim-datapath = { workspace = true }
agntcy-slim-service = { workspace = true }
agntcy-slim-session = { workspace = true }
agntcy-slim-tracing = { workspace = true }
aws-lc-rs = { workspace = true }
base64 = { workspace = true }
bollard = { version = "0.17" }
clap = { workspace = true }
futures = { workspace = true }
indicatif = { workspace = true }
jsonwebtoken-aws-lc = { workspace = true }
libc = { version = "0.2.177" }
parking_lot = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
wiremock = { workspace = true }
