[package]
name = "testing"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
publish = false

[[bin]]
name = "channel"
path = "src/bin/channel.rs"

[[bin]]
name = "test-group"
path = "src/bin/test_group.rs"

[[bin]]
name = "test-p2p"
path = "src/bin/test_p2p.rs"

[dependencies]
agntcy-slim = { workspace = true }
agntcy-slim-auth = { workspace = true }
agntcy-slim-config = { workspace = true }
agntcy-slim-datapath = { workspace = true }
agntcy-slim-service = { workspace = true }
agntcy-slim-session = { workspace = true }
agntcy-slim-tracing = { workspace = true }
clap = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
