version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

env:
  CONFIG_CLIENT: ../config/base/client-config.yaml
  CONFIG_SERVER: ./config/base/server-config.yaml
  SUB: 5000
  PUB: 10000
  SUB_APPS: 10
  PUB_APPS: 1

tasks:
  default:
    cmds:
      - task -l

  run:workload-gen:
    desc: "Run workload generator"
    cmds:
      - cargo run --release --bin workload-gen -- -s $SUB -p $PUB -i $SUB_APPS -a $SUB_APPS

  run:slim:
    desc: "Run the SLIM server"
    dir: ".."
    cmds:
      - cargo run --release --bin slim -- --config $CONFIG_SERVER

  run:subscribers:
    desc: "Run subscriber applications"
    cmds:
      - |
        for ((i = 0 ; i < $SUB_APPS ; i++ )); do
          cargo run --release --bin subscriber -- -w sub${SUB}_pub${PUB}_i${SUB_APPS}_s${SUB_APPS}.dat -c $CONFIG_CLIENT -i $i &
          sleep 1
        done

  run:publisher:
    desc: "Run publisher application"
    cmds:
      - cargo run --release --bin publisher -- -w sub${SUB}_pub${PUB}_i${SUB_APPS}_s${SUB_APPS}.dat -c $CONFIG_CLIENT -i 0

  run:shutdown:
    desc: "Shutdown test"
    cmds:
      - |
        echo "stop all subscribers"
        killall subscriber || true
        echo "stop all publishers"
        killall publisher || true
        echo "stop slim"
        killall slim || true

  channel-example:moderator:mls:
    desc: "start moderator for test channel"
    cmds:
      - cargo run --release --bin channel -- --config $CONFIG_CLIENT --name org/ns/moderator/1 --is-moderator --participants org/ns/t1 org/ns/t2

  channel-example:participant-1:mls:
    desc: "start participant-1 for test channel"
    cmds:
      - cargo run --release --bin channel -- --config $CONFIG_CLIENT --name org/ns/t1/1 --moderator-name org/ns/moderator/1

  channel-example:participant-2:mls:
    desc: "start participant-2 for test channel"
    cmds:
      - cargo run --release --bin channel -- --config $CONFIG_CLIENT --name org/ns/t2/1 --moderator-name org/ns/moderator/1

  channel-example:moderator:no-mls:
    desc: "start moderator for test channel"
    cmds:
      - cargo run --release --bin channel -- --config $CONFIG_CLIENT --name org/ns/moderator/1 --is-moderator --participants org/ns/t1 org/ns/t2 --mls-disabled

  channel-example:participant-1:no-mls:
    desc: "start participant-1 for test channel"
    cmds:
      - cargo run --release --bin channel -- --config $CONFIG_CLIENT --name org/ns/t1/1 --moderator-name org/ns/moderator/1 --mls-disabled

  channel-example:participant-2:no-mls:
    desc: "start participant-2 for test channel"
    cmds:
      - cargo run --release --bin channel -- --config $CONFIG_CLIENT --name org/ns/t2/1 --moderator-name org/ns/moderator/1 --mls-disabled

  test:group-session:
    desc: "start MLS dynamic group test"
    cmds:
      - |
        cargo run --release --bin test-group
        cargo run --release --bin test-group -- --mls-disabled

  test:point-to-point-session:
    desc: "start test for point to point session"
    cmds:
      - |
        cargo run --release --bin test-p2p -- --mls-disabled
        cargo run --release --bin test-p2p -- --mls-disabled --is-sticky
        cargo run --release --bin test-p2p -- --is-sticky

