import { JsExternal } from 'ffi-rs';
import { type UniffiByteArray } from 'uniffi-bindgen-react-native';
declare class UniffiFfiRsRustCaller {
    rustCall<T>(caller: (status: JsExternal) => T, liftString: (bytes: UniffiByteArray) => string): T;
    rustCallWithError<T, ErrorEnumAndVariant extends [string, string]>(liftError: (buffer: UniffiByteArray) => ErrorEnumAndVariant, caller: (status: JsExternal) => T, liftString: (bytes: UniffiByteArray) => string): T;
    createCallStatus(): [JsExternal];
    createErrorStatus(_code: number, _errorBuf: UniffiByteArray): JsExternal;
    makeRustCall<T, ErrorEnumAndVariant extends [string, string]>(caller: (status: JsExternal) => T, liftString: (bytes: UniffiByteArray) => string, liftError?: (buffer: UniffiByteArray) => ErrorEnumAndVariant): T;
}
export declare const uniffiCaller: UniffiFfiRsRustCaller;
export declare const stringConverter: {
    stringToBytes: (s: string) => NodeJS.NonSharedUint8Array;
    bytesToString: (ab: UniffiByteArray) => string;
    stringByteLength: (s: string) => number;
};
export declare const FfiConverterString: import("uniffi-bindgen-react-native").FfiConverter<UniffiByteArray, string>;
export type UniffiRustBufferStruct = {
    capacity: bigint;
    len: bigint;
    data: JsExternal;
};
export type UniffiForeignBytes = {
    len: number;
    data: JsExternal;
};
/** A UniffiRustBufferValue represents stack allocated structure containing pointer to series of
  * bytes most likely on the heap, along with the size of that data in bytes.
  *
  * It is often used to encode more complex function parameters / return values like structs,
  * optionals, etc.
  *
  * `RustBufferValue`s are behind the scenes backed by manually managed memory on the rust end, and
  * must be explictly destroyed when no longer used to ensure no memory is leaked.
  * */
export declare class UniffiRustBufferValue {
    private struct;
    constructor(struct: UniffiRustBufferStruct);
    static allocateWithBytes(bytes: Uint8Array): UniffiRustBufferValue;
    static allocateEmpty(): UniffiRustBufferValue;
    toStruct(): UniffiRustBufferStruct;
    toUint8Array(): Uint8Array<ArrayBuffer>;
    consumeIntoUint8Array(): Uint8Array<ArrayBuffer>;
    destroy(): void;
}
export type UniffiRustCallStatusStruct = {
    code: number;
    error_buf: UniffiRustBufferStruct;
};
export type UniffiCallbackRustFutureContinuationCallback = (data: bigint, poll_result: number) => void;
export type UniffiCallbackForeignFutureDroppedCallback = (handle: bigint) => void;
export type UniffiCallbackCallbackInterfaceFree = (handle: bigint) => void;
export type UniffiCallbackCallbackInterfaceClone = (handle: bigint) => bigint;
export type UniffiForeignFutureDroppedCallbackStruct = {
    handle: bigint;
    free: JsExternal;
};
export type UniffiForeignFutureResultU8 = {
    returnValue: number;
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteU8 = (callback_data: bigint, result: UniffiForeignFutureResultU8) => void;
export type UniffiForeignFutureResultI8 = {
    returnValue: number;
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteI8 = (callback_data: bigint, result: UniffiForeignFutureResultI8) => void;
export type UniffiForeignFutureResultU16 = {
    returnValue: number;
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteU16 = (callback_data: bigint, result: UniffiForeignFutureResultU16) => void;
export type UniffiForeignFutureResultI16 = {
    returnValue: number;
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteI16 = (callback_data: bigint, result: UniffiForeignFutureResultI16) => void;
export type UniffiForeignFutureResultU32 = {
    returnValue: number;
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteU32 = (callback_data: bigint, result: UniffiForeignFutureResultU32) => void;
export type UniffiForeignFutureResultI32 = {
    returnValue: number;
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteI32 = (callback_data: bigint, result: UniffiForeignFutureResultI32) => void;
export type UniffiForeignFutureResultU64 = {
    returnValue: bigint;
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteU64 = (callback_data: bigint, result: UniffiForeignFutureResultU64) => void;
export type UniffiForeignFutureResultI64 = {
    returnValue: bigint;
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteI64 = (callback_data: bigint, result: UniffiForeignFutureResultI64) => void;
export type UniffiForeignFutureResultF32 = {
    returnValue: number;
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteF32 = (callback_data: bigint, result: UniffiForeignFutureResultF32) => void;
export type UniffiForeignFutureResultF64 = {
    returnValue: number;
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteF64 = (callback_data: bigint, result: UniffiForeignFutureResultF64) => void;
export type UniffiForeignFutureResultRustBuffer = {
    returnValue: UniffiRustBufferStruct;
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteRustBuffer = (callback_data: bigint, result: UniffiForeignFutureResultRustBuffer) => void;
export type UniffiForeignFutureResultVoid = {
    callStatus: JsExternal;
};
export type UniffiCallbackForeignFutureCompleteVoid = (callback_data: bigint, result: UniffiForeignFutureResultVoid) => void;
/** This direct / "extern C" type FFI interface is bound directly to the functions exposed by the
  * dynamic library. Using this manually from end-user javascript code is unsafe and this is not
  * recommended. */
declare const FFI_DYNAMIC_LIB: {
    RustFutureContinuationCallback: (args: [bigint, number]) => void;
    ForeignFutureDroppedCallback: (args: [bigint]) => void;
    CallbackInterfaceFree: (args: [bigint]) => void;
    CallbackInterfaceClone: (args: [bigint]) => bigint;
    ForeignFutureCompleteU8: (args: [bigint, UniffiForeignFutureResultU8]) => void;
    ForeignFutureCompleteI8: (args: [bigint, UniffiForeignFutureResultI8]) => void;
    ForeignFutureCompleteU16: (args: [bigint, UniffiForeignFutureResultU16]) => void;
    ForeignFutureCompleteI16: (args: [bigint, UniffiForeignFutureResultI16]) => void;
    ForeignFutureCompleteU32: (args: [bigint, UniffiForeignFutureResultU32]) => void;
    ForeignFutureCompleteI32: (args: [bigint, UniffiForeignFutureResultI32]) => void;
    ForeignFutureCompleteU64: (args: [bigint, UniffiForeignFutureResultU64]) => void;
    ForeignFutureCompleteI64: (args: [bigint, UniffiForeignFutureResultI64]) => void;
    ForeignFutureCompleteF32: (args: [bigint, UniffiForeignFutureResultF32]) => void;
    ForeignFutureCompleteF64: (args: [bigint, UniffiForeignFutureResultF64]) => void;
    ForeignFutureCompleteRustBuffer: (args: [bigint, UniffiForeignFutureResultRustBuffer]) => void;
    ForeignFutureCompleteVoid: (args: [bigint, UniffiForeignFutureResultVoid]) => void;
    uniffi_slim_bindings_fn_clone_app: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_free_app: (args: [bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_constructor_app_new: (args: [bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_constructor_app_new_with_direction: (args: [bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_constructor_app_new_with_secret: (args: [bigint, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_app_create_session: (args: [bigint, UniffiRustBufferStruct, bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_app_create_session_and_wait: (args: [bigint, UniffiRustBufferStruct, bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_app_create_session_and_wait_async: (args: [bigint, UniffiRustBufferStruct, bigint]) => bigint;
    uniffi_slim_bindings_fn_method_app_create_session_async: (args: [bigint, UniffiRustBufferStruct, bigint]) => bigint;
    uniffi_slim_bindings_fn_method_app_delete_session: (args: [bigint, bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_app_delete_session_and_wait: (args: [bigint, bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_app_delete_session_and_wait_async: (args: [bigint, bigint]) => bigint;
    uniffi_slim_bindings_fn_method_app_delete_session_async: (args: [bigint, bigint]) => bigint;
    uniffi_slim_bindings_fn_method_app_id: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_app_listen_for_session: (args: [bigint, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_app_listen_for_session_async: (args: [bigint, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_app_name: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_app_remove_route: (args: [bigint, bigint, bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_app_remove_route_async: (args: [bigint, bigint, bigint]) => bigint;
    uniffi_slim_bindings_fn_method_app_set_route: (args: [bigint, bigint, bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_app_set_route_async: (args: [bigint, bigint, bigint]) => bigint;
    uniffi_slim_bindings_fn_method_app_subscribe: (args: [bigint, bigint, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_app_subscribe_async: (args: [bigint, bigint, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_app_unsubscribe: (args: [bigint, bigint, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_app_unsubscribe_async: (args: [bigint, bigint, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_clone_completionhandle: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_free_completionhandle: (args: [bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_completionhandle_wait: (args: [bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_completionhandle_wait_async: (args: [bigint]) => bigint;
    uniffi_slim_bindings_fn_method_completionhandle_wait_for: (args: [bigint, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_completionhandle_wait_for_async: (args: [bigint, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_clone_name: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_free_name: (args: [bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_constructor_name_new: (args: [UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_constructor_name_new_with_id: (args: [UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_name_components: (args: [bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_name_id: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_name_uniffi_trait_debug: (args: [bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_name_uniffi_trait_display: (args: [bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_name_uniffi_trait_eq_eq: (args: [bigint, bigint, /* RustCallStatus */ JsExternal]) => number;
    uniffi_slim_bindings_fn_method_name_uniffi_trait_eq_ne: (args: [bigint, bigint, /* RustCallStatus */ JsExternal]) => number;
    uniffi_slim_bindings_fn_clone_service: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_free_service: (args: [bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_constructor_service_new: (args: [UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_constructor_service_new_with_config: (args: [UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_service_config: (args: [bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_service_connect: (args: [bigint, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_service_connect_async: (args: [bigint, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_service_create_app: (args: [bigint, bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_service_create_app_async: (args: [bigint, bigint, UniffiRustBufferStruct, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_service_create_app_with_direction: (args: [bigint, bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_service_create_app_with_direction_async: (args: [bigint, bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_service_create_app_with_secret: (args: [bigint, bigint, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_service_create_app_with_secret_async: (args: [bigint, bigint, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_service_disconnect: (args: [bigint, bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_service_get_connection_id: (args: [bigint, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_service_get_name: (args: [bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_service_run: (args: [bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_service_run_async: (args: [bigint]) => bigint;
    uniffi_slim_bindings_fn_method_service_run_server: (args: [bigint, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_service_run_server_async: (args: [bigint, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_service_shutdown: (args: [bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_service_shutdown_async: (args: [bigint]) => bigint;
    uniffi_slim_bindings_fn_method_service_stop_server: (args: [bigint, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_clone_session: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_free_session: (args: [bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_session_config: (args: [bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_session_destination: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_session_get_message: (args: [bigint, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_session_get_message_async: (args: [bigint, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_session_invite: (args: [bigint, bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_session_invite_and_wait: (args: [bigint, bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_session_invite_and_wait_async: (args: [bigint, bigint]) => bigint;
    uniffi_slim_bindings_fn_method_session_invite_async: (args: [bigint, bigint]) => bigint;
    uniffi_slim_bindings_fn_method_session_is_initiator: (args: [bigint, /* RustCallStatus */ JsExternal]) => number;
    uniffi_slim_bindings_fn_method_session_metadata: (args: [bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_session_participants_list: (args: [bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_session_participants_list_async: (args: [bigint]) => bigint;
    uniffi_slim_bindings_fn_method_session_publish: (args: [bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_session_publish_and_wait: (args: [bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_session_publish_and_wait_async: (args: [bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_session_publish_async: (args: [bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_session_publish_to: (args: [bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_session_publish_to_and_wait: (args: [bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_session_publish_to_and_wait_async: (args: [bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_session_publish_to_async: (args: [bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_session_publish_with_params: (args: [bigint, bigint, number, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_session_publish_with_params_async: (args: [bigint, bigint, number, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct]) => bigint;
    uniffi_slim_bindings_fn_method_session_remove: (args: [bigint, bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_method_session_remove_and_wait: (args: [bigint, bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_method_session_remove_and_wait_async: (args: [bigint, bigint]) => bigint;
    uniffi_slim_bindings_fn_method_session_remove_async: (args: [bigint, bigint]) => bigint;
    uniffi_slim_bindings_fn_method_session_session_id: (args: [bigint, /* RustCallStatus */ JsExternal]) => number;
    uniffi_slim_bindings_fn_method_session_session_type: (args: [bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_method_session_source: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_func_create_service: (args: [UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_func_create_service_with_config: (args: [UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_func_get_build_info: (args: [/* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_get_global_service: (args: [/* RustCallStatus */ JsExternal]) => bigint;
    uniffi_slim_bindings_fn_func_get_services: (args: [/* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_get_version: (args: [/* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_initialize_from_config: (args: [UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_func_initialize_with_configs: (args: [UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_func_initialize_with_defaults: (args: [/* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_fn_func_is_initialized: (args: [/* RustCallStatus */ JsExternal]) => number;
    uniffi_slim_bindings_fn_func_new_dataplane_config: (args: [/* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_new_insecure_client_config: (args: [UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_new_insecure_server_config: (args: [UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_new_runtime_config: (args: [/* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_new_runtime_config_with: (args: [bigint, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_new_server_config: (args: [UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_new_service_config: (args: [/* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_new_service_config_with: (args: [UniffiRustBufferStruct, UniffiRustBufferStruct, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_new_service_configuration: (args: [/* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_new_tracing_config: (args: [/* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_new_tracing_config_with: (args: [UniffiRustBufferStruct, number, number, UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    uniffi_slim_bindings_fn_func_shutdown_blocking: (args: [/* RustCallStatus */ JsExternal]) => void;
    ffi_slim_bindings_rustbuffer_alloc: (args: [bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    ffi_slim_bindings_rustbuffer_from_bytes: (args: [UniffiForeignBytes, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    ffi_slim_bindings_rustbuffer_free: (args: [UniffiRustBufferStruct, /* RustCallStatus */ JsExternal]) => void;
    ffi_slim_bindings_rustbuffer_reserve: (args: [UniffiRustBufferStruct, bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    ffi_slim_bindings_rust_future_poll_u8: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_u8: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_u8: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_u8: (args: [bigint, /* RustCallStatus */ JsExternal]) => number;
    ffi_slim_bindings_rust_future_poll_i8: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_i8: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_i8: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_i8: (args: [bigint, /* RustCallStatus */ JsExternal]) => number;
    ffi_slim_bindings_rust_future_poll_u16: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_u16: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_u16: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_u16: (args: [bigint, /* RustCallStatus */ JsExternal]) => number;
    ffi_slim_bindings_rust_future_poll_i16: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_i16: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_i16: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_i16: (args: [bigint, /* RustCallStatus */ JsExternal]) => number;
    ffi_slim_bindings_rust_future_poll_u32: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_u32: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_u32: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_u32: (args: [bigint, /* RustCallStatus */ JsExternal]) => number;
    ffi_slim_bindings_rust_future_poll_i32: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_i32: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_i32: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_i32: (args: [bigint, /* RustCallStatus */ JsExternal]) => number;
    ffi_slim_bindings_rust_future_poll_u64: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_u64: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_u64: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_u64: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    ffi_slim_bindings_rust_future_poll_i64: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_i64: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_i64: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_i64: (args: [bigint, /* RustCallStatus */ JsExternal]) => bigint;
    ffi_slim_bindings_rust_future_poll_f32: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_f32: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_f32: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_f32: (args: [bigint, /* RustCallStatus */ JsExternal]) => number;
    ffi_slim_bindings_rust_future_poll_f64: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_f64: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_f64: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_f64: (args: [bigint, /* RustCallStatus */ JsExternal]) => number;
    ffi_slim_bindings_rust_future_poll_rust_buffer: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_rust_buffer: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_rust_buffer: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_rust_buffer: (args: [bigint, /* RustCallStatus */ JsExternal]) => UniffiRustBufferStruct;
    ffi_slim_bindings_rust_future_poll_void: (args: [bigint, JsExternal, bigint]) => void;
    ffi_slim_bindings_rust_future_cancel_void: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_free_void: (args: [bigint]) => void;
    ffi_slim_bindings_rust_future_complete_void: (args: [bigint, /* RustCallStatus */ JsExternal]) => void;
    uniffi_slim_bindings_checksum_func_create_service: (args: []) => number;
    uniffi_slim_bindings_checksum_func_create_service_with_config: (args: []) => number;
    uniffi_slim_bindings_checksum_func_get_build_info: (args: []) => number;
    uniffi_slim_bindings_checksum_func_get_global_service: (args: []) => number;
    uniffi_slim_bindings_checksum_func_get_services: (args: []) => number;
    uniffi_slim_bindings_checksum_func_get_version: (args: []) => number;
    uniffi_slim_bindings_checksum_func_initialize_from_config: (args: []) => number;
    uniffi_slim_bindings_checksum_func_initialize_with_configs: (args: []) => number;
    uniffi_slim_bindings_checksum_func_initialize_with_defaults: (args: []) => number;
    uniffi_slim_bindings_checksum_func_is_initialized: (args: []) => number;
    uniffi_slim_bindings_checksum_func_new_dataplane_config: (args: []) => number;
    uniffi_slim_bindings_checksum_func_new_insecure_client_config: (args: []) => number;
    uniffi_slim_bindings_checksum_func_new_insecure_server_config: (args: []) => number;
    uniffi_slim_bindings_checksum_func_new_runtime_config: (args: []) => number;
    uniffi_slim_bindings_checksum_func_new_runtime_config_with: (args: []) => number;
    uniffi_slim_bindings_checksum_func_new_server_config: (args: []) => number;
    uniffi_slim_bindings_checksum_func_new_service_config: (args: []) => number;
    uniffi_slim_bindings_checksum_func_new_service_config_with: (args: []) => number;
    uniffi_slim_bindings_checksum_func_new_service_configuration: (args: []) => number;
    uniffi_slim_bindings_checksum_func_new_tracing_config: (args: []) => number;
    uniffi_slim_bindings_checksum_func_new_tracing_config_with: (args: []) => number;
    uniffi_slim_bindings_checksum_func_shutdown_blocking: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_create_session: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_create_session_and_wait: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_create_session_and_wait_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_create_session_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_delete_session: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_delete_session_and_wait: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_delete_session_and_wait_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_delete_session_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_id: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_listen_for_session: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_listen_for_session_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_name: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_remove_route: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_remove_route_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_set_route: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_set_route_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_subscribe: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_subscribe_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_unsubscribe: (args: []) => number;
    uniffi_slim_bindings_checksum_method_app_unsubscribe_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_completionhandle_wait: (args: []) => number;
    uniffi_slim_bindings_checksum_method_completionhandle_wait_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_completionhandle_wait_for: (args: []) => number;
    uniffi_slim_bindings_checksum_method_completionhandle_wait_for_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_name_components: (args: []) => number;
    uniffi_slim_bindings_checksum_method_name_id: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_config: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_connect: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_connect_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_create_app: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_create_app_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_create_app_with_direction: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_create_app_with_direction_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_create_app_with_secret: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_create_app_with_secret_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_disconnect: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_get_connection_id: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_get_name: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_run: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_run_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_run_server: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_run_server_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_shutdown: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_shutdown_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_service_stop_server: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_config: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_destination: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_get_message: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_get_message_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_invite: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_invite_and_wait: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_invite_and_wait_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_invite_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_is_initiator: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_metadata: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_participants_list: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_participants_list_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_publish: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_publish_and_wait: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_publish_and_wait_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_publish_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_publish_to: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_publish_to_and_wait: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_publish_to_and_wait_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_publish_to_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_publish_with_params: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_publish_with_params_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_remove: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_remove_and_wait: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_remove_and_wait_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_remove_async: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_session_id: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_session_type: (args: []) => number;
    uniffi_slim_bindings_checksum_method_session_source: (args: []) => number;
    uniffi_slim_bindings_checksum_constructor_app_new: (args: []) => number;
    uniffi_slim_bindings_checksum_constructor_app_new_with_direction: (args: []) => number;
    uniffi_slim_bindings_checksum_constructor_app_new_with_secret: (args: []) => number;
    uniffi_slim_bindings_checksum_constructor_name_new: (args: []) => number;
    uniffi_slim_bindings_checksum_constructor_name_new_with_id: (args: []) => number;
    uniffi_slim_bindings_checksum_constructor_service_new: (args: []) => number;
    uniffi_slim_bindings_checksum_constructor_service_new_with_config: (args: []) => number;
    ffi_slim_bindings_uniffi_contract_version: (args: []) => number;
};
export default FFI_DYNAMIC_LIB;
