# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

includes:
  python:
    taskfile: ../../tasks/python.yaml
  tools:
    taskfile: ../../tasks/tools.yaml
    internal: true
    flatten: true

tasks:
  default:
    cmds:
      - task -l

  python:packaging:all:
    desc: "Build and package the Python bindings and examples"
    cmds:
      - mkdir -p ./dist
      - uv build --package slim-bindings-examples
