# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

includes:
  python:
    taskfile: ../../tasks/python.yaml
  tools:
    taskfile: ../../tasks/tools.yaml
    internal: true
  slimrpc:
    taskfile: ./integrations/slimrpc/Taskfile.yaml

tasks:
  default:
    cmds:
      - task -l

  python:packaging:all:
    desc: "Build and package the Python bindings and examples"
    cmds:
      - mkdir -p ./dist
      - uv build --package slim-bindings-examples
      - uv build --package slimrpc

  python:generate-proto:
    desc: "Generate proto files for the Python bindings"
    deps:
      - task: rust:toolchain:run-command
        vars:
          COMMAND: |
            cargo build --package agntcy-protoc-slimrpc-plugin --bin protoc-slimrpc-plugin
      - task: tools:buf
    cmds:
      - |
        # Find all the buf.gen.yaml files in the current directory and its subdirectories
        find . -name 'buf.gen.yaml' | while read -r file; do
          # Generate the proto files using buf
          echo "Generating proto files for $file"
          # get folder name
          folder=$(dirname "$file")
          pushd > /dev/null ${folder} && {{.TOOLS_INSTALL_DIR}}/buf generate && popd > /dev/null
        done
