# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slim.fullname" . }}
  labels:
    {{- include "slim.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.slim.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "slim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "slim.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "slim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}      
      containers:      
       {{- if eq .Values.spire.enabled true }}
        - name: spiffe-helper
          image: {{ .Values.spire.helperImage.repository }}:{{ .Values.spire.helperImage.tag | default "0.10.0" }}
          imagePullPolicy: {{ .Values.spire.helperImage.pullPolicy }}     
          args: [ "-config", "config/helper.conf" ]
          volumeMounts:
            - name: config-volume
              mountPath: /config/helper.conf
              subPath: helper.conf
            - name: spire-agent-socket
              mountPath: /run/spire/agent-sockets
              readOnly: false 
            - name: svids-volume
              mountPath: /svids     
              readOnly: false      
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.slim.image.repository }}:{{ .Values.slim.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.slim.image.pullPolicy }}
          command:
            - "/slim"
          args:
            - "--config"
            - "/config.yaml"
          ports:
            - name: messenger
              containerPort: {{ .Values.slim.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.slim.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /config.yaml
              subPath: config.yaml  
{{- if eq .Values.spire.enabled true }}
            - name: svids-volume
              mountPath: /svids 
              readOnly: false
{{- end }}
{{- with .Values.slim.extraVolumeMounts }}
{{ toYaml . | nindent 12 }}
{{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "slim.fullname" . }}
        {{- with .Values.slim.extraVolumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}      
{{- if eq .Values.spire.enabled true }}
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/agent-sockets
            type: Directory       
        - name: svids-volume
          emptyDir: {}            
{{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
