{{- if .Values.mcpProxy.enabled -}}
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slim.mcpProxyName" . }}
  labels:
    {{- include "slim.mcpProxyLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "slim.mcpProxySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "slim.mcpProxyLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "slim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
       {{- if eq .Values.spire.enabled true }}
        - name: spiffe-helper
          image: {{ .Values.spire.helperImage.repository }}:{{ .Values.spire.helperImage.tag | default "0.10.0" }}
          imagePullPolicy: {{ .Values.spire.helperImage.pullPolicy }}     
          args: [ "-config", "config/helper.conf" ]
          volumeMounts:
            - name: config-volume
              mountPath: /config/helper.conf
              subPath: helper.conf
            - name: spire-agent-socket
              mountPath: /run/spire/agent-sockets
              readOnly: false 
            - name: svids-volume
              mountPath: /svids     
              readOnly: false      
        {{- end }}       
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mcpProxy.image.repository }}:{{ .Values.mcpProxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.mcpProxy.image.pullPolicy }}
          command:
            - "/slim-mcp-proxy"
          args:
            - "--config"
            - "/config.yaml"
            - "--svc-name"
            - {{ .Values.mcpProxy.args.svcName | quote }}
            - "--name"
            - {{ .Values.mcpProxy.args.name | quote }}
            - "--mcp-server"
            - {{ .Values.mcpProxy.args.mcpServer | quote }}
          resources:
            {{- toYaml .Values.mcpProxy.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /config.yaml
              subPath: config.yaml
{{- if eq .Values.spire.enabled true }}
            - name: svids-volume
              mountPath: /svids 
              readOnly: false
{{- end }}              
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "slim.mcpProxyName" . }}
{{- if eq .Values.spire.enabled true }}
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/agent-sockets
            type: Directory       
        - name: svids-volume
          emptyDir: {}            
{{- end}}            
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}