{{/*
Copyright AGNTCY Contributors (https://github.com/agntcy)
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if eq .Values.serviceAccount.create true -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slim.serviceAccountName" . }}
  labels:
    {{- include "slim.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
