# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

"""MkDocs hooks.

- Trust store for urllib (HTTPS includes in mkdocs-include-markdown-plugin).
- Generate ``javascripts/slim-repobeats-data.js`` with GitHub activity metrics
  for the home page RepoBeats-style widget (fetched at build time).
"""
from __future__ import annotations

import json
import logging
import ssl
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import certifi

_REPOBEATS_DATA_FILE = "javascripts/slim-repobeats-data.js"
_REPobeATS_CACHE_FILE = Path(__file__).resolve().parent / ".cache" / "repobeats.json"
_REPobeATS_CACHE_TTL_SECONDS = 45 * 60
_DEFAULT_REPO = "agntcy/slim"

log = logging.getLogger("mkdocs.hooks")


def on_startup(**kwargs):
    """Configure SSL context to use certifi certificates."""
    ssl_context = ssl.create_default_context(cafile=certifi.where())
    https_handler = urllib.request.HTTPSHandler(context=ssl_context)
    opener = urllib.request.build_opener(https_handler)
    urllib.request.install_opener(opener)


def on_pre_build(config, **kwargs):
    """Write GitHub metrics for the home page widget before each build."""
    docs_dir = Path(config.docs_dir)
    output = docs_dir / _REPOBEATS_DATA_FILE
    repo = _default_repo(config)
    embed_id = _repobeats_embed_id(config)
    if embed_id:
        payload: dict[str, Any] = {"repo": repo, "embedId": embed_id}
    else:
        payload = _load_repobeats_payload(repo)
    output.write_text(
        "/* Generated by MkDocs hooks on build — do not edit by hand. */\n"
        "window.__SLIM_REPOBEATS_DATA__ = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )


def _default_repo(config) -> str:
    extra = getattr(config, "extra", None) or {}
    var = extra.get("var") if isinstance(extra.get("var"), dict) else {}
    from_extra = (var.get("repo_slug") or "").strip()
    return from_extra or _DEFAULT_REPO


def _repobeats_embed_id(config) -> str:
    """Optional RepoBeats config ID from MkDocs extra vars or REPOBEATS_EMBED_ID."""
    import os

    extra = getattr(config, "extra", None) or {}
    var = extra.get("var") if isinstance(extra.get("var"), dict) else {}
    from_extra = (var.get("repobeats_embed_id") or "").strip()
    if from_extra:
        return from_extra
    return os.environ.get("REPOBEATS_EMBED_ID", "").strip()


def _load_repobeats_payload(repo: str) -> dict[str, Any]:
    cached = _read_repobeats_cache(repo)
    if cached is not None:
        return cached
    payload = _fetch_repobeats_data(repo)
    _write_repobeats_cache(repo, payload)
    return payload


def _read_repobeats_cache(repo: str) -> dict[str, Any] | None:
    if not _REPobeATS_CACHE_FILE.exists():
        return None
    try:
        cached = json.loads(_REPobeATS_CACHE_FILE.read_text(encoding="utf-8"))
    except (OSError, ValueError, json.JSONDecodeError):
        return None
    if cached.get("repo") != repo:
        return None
    fetched_at = cached.get("fetchedAt")
    if not isinstance(fetched_at, (int, float)):
        return None
    if time.time() - fetched_at > _REPobeATS_CACHE_TTL_SECONDS:
        return None
    data = cached.get("data")
    return data if isinstance(data, dict) else None


def _write_repobeats_cache(repo: str, data: dict[str, Any]) -> None:
    _REPobeATS_CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
    payload = {"repo": repo, "fetchedAt": time.time(), "data": data}
    _REPobeATS_CACHE_FILE.write_text(
        json.dumps(payload, indent=2),
        encoding="utf-8",
    )


def _github_request(url: str) -> Any:
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "agntcy-slim-docs",
        },
    )
    with urllib.request.urlopen(request, timeout=20) as response:
        return json.loads(response.read().decode("utf-8"))


def _search_total(endpoint: str, query: str) -> int:
    params = urllib.parse.urlencode({"q": query, "per_page": "1"})
    url = f"https://api.github.com/search/{endpoint}?{params}"
    try:
        payload = _github_request(url)
    except urllib.error.HTTPError as exc:
        if exc.code in {403, 422}:
            log.warning("GitHub search skipped (%s): %s", exc.code, query)
            return 0
        raise
    except (urllib.error.URLError, TimeoutError, ValueError, json.JSONDecodeError):
        return 0
    return int(payload.get("total_count") or 0)


def _iso_days_ago(days: int) -> str:
    return (datetime.now(UTC).date() - timedelta(days=days)).isoformat()


def _weekly_commit_counts(repo: str, weeks: int = 6) -> list[int]:
    counts: list[int] = []
    for index in range(weeks - 1, -1, -1):
        start = _iso_days_ago((index + 1) * 7)
        end = _iso_days_ago(0 if index == 0 else index * 7)
        query = f"repo:{repo} committer-date:{start}..{end}"
        counts.append(_search_total("commits", query))
        time.sleep(0.4)
    return counts


def _expand_bars(values: list[int], target: int) -> list[int]:
    if not values:
        return [0] * target
    if len(values) >= target:
        return values[-target:]
    expanded: list[int] = []
    repeats = (target + len(values) - 1) // len(values)
    for value in values:
        expanded.extend([value] * repeats)
    return expanded[-target:]


def _fetch_repobeats_data(repo: str) -> dict[str, Any]:
    since = _iso_days_ago(30)

    contributors: list[dict[str, Any]] = []
    try:
        raw_contributors = _github_request(
            f"https://api.github.com/repos/{repo}/contributors?per_page=12"
        )
        if isinstance(raw_contributors, list):
            contributors = [
                {
                    "login": item.get("login", ""),
                    "avatar_url": item.get("avatar_url", ""),
                    "contributions": int(item.get("contributions") or 0),
                }
                for item in raw_contributors
            ]
    except (urllib.error.URLError, TimeoutError, ValueError, json.JSONDecodeError):
        log.warning("Could not fetch GitHub contributors for %s", repo)

    time.sleep(0.4)
    weekly_commits = _weekly_commit_counts(repo, 6)
    commit_bars = _expand_bars(weekly_commits, 12)
    recent_commits = sum(weekly_commits[-5:])

    open_prs = _search_total("issues", f"repo:{repo} is:pr is:open")
    time.sleep(0.4)
    prs_opened = _search_total("issues", f"repo:{repo} is:pr created:>{since}")
    time.sleep(0.4)
    prs_merged = _search_total("issues", f"repo:{repo} is:pr is:merged closed:>{since}")
    time.sleep(0.4)
    issues_opened = _search_total("issues", f"repo:{repo} is:issue created:>{since}")
    time.sleep(0.4)
    issues_closed = _search_total("issues", f"repo:{repo} is:issue closed:>{since}")
    time.sleep(0.4)

    issue_weeks = _expand_bars(weekly_commits[-4:], 4)
    pr_weeks = issue_weeks

    return {
        "repo": repo,
        "recentCommits": recent_commits,
        "commitBars": commit_bars,
        "openPrs": open_prs,
        "prsOpened": prs_opened,
        "prsMerged": prs_merged,
        "issuesOpened": issues_opened,
        "issuesClosed": issues_closed,
        "issueWeeks": issue_weeks,
        "prWeeks": pr_weeks,
        "contributors": contributors,
    }
