# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

tracing:
  log_level: debug
  display_thread_names: true
  display_thread_ids: true

runtime:
  n_cores: 0
  thread_name: "slim-data-plane"
  drain_timeout: 10s

services:
  slim/0:
    dataplane:
      servers:
      - endpoint: "0.0.0.0:46357"
        tls:
          cert_file: "./config/crypto/server-cert.pem"
          key_file: "./config/crypto/server-key.pem"
        auth:
          basic:
            username: username
            password: ${env:PASSWORD}

      clients: []
