apiVersion: v1
kind: ServiceAccount
metadata:
  name: alice
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: alice   
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: alice
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: alice   
spec:
  className: spire-spire
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - alice
  workloadSelectorTemplates:
    - k8s:sa:alice
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/default/sa/alice"
---
apiVersion: v1
kind: Pod
metadata:
  name: alice  
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: alice 
spec:  
  containers:      
  - args:
    - p2p
    - --spire-socket-path
    - unix:/tmp/spire-agent/public/api.sock
    - --spire-jwt-audience
    - slim-demo
    - --local
    - org/ns/alice
    - --slim
    - '{"endpoint":"https://slim.slim.svc.cluster.local:46357","tls":{"source":{"type":"spire","socket_path":"unix:/tmp/spire-agent/public/api.sock"},"ca_source":{"type":"spire","socket_path":"unix:/tmp/spire-agent/public/api.sock","trust_domains":["example.local"]}}}'    
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    image: ghcr.io/agntcy/slim/bindings-examples:0.7.1
    imagePullPolicy: Always
    name: client
    volumeMounts:
    - name: spire-agent-socket
      mountPath: /tmp/spire-agent/public/
      readOnly: true       
  restartPolicy: OnFailure  
  serviceAccountName: alice
  volumes:
  - hostPath:
      path: /run/spire/agent-sockets
      type: Directory
    name: spire-agent-socket
