apiVersion: v1
kind: Pod
metadata:
  name: alice
  namespace: default
spec:
  containers:
  - args:
    - ff
    - --local
    - org/ns/alice
    - --shared-secret
    - secret123
    - --config
    - '{"endpoint":"https://agntcy-slim-1:46357","tls":{"cert_file":"/svids/tls.crt","key_file":"/svids/tls.key","ca_file":"/svids/svid_bundle.pem"}}'
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    image: ghcr.io/agntcy/slim/bindings-examples:latest
    imagePullPolicy: Always
    name: alice
    volumeMounts:
    - mountPath: /svids
      name: svids-volume
  initContainers:
  - args:
    - -config
    - config/helper.conf
    image: ghcr.io/spiffe/spiffe-helper:0.10.0
    imagePullPolicy: IfNotPresent
    name: spiffe-helper
    resources: {}
    volumeMounts:
    - mountPath: /config/helper.conf
      name: config-volume
      subPath: helper.conf
    - mountPath: /run/spire/agent-sockets
      name: spire-agent-socket
    - mountPath: /svids
      name: svids-volume
  restartPolicy: OnFailure
  serviceAccount: default
  serviceAccountName: default
  volumes:
  - hostPath:
      path: /run/spire/agent-sockets
      type: Directory
    name: spire-agent-socket
  - emptyDir: {}
    name: svids-volume
  - configMap:
      defaultMode: 420
      name: alice
    name: config-volume
