apiVersion: v1
kind: Pod
metadata:
  name: bob
  namespace: default
spec:
  containers:
  - args:
    - anycast
    - --message
    - hello
    - --iterations
    - "10"
    - --local
    - org/ns/bob
    - --remote
    - org/ns/alice
    - --shared-secret
    - secret123
    - --slim
    - '{"endpoint":"https://slim.slim.svc.cluster.local:46357","tls":{"insecure_skip_verify": false, "cert_file":"/svids/tls.crt","key_file":"/svids/tls.key","ca_file":"/svids/svid_bundle.pem"}}'
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    image: ghcr.io/agntcy/slim/bindings-examples:0.6.0-dev.3
    imagePullPolicy: Always
    name: alice
    volumeMounts:
    - mountPath: /svids
      name: svids-volume
  initContainers:
  - args:
    - -config
    - config/helper.conf
    image: ghcr.io/spiffe/spiffe-helper:0.10.0
    imagePullPolicy: IfNotPresent
    name: spiffe-helper
    resources: {}
    volumeMounts:
    - mountPath: /config/helper.conf
      name: config-volume
      subPath: helper.conf
    - mountPath: /run/spire/agent-sockets
      name: spire-agent-socket
    - mountPath: /svids
      name: svids-volume
  restartPolicy: OnFailure
  serviceAccount: default
  serviceAccountName: default
  volumes:
  - hostPath:
      path: /run/spire/agent-sockets
      type: Directory
    name: spire-agent-socket
  - emptyDir: {}
    name: svids-volume
  - configMap:
      defaultMode: 420
      name: helper-config
    name: config-volume
