apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: bob     
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: bob
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: bob     
spec:
  className: spire-spire
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - bob
  workloadSelectorTemplates:
    - k8s:sa:bob
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/default/sa/bob"
  federatesWith:
    - cluster-a.example
---
apiVersion: v1
kind: Pod
metadata:
  name: bob
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: bob     
spec:
  serviceAccountName: bob
  containers:         
  - args:
    - p2p
    - --message
    - hello
    - --iterations
    - "10"
    - --local
    - org/ns/bob
    - --remote
    - org/ns/alice
    - --spire-socket-path
    - unix:/tmp/spire-agent/public/api.sock
    - --spire-jwt-audience
    - slim-demo
    - --enable-mls
    - --slim
    - '{"endpoint":"https://slim.slim.svc.cluster.local:46357","tls":{"source":{"type":"spire","socket_path":"unix:/tmp/spire-agent/public/api.sock"},"ca_source":{"type":"spire","socket_path":"unix:/tmp/spire-agent/public/api.sock","trust_domains":["cluster-b.example"]}}}'    
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    image: ghcr.io/agntcy/slim/bindings-examples:0.7.0
    imagePullPolicy: Always
    name: client
    volumeMounts:
    - name: spire-agent-socket
      mountPath: /tmp/spire-agent/public/
      readOnly: true
  restartPolicy: OnFailure
  serviceAccountName: bob
  volumes:
  - hostPath:
      path: /run/spire/agent-sockets
      type: Directory
    name: spire-agent-socket
