apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: bob     
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: bob
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: bob     
spec:
  className: spire-spire
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - bob
  workloadSelectorTemplates:
    - k8s:sa:bob
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/default/sa/bob"
  federatesWith:
    - cluster-a.example
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bob-spiffe-config
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: bob
data:
  helper.conf: |-
    agent_address =  "/run/spire/agent-sockets/api.sock"
    cmd = ""
    cmd_args = ""
    cert_dir = "/svids"
    renew_signal = ""
    svid_file_name = "tls.crt"
    svid_key_file_name = "tls.key"
    svid_bundle_file_name = "svid_bundle.pem"
    jwt_bundle_file_name = "key.jwt"
    cert_file_mode = 0644
    key_file_mode = 0644
    jwt_svid_file_mode = 0644
    jwt_bundle_file_mode = 0644
    jwt_svids = [{jwt_audience="slim-demo", jwt_svid_file_name="jwt_svid.token"}]
    daemon_mode = true
---
apiVersion: v1
kind: Pod
metadata:
  name: bob
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: bob     
spec:
  serviceAccountName: bob
  containers:
  - args:
    - -config
    - config/helper.conf
    image: ghcr.io/spiffe/spiffe-helper:0.10.0
    imagePullPolicy: IfNotPresent
    name: spiffe-helper
    resources: {}
    volumeMounts:
    - mountPath: /config/helper.conf
      name: config-volume
      subPath: helper.conf
    - mountPath: /run/spire/agent-sockets
      name: spire-agent-socket
    - mountPath: /svids
      name: svids-volume          
  - args:
    - unicast
    - --message
    - hello
    - --iterations
    - "10"
    - --local
    - org/ns/bob
    - --remote
    - org/ns/alice
    - --jwt
    - /svids/jwt_svid.token
    - --spire-trust-bundle
    - /svids/key.jwt
    - --audience
    - slim-demo
    - --enable-mls
    - --slim
    - '{"endpoint":"https://slim.slim.svc.cluster.local:46357","tls":{"insecure_skip_verify": false, "cert_file":"/svids/tls.crt","key_file":"/svids/tls.key","ca_file":"/svids/svid_bundle.pem"}}'
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    image: ghcr.io/agntcy/slim/bindings-examples:0.6.0-dev.4
    imagePullPolicy: Always
    name: client
    volumeMounts:
    - mountPath: /svids
      name: svids-volume
  restartPolicy: OnFailure
  serviceAccountName: bob
  volumes:
  - hostPath:
      path: /run/spire/agent-sockets
      type: Directory
    name: spire-agent-socket
  - emptyDir: {}
    name: svids-volume
  - configMap:
      defaultMode: 420
      name: bob-spiffe-config
    name: config-volume
