// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package objectbox

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type nodeEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var NodeEntityBinding = nodeEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 2792651086841387748,
}

// NodeEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var NodeEntity_ = struct {
	Id          *objectbox.PropertyUint64
	NodeID      *objectbox.PropertyString
	GroupName   *objectbox.PropertyString
	ConnDetails *objectbox.PropertyString
	LastUpdated *objectbox.PropertyInt64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	NodeID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	GroupName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	ConnDetails: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	LastUpdated: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &NodeEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (nodeEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (nodeEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("NodeEntity", 1, 2792651086841387748)
	model.Property("Id", 6, 1, 1580336837220168436)
	model.PropertyFlags(1)
	model.Property("NodeID", 9, 2, 2385929680837930931)
	model.PropertyFlags(2080)
	model.PropertyIndex(1, 5348801088592947243)
	model.Property("GroupName", 9, 3, 5683598783254344800)
	model.Property("ConnDetails", 9, 4, 8492523172653333717)
	model.Property("LastUpdated", 6, 5, 8394852351442290764)
	model.EntityLastPropertyId(5, 8394852351442290764)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (nodeEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*NodeEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (nodeEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*NodeEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (nodeEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (nodeEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*NodeEntity)
	var offsetNodeID = fbutils.CreateStringOffset(fbb, obj.NodeID)
	var offsetGroupName = fbutils.CreateStringOffset(fbb, obj.GroupName)
	var offsetConnDetails = fbutils.CreateStringOffset(fbb, obj.ConnDetails)

	// build the FlatBuffers object
	fbb.StartObject(5)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetNodeID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetGroupName)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetConnDetails)
	fbutils.SetInt64Slot(fbb, 4, obj.LastUpdated)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (nodeEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'NodeEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &NodeEntity{
		Id:          propId,
		NodeID:      fbutils.GetStringSlot(table, 6),
		GroupName:   fbutils.GetStringSlot(table, 8),
		ConnDetails: fbutils.GetStringSlot(table, 10),
		LastUpdated: fbutils.GetInt64Slot(table, 12),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (nodeEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*NodeEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (nodeEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*NodeEntity), nil)
	}
	return append(slice.([]*NodeEntity), object.(*NodeEntity))
}

// Box provides CRUD access to NodeEntity objects
type NodeEntityBox struct {
	*objectbox.Box
}

// BoxForNodeEntity opens a box of NodeEntity objects
func BoxForNodeEntity(ob *objectbox.ObjectBox) *NodeEntityBox {
	return &NodeEntityBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the NodeEntity.Id property on the passed object will be assigned the new ID as well.
func (box *NodeEntityBox) Put(object *NodeEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the NodeEntity.Id property on the passed object will be assigned the new ID as well.
func (box *NodeEntityBox) Insert(object *NodeEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *NodeEntityBox) Update(object *NodeEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *NodeEntityBox) PutAsync(object *NodeEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the NodeEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the NodeEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *NodeEntityBox) PutMany(objects []*NodeEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *NodeEntityBox) Get(id uint64) (*NodeEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*NodeEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *NodeEntityBox) GetMany(ids ...uint64) ([]*NodeEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*NodeEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *NodeEntityBox) GetManyExisting(ids ...uint64) ([]*NodeEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*NodeEntity), nil
}

// GetAll reads all stored objects
func (box *NodeEntityBox) GetAll() ([]*NodeEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*NodeEntity), nil
}

// Remove deletes a single object
func (box *NodeEntityBox) Remove(object *NodeEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *NodeEntityBox) RemoveMany(objects ...*NodeEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the NodeEntity_ struct to create conditions.
// Keep the *NodeEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *NodeEntityBox) Query(conditions ...objectbox.Condition) *NodeEntityQuery {
	return &NodeEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the NodeEntity_ struct to create conditions.
// Keep the *NodeEntityQuery if you intend to execute the query multiple times.
func (box *NodeEntityBox) QueryOrError(conditions ...objectbox.Condition) (*NodeEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &NodeEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See NodeEntityAsyncBox for more information.
func (box *NodeEntityBox) Async() *NodeEntityAsyncBox {
	return &NodeEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// NodeEntityAsyncBox provides asynchronous operations on NodeEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type NodeEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForNodeEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use NodeEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForNodeEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *NodeEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &NodeEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *NodeEntityAsyncBox) Put(object *NodeEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *NodeEntityAsyncBox) Insert(object *NodeEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *NodeEntityAsyncBox) Update(object *NodeEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *NodeEntityAsyncBox) Remove(object *NodeEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all NodeEntity which Id is either 42 or 47:
//
// box.Query(NodeEntity_.Id.In(42, 47)).Find()
type NodeEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *NodeEntityQuery) Find() ([]*NodeEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*NodeEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *NodeEntityQuery) Offset(offset uint64) *NodeEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *NodeEntityQuery) Limit(limit uint64) *NodeEntityQuery {
	query.Query.Limit(limit)
	return query
}

type routeEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var RouteEntityBinding = routeEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 2,
	},
	Uid: 8025942386521378814,
}

// RouteEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var RouteEntity_ = struct {
	Id             *objectbox.PropertyUint64
	RouteID        *objectbox.PropertyString
	SourceNodeID   *objectbox.PropertyString
	DestNodeID     *objectbox.PropertyString
	DestEndpoint   *objectbox.PropertyString
	ConnConfigData *objectbox.PropertyString
	Component0     *objectbox.PropertyString
	Component1     *objectbox.PropertyString
	Component2     *objectbox.PropertyString
	ComponentID    *objectbox.PropertyUint64
	HasComponentID *objectbox.PropertyBool
	Status         *objectbox.PropertyInt
	StatusMsg      *objectbox.PropertyString
	Deleted        *objectbox.PropertyBool
	LastUpdated    *objectbox.PropertyInt64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	RouteID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	SourceNodeID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	DestNodeID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	DestEndpoint: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	ConnConfigData: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	Component0: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	Component1: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	Component2: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	ComponentID: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	HasComponentID: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     11,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	Status: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     12,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	StatusMsg: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     13,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	Deleted: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     14,
			Entity: &RouteEntityBinding.Entity,
		},
	},
	LastUpdated: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     15,
			Entity: &RouteEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (routeEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (routeEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("RouteEntity", 2, 8025942386521378814)
	model.Property("Id", 6, 1, 566457905021413900)
	model.PropertyFlags(1)
	model.Property("RouteID", 9, 2, 5554414035527373395)
	model.PropertyFlags(2080)
	model.PropertyIndex(2, 1113185701350775528)
	model.Property("SourceNodeID", 9, 3, 7748903037239364274)
	model.PropertyFlags(2048)
	model.PropertyIndex(3, 5899322149723026848)
	model.Property("DestNodeID", 9, 4, 6626436553446245957)
	model.PropertyFlags(2048)
	model.PropertyIndex(4, 1346941228755011668)
	model.Property("DestEndpoint", 9, 5, 355551745912170104)
	model.PropertyFlags(2048)
	model.PropertyIndex(5, 6261784079211242742)
	model.Property("ConnConfigData", 9, 6, 7370354698813327691)
	model.Property("Component0", 9, 7, 6894079634672535263)
	model.Property("Component1", 9, 8, 665150575351312567)
	model.Property("Component2", 9, 9, 3477097287044552605)
	model.Property("ComponentID", 6, 10, 1241360834894830306)
	model.PropertyFlags(8192)
	model.Property("HasComponentID", 1, 11, 7476091948321448021)
	model.Property("Status", 6, 12, 4016151492872340074)
	model.Property("StatusMsg", 9, 13, 3886248145022450611)
	model.Property("Deleted", 1, 14, 8266734558067358534)
	model.Property("LastUpdated", 6, 15, 3237939283044381598)
	model.EntityLastPropertyId(15, 3237939283044381598)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (routeEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*RouteEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (routeEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*RouteEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (routeEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (routeEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*RouteEntity)
	var offsetRouteID = fbutils.CreateStringOffset(fbb, obj.RouteID)
	var offsetSourceNodeID = fbutils.CreateStringOffset(fbb, obj.SourceNodeID)
	var offsetDestNodeID = fbutils.CreateStringOffset(fbb, obj.DestNodeID)
	var offsetDestEndpoint = fbutils.CreateStringOffset(fbb, obj.DestEndpoint)
	var offsetConnConfigData = fbutils.CreateStringOffset(fbb, obj.ConnConfigData)
	var offsetComponent0 = fbutils.CreateStringOffset(fbb, obj.Component0)
	var offsetComponent1 = fbutils.CreateStringOffset(fbb, obj.Component1)
	var offsetComponent2 = fbutils.CreateStringOffset(fbb, obj.Component2)
	var offsetStatusMsg = fbutils.CreateStringOffset(fbb, obj.StatusMsg)

	// build the FlatBuffers object
	fbb.StartObject(15)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetRouteID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetSourceNodeID)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetDestNodeID)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetDestEndpoint)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetConnConfigData)
	fbutils.SetUOffsetTSlot(fbb, 6, offsetComponent0)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetComponent1)
	fbutils.SetUOffsetTSlot(fbb, 8, offsetComponent2)
	fbutils.SetUint64Slot(fbb, 9, obj.ComponentID)
	fbutils.SetBoolSlot(fbb, 10, obj.HasComponentID)
	fbutils.SetInt64Slot(fbb, 11, int64(obj.Status))
	fbutils.SetUOffsetTSlot(fbb, 12, offsetStatusMsg)
	fbutils.SetBoolSlot(fbb, 13, obj.Deleted)
	fbutils.SetInt64Slot(fbb, 14, obj.LastUpdated)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (routeEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'RouteEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &RouteEntity{
		Id:             propId,
		RouteID:        fbutils.GetStringSlot(table, 6),
		SourceNodeID:   fbutils.GetStringSlot(table, 8),
		DestNodeID:     fbutils.GetStringSlot(table, 10),
		DestEndpoint:   fbutils.GetStringSlot(table, 12),
		ConnConfigData: fbutils.GetStringSlot(table, 14),
		Component0:     fbutils.GetStringSlot(table, 16),
		Component1:     fbutils.GetStringSlot(table, 18),
		Component2:     fbutils.GetStringSlot(table, 20),
		ComponentID:    fbutils.GetUint64Slot(table, 22),
		HasComponentID: fbutils.GetBoolSlot(table, 24),
		Status:         fbutils.GetIntSlot(table, 26),
		StatusMsg:      fbutils.GetStringSlot(table, 28),
		Deleted:        fbutils.GetBoolSlot(table, 30),
		LastUpdated:    fbutils.GetInt64Slot(table, 32),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (routeEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*RouteEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (routeEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*RouteEntity), nil)
	}
	return append(slice.([]*RouteEntity), object.(*RouteEntity))
}

// Box provides CRUD access to RouteEntity objects
type RouteEntityBox struct {
	*objectbox.Box
}

// BoxForRouteEntity opens a box of RouteEntity objects
func BoxForRouteEntity(ob *objectbox.ObjectBox) *RouteEntityBox {
	return &RouteEntityBox{
		Box: ob.InternalBox(2),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the RouteEntity.Id property on the passed object will be assigned the new ID as well.
func (box *RouteEntityBox) Put(object *RouteEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the RouteEntity.Id property on the passed object will be assigned the new ID as well.
func (box *RouteEntityBox) Insert(object *RouteEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *RouteEntityBox) Update(object *RouteEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *RouteEntityBox) PutAsync(object *RouteEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the RouteEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the RouteEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *RouteEntityBox) PutMany(objects []*RouteEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *RouteEntityBox) Get(id uint64) (*RouteEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*RouteEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *RouteEntityBox) GetMany(ids ...uint64) ([]*RouteEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*RouteEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *RouteEntityBox) GetManyExisting(ids ...uint64) ([]*RouteEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*RouteEntity), nil
}

// GetAll reads all stored objects
func (box *RouteEntityBox) GetAll() ([]*RouteEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*RouteEntity), nil
}

// Remove deletes a single object
func (box *RouteEntityBox) Remove(object *RouteEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *RouteEntityBox) RemoveMany(objects ...*RouteEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the RouteEntity_ struct to create conditions.
// Keep the *RouteEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *RouteEntityBox) Query(conditions ...objectbox.Condition) *RouteEntityQuery {
	return &RouteEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the RouteEntity_ struct to create conditions.
// Keep the *RouteEntityQuery if you intend to execute the query multiple times.
func (box *RouteEntityBox) QueryOrError(conditions ...objectbox.Condition) (*RouteEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &RouteEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See RouteEntityAsyncBox for more information.
func (box *RouteEntityBox) Async() *RouteEntityAsyncBox {
	return &RouteEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// RouteEntityAsyncBox provides asynchronous operations on RouteEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type RouteEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForRouteEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use RouteEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForRouteEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *RouteEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 2, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 2: %s" + err.Error())
	}
	return &RouteEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *RouteEntityAsyncBox) Put(object *RouteEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *RouteEntityAsyncBox) Insert(object *RouteEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *RouteEntityAsyncBox) Update(object *RouteEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *RouteEntityAsyncBox) Remove(object *RouteEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all RouteEntity which Id is either 42 or 47:
//
// box.Query(RouteEntity_.Id.In(42, 47)).Find()
type RouteEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *RouteEntityQuery) Find() ([]*RouteEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*RouteEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *RouteEntityQuery) Offset(offset uint64) *RouteEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *RouteEntityQuery) Limit(limit uint64) *RouteEntityQuery {
	query.Query.Limit(limit)
	return query
}

type channelEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var ChannelEntityBinding = channelEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 3,
	},
	Uid: 8991150634135627712,
}

// ChannelEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var ChannelEntity_ = struct {
	Id           *objectbox.PropertyUint64
	ChannelID    *objectbox.PropertyString
	Moderators   *objectbox.PropertyString
	Participants *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &ChannelEntityBinding.Entity,
		},
	},
	ChannelID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &ChannelEntityBinding.Entity,
		},
	},
	Moderators: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &ChannelEntityBinding.Entity,
		},
	},
	Participants: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &ChannelEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (channelEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (channelEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("ChannelEntity", 3, 8991150634135627712)
	model.Property("Id", 6, 1, 3627667097600927234)
	model.PropertyFlags(1)
	model.Property("ChannelID", 9, 2, 5076872574005507064)
	model.PropertyFlags(2080)
	model.PropertyIndex(6, 482193135239913214)
	model.Property("Moderators", 9, 3, 413362110142970815)
	model.Property("Participants", 9, 4, 4893088794221328790)
	model.EntityLastPropertyId(4, 4893088794221328790)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (channelEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*ChannelEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (channelEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*ChannelEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (channelEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (channelEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*ChannelEntity)
	var offsetChannelID = fbutils.CreateStringOffset(fbb, obj.ChannelID)
	var offsetModerators = fbutils.CreateStringOffset(fbb, obj.Moderators)
	var offsetParticipants = fbutils.CreateStringOffset(fbb, obj.Participants)

	// build the FlatBuffers object
	fbb.StartObject(4)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetChannelID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetModerators)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetParticipants)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (channelEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'ChannelEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &ChannelEntity{
		Id:           propId,
		ChannelID:    fbutils.GetStringSlot(table, 6),
		Moderators:   fbutils.GetStringSlot(table, 8),
		Participants: fbutils.GetStringSlot(table, 10),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (channelEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*ChannelEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (channelEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*ChannelEntity), nil)
	}
	return append(slice.([]*ChannelEntity), object.(*ChannelEntity))
}

// Box provides CRUD access to ChannelEntity objects
type ChannelEntityBox struct {
	*objectbox.Box
}

// BoxForChannelEntity opens a box of ChannelEntity objects
func BoxForChannelEntity(ob *objectbox.ObjectBox) *ChannelEntityBox {
	return &ChannelEntityBox{
		Box: ob.InternalBox(3),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the ChannelEntity.Id property on the passed object will be assigned the new ID as well.
func (box *ChannelEntityBox) Put(object *ChannelEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the ChannelEntity.Id property on the passed object will be assigned the new ID as well.
func (box *ChannelEntityBox) Insert(object *ChannelEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *ChannelEntityBox) Update(object *ChannelEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *ChannelEntityBox) PutAsync(object *ChannelEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the ChannelEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the ChannelEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *ChannelEntityBox) PutMany(objects []*ChannelEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *ChannelEntityBox) Get(id uint64) (*ChannelEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*ChannelEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *ChannelEntityBox) GetMany(ids ...uint64) ([]*ChannelEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*ChannelEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *ChannelEntityBox) GetManyExisting(ids ...uint64) ([]*ChannelEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*ChannelEntity), nil
}

// GetAll reads all stored objects
func (box *ChannelEntityBox) GetAll() ([]*ChannelEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*ChannelEntity), nil
}

// Remove deletes a single object
func (box *ChannelEntityBox) Remove(object *ChannelEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *ChannelEntityBox) RemoveMany(objects ...*ChannelEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the ChannelEntity_ struct to create conditions.
// Keep the *ChannelEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *ChannelEntityBox) Query(conditions ...objectbox.Condition) *ChannelEntityQuery {
	return &ChannelEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the ChannelEntity_ struct to create conditions.
// Keep the *ChannelEntityQuery if you intend to execute the query multiple times.
func (box *ChannelEntityBox) QueryOrError(conditions ...objectbox.Condition) (*ChannelEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &ChannelEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See ChannelEntityAsyncBox for more information.
func (box *ChannelEntityBox) Async() *ChannelEntityAsyncBox {
	return &ChannelEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// ChannelEntityAsyncBox provides asynchronous operations on ChannelEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type ChannelEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForChannelEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use ChannelEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForChannelEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *ChannelEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 3, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 3: %s" + err.Error())
	}
	return &ChannelEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *ChannelEntityAsyncBox) Put(object *ChannelEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *ChannelEntityAsyncBox) Insert(object *ChannelEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *ChannelEntityAsyncBox) Update(object *ChannelEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *ChannelEntityAsyncBox) Remove(object *ChannelEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all ChannelEntity which Id is either 42 or 47:
//
// box.Query(ChannelEntity_.Id.In(42, 47)).Find()
type ChannelEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *ChannelEntityQuery) Find() ([]*ChannelEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*ChannelEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *ChannelEntityQuery) Offset(offset uint64) *ChannelEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *ChannelEntityQuery) Limit(limit uint64) *ChannelEntityQuery {
	query.Query.Limit(limit)
	return query
}
