// Code generated by ObjectBox; DO NOT EDIT.

package objectbox

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(NodeEntityBinding)
	model.RegisterBinding(RouteEntityBinding)
	model.RegisterBinding(ChannelEntityBinding)
	model.LastEntityId(3, 8991150634135627712)
	model.LastIndexId(6, 482193135239913214)

	return model
}
