# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: "3"

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

includes:
  rust:
    taskfile: ../../../tasks/rust.yaml
    internal: true

tasks:
  python:bindings:lint:
    desc: "Lint the Python bindings"
    cmds:
      - uv run ruff check
      - uv run ruff format --check
      - uv run mypy --ignore-missing-imports --explicit-package-bases .

  python:bindings:build:
    desc: "Build the Python bindings"
    vars:
      PROFILE: '{{.PROFILE | default "debug"}}'
      RELEASE:
        sh: '[[ {{.PROFILE}} == "release" ]] && echo "--release" || echo ""'
    cmds:
      - task: rust:toolchain:run-command
        vars:
          COMMAND: |
            uv run maturin develop --uv {{.RELEASE}}

  python:bindings:test:
    desc: "Test the Python bindings"
    deps:
      - python:bindings:build
    cmds:
      - uv run pytest -s {{.TESTS}}
    vars:
      TARGET: '{{.TESTS | default ""}}'

  python:bindings:test:coverage:
    desc: "Test the Python bindings with coverage"
    deps:
      - python:bindings:build
    cmds:
      - uv run pytest --cov=slim_bindings --cov-report=lcov:coverage.lcov --cov-report=html --cov-report=term -s {{.TESTS}}
    vars:
      TARGET: '{{.TESTS | default ""}}'

  python:bindings:packaging:
    desc: "Generate the Python bindings for python versions 3.10, 3.11, 3.12, 3.13"
    vars:
      PROFILE: '{{.PROFILE | default "debug"}}'
      RELEASE:
        sh: '[[ {{.PROFILE}} == "release" ]] && echo "--release" || echo ""'
      _TARGET:
        sh: 'rustc -vV | grep "host: " | cut -d" " -f2'
      TARGET: '{{.TARGET | default ._TARGET}}'
      ARCH:
        sh: 'echo {{.TARGET}} | cut -d"-" -f1'
      OS:
        sh: 'echo {{.TARGET}} | cut -d"-" -f3'
      C_LIB:
        sh: 'echo {{.TARGET}} | cut -d"-" -f4 || echo ""'
      INTERPRETERS: '{{.INTERPRETERS | default "3.10 3.11 3.12 3.13 3.14"}}'
    cmds:
      - uv python install {{.INTERPRETERS}}
      - task: rust:toolchain:run-command
        vars:
          COMMAND: |
            rustup target add {{.TARGET}}

            UV_ARGS=(
              --no-default-groups
              --group building
            )

            MATURIN_ARGS=(
              {{.RELEASE}}
              --out dist
              --target {{.TARGET}}
              --frozen
              -i {{.INTERPRETERS}}
            )

            if [[ "{{.C_LIB}}" = "gnu" ]]; then
              MATURIN_ARGS+=(
                --compatibility manylinux_2_28
                --zig
              )
            elif [[ "{{.C_LIB}}" = "musl" ]]; then
              MATURIN_ARGS+=(
                --compatibility musllinux_1_2
                --zig
              )
            fi
            
            # Workaround for windows
            if [[ "{{.OS}}" = "windows" ]]; then
              uv sync ${UV_ARGS[@]}
              uv run ${UV_ARGS[@]} maturin develop --uv {{.RELEASE}}
              
              # This file if a leftover from the previous build, delete it otherwise
              # maturin will try to add it to the wheel, and it will fail
              rm -f slim_bindings/*.pyd
            fi

            echo "Running maturin with the following args: ${MATURIN_ARGS[@]}"

            uv run                            \
              ${UV_ARGS[@]}                   \
              maturin build                   \
              ${MATURIN_ARGS[@]}

  python:bindings:generate-stub:
    desc: "Generate stub file for the Python bindings"
    cmds:
      - cmd: |
          export PYTHONHOME="$(dirname $(dirname $(realpath $(which .venv/bin/python))))"
          uv run cargo run --bin stub_gen
