// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Generated by build.rs from migrations/. Do not edit manually.
include!(concat!(env!("OUT_DIR"), "/schema.rs"));
