# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

vars:
  # The Rust UniFFI bindings crate - in bindings/adapter (sibling to bindings/go)
  BINDINGS_DIR: "{{.TASKFILE_DIR}}../adapter"
  SERVICE_TARGET: "{{.TASKFILE_DIR}}/../../target/release"
  LIB_NAME: slim_bindings
  _DEFAULT_LIB_PATH: "{{.SERVICE_TARGET}}/lib{{.LIB_NAME}}.a"
  LIB_PATH: "{{.LIB_PATH | default ._DEFAULT_LIB_PATH}}"

tasks:
  default:
    cmds:
      - task -l

  rust-build:
    desc: Build the Rust library with UniFFI (release mode)
    dir: "{{.BINDINGS_DIR}}"
    cmds:
      - echo "ðŸ¦€ Building Rust bindings library with UniFFI (release mode)..."
      - cargo build --release
    silent: true

  ensure-lib:
    desc: Ensure the UniFFI library is built
    cmds:
      - |
        if [ ! -f "{{.LIB_PATH}}" ]; then
          echo "âš ï¸  UniFFI library not found, building now..."
          task rust-build
        else
          echo "âœ… Found UniFFI library: {{.LIB_PATH}}"
        fi
    silent: true

  patch-cgo-directives:
    desc: Patch generated Go bindings with proper cgo directives
    internal: true
    cmds:
      - echo "ðŸ”§ Patching cgo directives..."
      - |
        GO_FILE="generated/{{.LIB_NAME}}/{{.LIB_NAME}}.go"
        if [ -f "$GO_FILE" ]; then
          # Create the new cgo preamble
          cat > /tmp/cgo_preamble.txt << 'EOF'
        package slim_bindings

        /*
        #cgo CFLAGS: -I${SRCDIR}
        #cgo linux,amd64 LDFLAGS: ${SRCDIR}/libslim_bindings_x86_64_linux_gnu.a -lm
        #cgo linux,arm64 LDFLAGS: ${SRCDIR}/libslim_bindings_aarch64_linux_gnu.a -lm
        #cgo darwin,amd64 LDFLAGS: ${SRCDIR}/libslim_bindings_x86_64_darwin.a -Wl,-undefined,dynamic_lookup
        #cgo darwin,arm64 LDFLAGS: ${SRCDIR}/libslim_bindings_aarch64_darwin.a -Wl,-undefined,dynamic_lookup
        #include <slim_bindings.h>
        */
        import "C"
        EOF

          # Extract the rest of the file after 'import "C"'
          sed -n '/^import "C"/,$p' "$GO_FILE" | tail -n +2 > /tmp/go_rest.txt

          # Combine the new preamble with the rest of the file
          cat /tmp/cgo_preamble.txt /tmp/go_rest.txt > "$GO_FILE"

          # Cleanup
          rm -f /tmp/cgo_preamble.txt /tmp/go_rest.txt
          echo "âœ… Patched $GO_FILE with cgo directives"
        else
          echo "âš ï¸  Go file not found: $GO_FILE"
          exit 1
        fi
    silent: true

  copy-library:
    desc: Copy shared library to generated directory
    internal: true
    cmds:
      - echo "ðŸ“¦ Copying static libraries..."
      - find $(dirname {{.LIB_PATH}}) -type f -name "*{{.LIB_NAME}}*.a" -exec cp {} "generated/{{.LIB_NAME}}/" \;
      - echo "âœ… Libraries copied to generated/{{.LIB_NAME}}/"
    silent: true

  generate:
    desc: Generate Go bindings from compiled library
    deps: [ensure-lib]
    cmds:
      - echo "ðŸ”§ Generating Go bindings from compiled library..."
      - |
        uniffi-bindgen-go \
          --library '{{.LIB_PATH}}' \
          --out-dir generated
      - cd generated && go mod init github.com/agntcy/slim/bindings/generated 2>/dev/null || true
      - task: patch-cgo-directives
      - task: copy-library
      - echo "âœ… Bindings generated in generated/"
    silent: true

  install-uniffi-bindgen-go:
    desc: Install uniffi-bindgen-go
    cmds:
      - cargo install uniffi-bindgen-go --git https://github.com/NordSecurity/uniffi-bindgen-go.git --tag v0.4.0+v0.28.3 --config net.git-fetch-with-cli=true

  test:
    desc: Run all tests
    deps: [ensure-lib]
    cmds:
      - echo "ðŸ§ª Running all tests..."
      - go test -v ./...
      - echo "âœ… All Go tests passed"
    silent: true

  test-coverage:
    desc: Run tests with coverage report
    deps: [ensure-lib]
    cmds:
      - echo "ðŸ“Š Running tests with coverage..."
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "âœ… Coverage report generated in coverage.html"
    silent: true

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "ðŸ§¹ Cleaning build artifacts..."
      - cd {{.BINDINGS_DIR}} && cargo clean
      - rm -rf generated/
      - echo "âœ… Clean complete"
    silent: true

  # Examples
  example:
    desc: Run the simple example
    deps: [ensure-lib]
    dir: examples/simple
    cmds:
      - echo "ðŸš€ Running simple example..."
      - go run .
    silent: true

  example:server:
    desc: Run the SLIM server
    deps: [ensure-lib]
    dir: cmd/server
    cmds:
      - echo "ðŸš€ Starting SLIM server..."
      - go run . {{.CLI_ARGS}}
    silent: true

  example:p2p:alice:
    desc: Run Alice (receiver) for point-to-point example
    deps: [ensure-lib]
    dir: examples/point_to_point
    cmds:
      - echo "ðŸ‘© Starting Alice (receiver)..."
      - go run . --local="org/alice/app" --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true

  example:p2p:bob:
    desc: Run Bob (sender) for point-to-point example
    deps: [ensure-lib]
    dir: examples/point_to_point
    cmds:
      - echo "ðŸ‘¨ Starting Bob (sender)..."
      - go run . --local="org/bob/app" --remote="org/alice/app" --message="Hello SLIM" --iterations=5 --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true

  example:group:moderator:
    desc: Run group moderator (creates session and invites participants)
    deps: [ensure-lib]
    dir: examples/group
    cmds:
      - echo "ðŸ‘‘ Starting group moderator..."
      - go run . --local="org/moderator/app" --remote="org/default/chat-room" --invites="org/alice/app,org/bob/app" --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true

  example:group:participant:alice:
    desc: Run group participant (waits for invitation)
    deps: [ensure-lib]
    dir: examples/group
    cmds:
      - echo "ðŸ‘¤ Starting group participant..."
      - go run . --local="org/alice/app" --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true
  
  example:group:participant:bob:
    desc: Run group participant (waits for invitation)
    deps: [ensure-lib]
    dir: examples/group
    cmds:
      - echo "ðŸ‘¤ Starting group participant..."
      - go run . --local="org/bob/app" --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true
