# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

vars:
  SERVICE_DIR: ../../core/service
  SERVICE_TARGET: ../../target/release
  LIB_NAME: slim_service
  # Get absolute path for CGO flags
  ROOT_DIR:
    sh: pwd

tasks:
  default:
    desc: Show help (default task)
    cmds:
      - task: help

  help:
    desc: Show available tasks
    cmds:
      - |
        echo "SLIM Go Bindings - Available tasks:"
        echo ""
        echo "Build & Generate:"
        echo "  task rust-build                - Build the Rust library with UniFFI (release mode)"
        echo "  task generate                  - Generate Go bindings from compiled library"
        echo "  task install-uniffi-bindgen-go - Install uniffi-bindgen-go"
        echo ""
        echo "Testing:"
        echo "  task test                      - Run all tests"
        echo "  task test-coverage             - Run tests with coverage report"
        echo ""
        echo "Utilities:"
        echo "  task clean                     - Clean build artifacts"
        echo "  task help                      - Show this help message"
        echo ""
        echo "Examples:"
        echo "  task example                   - Run the simple example"
        echo "  task example:server            - Run the SLIM server"
        echo "  task example:p2p:alice         - Run Alice (receiver) for point-to-point"
        echo "  task example:p2p:bob           - Run Bob (sender) for point-to-point"
        echo "  task example:otel-receiver     - Run the OTEL receiver app"
    silent: true

  rust-build:
    desc: Build the Rust library with UniFFI (release mode)
    dir: "{{.SERVICE_DIR}}"
    cmds:
      - echo "🦀 Building Rust library with UniFFI (release mode)..."
      - cargo build --release
    silent: true

  generate:
    desc: Generate Go bindings from compiled library
    cmds:
      - echo "🔧 Generating Go bindings from compiled library..."
      - |
        uniffi-bindgen-go \
          --library '{{.SERVICE_TARGET}}/lib{{.LIB_NAME}}.dylib' \
          --out-dir generated
      - cd generated && go mod init github.com/agntcy/slim/bindings/generated 2>/dev/null || true
      - echo "✅ Bindings generated in generated/"
    silent: true

  install-uniffi-bindgen-go:
    desc: Install uniffi-bindgen-go
    cmds:
      - cargo install uniffi-bindgen-go --git https://github.com/NordSecurity/uniffi-bindgen-go.git --tag v0.4.0+v0.28.3 --config net.git-fetch-with-cli=true

  test:
    desc: Run all tests
    dir: tests
    env:
      CGO_LDFLAGS: -L{{.ROOT_DIR}}/{{.SERVICE_TARGET}} -l{{.LIB_NAME}}
      DYLD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${DYLD_LIBRARY_PATH}"
      LD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${LD_LIBRARY_PATH}"
    cmds:
      - echo "🧪 Running all tests..."
      - go mod tidy
      - go test -v .
      - echo "✅ All tests passed"
    silent: true

  test-coverage:
    desc: Run tests with coverage report
    dir: tests
    env:
      CGO_LDFLAGS: -L{{.ROOT_DIR}}/{{.SERVICE_TARGET}} -l{{.LIB_NAME}}
      DYLD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${DYLD_LIBRARY_PATH}"
      LD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${LD_LIBRARY_PATH}"
    cmds:
      - echo "📊 Running tests with coverage..."
      - go mod tidy
      - go test -v -coverprofile=coverage.out .
      - go tool cover -html=coverage.out -o coverage.html
      - echo "✅ Coverage report generated in tests/coverage.html"
    silent: true

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "🧹 Cleaning build artifacts..."
      - cd {{.SERVICE_DIR}} && cargo clean
      - rm -rf generated/
      - echo "✅ Clean complete"
    silent: true

  # Examples
  example:
    desc: Run the simple example
    dir: examples/simple
    env:
      CGO_LDFLAGS: -L{{.ROOT_DIR}}/{{.SERVICE_TARGET}} -l{{.LIB_NAME}}
      DYLD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${DYLD_LIBRARY_PATH}"
      LD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${LD_LIBRARY_PATH}"
    cmds:
      - echo "🚀 Running simple example..."
      - go mod init github.com/agntcy/slim/bindings/go/examples/simple 2>/dev/null || true
      - go mod edit -replace github.com/agntcy/slim/bindings/generated=../../generated
      - go mod tidy
      - go run main.go
    silent: true

  example:server:
    desc: Run the SLIM server
    dir: cmd/server
    env:
      CGO_LDFLAGS: -L{{.ROOT_DIR}}/{{.SERVICE_TARGET}} -l{{.LIB_NAME}}
      DYLD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${DYLD_LIBRARY_PATH}"
      LD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${LD_LIBRARY_PATH}"
    cmds:
      - echo "🚀 Starting SLIM server..."
      - go mod init github.com/agntcy/slim/cmd/server 2>/dev/null || true
      - go mod edit -replace github.com/agntcy/slim/bindings/generated=../../generated
      - go mod tidy
      - go run main.go {{.CLI_ARGS}}
    silent: true

  example:p2p:alice:
    desc: Run Alice (receiver) for point-to-point example
    dir: examples/point_to_point
    env:
      CGO_LDFLAGS: -L{{.ROOT_DIR}}/{{.SERVICE_TARGET}} -l{{.LIB_NAME}}
      DYLD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${DYLD_LIBRARY_PATH}"
      LD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${LD_LIBRARY_PATH}"
    cmds:
      - echo "👩 Starting Alice (receiver)..."
      - go mod tidy
      - go run main.go --local="org/alice/app" --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true

  example:p2p:bob:
    desc: Run Bob (sender) for point-to-point example
    dir: examples/point_to_point
    env:
      CGO_LDFLAGS: -L{{.ROOT_DIR}}/{{.SERVICE_TARGET}} -l{{.LIB_NAME}}
      DYLD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${DYLD_LIBRARY_PATH}"
      LD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${LD_LIBRARY_PATH}"
    cmds:
      - echo "👨 Starting Bob (sender)..."
      - go mod tidy
      - go run main.go --local="org/bob/app" --remote="org/alice/app" --message="Hello SLIM" --iterations=5 --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true

  example:otel-receiver:moderator:
    desc: Run the OTEL receiver app as moderator (initiator=true)
    dir: examples/slim-otel-receiver
    env:
      DYLD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${DYLD_LIBRARY_PATH}"
      LD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${LD_LIBRARY_PATH}"
    cmds:
      - echo "📡 Starting OTEL receiver as moderator (initiator=true)..."
      - go mod tidy
      - go run main.go --initiator=true {{.CLI_ARGS}}
    silent: true

  example:otel-receiver:participant:
    desc: Run the OTEL receiver app as participant (initiator=false)
    dir: examples/slim-otel-receiver
    env:
      DYLD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${DYLD_LIBRARY_PATH}"
      LD_LIBRARY_PATH: "{{.ROOT_DIR}}/{{.SERVICE_TARGET}}:${LD_LIBRARY_PATH}"
    cmds:
      - echo "📡 Starting OTEL receiver as participant (initiator=false)..."
      - go mod tidy
      - go run main.go --initiator=false {{.CLI_ARGS}}
    silent: true
