# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

includes:
  adapter:
    taskfile: "../adapter/Taskfile.yaml"
    internal: true
  rust:
    taskfile: ../../../tasks/rust.yaml
    internal: true

vars:
  # The Rust UniFFI bindings crate - in bindings/adapter (sibling to bindings/go)
  BINDINGS_DIR: "{{.TASKFILE_DIR}}../adapter"
  SERVICE_TARGET: "{{.TASKFILE_DIR}}/../../target/release"
  LIB_NAME: slim_bindings
  _DEFAULT_LIB_PATH: "{{.SERVICE_TARGET}}/lib{{.LIB_NAME}}.a"
  LIB_PATH: "{{.LIB_PATH | default ._DEFAULT_LIB_PATH}}"

tasks:
  default:
    cmds:
      - task -l

  rust-build:
    desc: Build the Rust library with UniFFI (release mode)
    dir: "{{.BINDINGS_DIR}}"
    cmds:
      - echo "ðŸ¦€ Building Rust bindings library with UniFFI (release mode)..."
      - cargo build --release
    silent: true

  ensure-lib:
    desc: Ensure the UniFFI library is built
    cmds:
      - |
        if [ ! -f "{{.LIB_PATH}}" ]; then
          echo "âš ï¸  UniFFI library not found, building now..."
          task rust-build
        else
          echo "âœ… Found UniFFI library: {{.LIB_PATH}}"
        fi
    silent: true

  patch-cgo-directives:
    desc: Patch generated Go bindings with proper cgo directives
    internal: true
    cmds:
      - echo "ðŸ”§ Patching cgo directives..."
      - |
        GO_FILE="generated/{{.LIB_NAME}}/{{.LIB_NAME}}.go"
        if [ -f "$GO_FILE" ]; then
          # Create the new cgo preamble with static LDFLAGS placeholders
          cat > /tmp/cgo_preamble.txt << 'EOF'
        package slim_bindings

        /*
        #cgo CFLAGS: -I${SRCDIR}
        #cgo linux,amd64 LDFLAGS: ${SRCDIR}/../../../../../.cache/slim-bindings/libslim_bindings.a -lm
        #cgo linux,arm64 LDFLAGS: ${SRCDIR}/../../../../../.cache/slim-bindings/libslim_bindings.a -lm
        #cgo darwin,amd64 LDFLAGS: ${SRCDIR}/../../../../../.cache/slim-bindings/libslim_bindings.a -Wl,-undefined,dynamic_lookup
        #cgo darwin,arm64 LDFLAGS: ${SRCDIR}/../../../../../.cache/slim-bindings/libslim_bindings.a -Wl,-undefined,dynamic_lookup
        #include <slim_bindings.h>
        */
        import "C"
        EOF

          # Extract the rest of the file after 'import "C"'
          sed -n '/^import "C"/,$p' "$GO_FILE" | tail -n +2 > /tmp/go_rest.txt

          # Combine the new preamble with the rest of the file
          cat /tmp/cgo_preamble.txt /tmp/go_rest.txt > "$GO_FILE"

          # Cleanup
          rm -f /tmp/cgo_preamble.txt /tmp/go_rest.txt
          echo "âœ… Patched $GO_FILE wits cgo directives"
        else
          echo "âš ï¸  Go file not found: $GO_FILE"
          exit 1
        fi
    silent: true

  generate:
    desc: Generate Go bindings from compiled library
    deps:
      - ensure-lib
      - install-uniffi-bindgen-go
    cmds:
      - echo "ðŸ”§ Generating Go bindings from compiled library..."
      - |
        uniffi-bindgen-go \
          --library '{{.LIB_PATH}}' \
          --library '{{.LIB_PATH}}' \
          --out-dir generated
      - cd generated && go mod init github.com/agntcy/slim/bindings/generated 2>/dev/null || true
      - task: copy-library
      - task: patch-cgo-directives
      - echo "âœ… Bindings generated in generated/"
    silent: true

  install-uniffi-bindgen-go:
    desc: Install uniffi-bindgen-go
    status:
      - which uniffi-bindgen-go
    status:
      - which uniffi-bindgen-go
    cmds:
      - echo "ðŸ“¦ Installing uniffi-bindgen-go..."
      - echo "ðŸ“¦ Installing uniffi-bindgen-go..."
      - cargo install uniffi-bindgen-go --git https://github.com/NordSecurity/uniffi-bindgen-go.git --tag v0.4.0+v0.28.3 --config net.git-fetch-with-cli=true
    silent: true

  copy-library:
    desc: Copy shared library to generated directory
    internal: true
    cmds:
      - echo "ðŸ“¦ Copying static libraries..."
      - |
        LIB_DIR=$(dirname "{{.LIB_PATH}}")
        DEST_DIR="generated/{{.LIB_NAME}}"

        # Check if libraries already have platform-specific names (from CI build)
        PLATFORM_LIBS=$(find "$LIB_DIR" -type f -name "lib{{.LIB_NAME}}_*.a" 2>/dev/null | head -1)

        if [ -n "$PLATFORM_LIBS" ]; then
          # CI build: libraries already have platform-specific names
          echo "ðŸ“¦ Found platform-specific libraries, copying..."
          find "$LIB_DIR" -type f -name "lib{{.LIB_NAME}}_*.a" | while read -r lib_file; do
            dest_name=$(basename "$lib_file")
            file_size=$(stat -f%z "$lib_file" 2>/dev/null || stat -c%s "$lib_file" 2>/dev/null)
            echo "   Copying $dest_name ($((file_size / 1024 / 1024))MB)"
            cp "$lib_file" "$DEST_DIR/$dest_name"
          done
        else
          # Local build: need to detect platform and rename
          echo "ðŸ“¦ Local build detected, renaming library for current platform..."

          # Detect architecture
          ARCH=$(uname -m)
          case "$ARCH" in
            x86_64|amd64) ARCH="x86_64" ;;
            arm64|aarch64) ARCH="aarch64" ;;
          esac

          # Detect OS
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          case "$OS" in
            darwin) OS="darwin" ;;
            linux) OS="linux_gnu" ;;  # Assume GNU for local builds
          esac

          LIB_NAME="lib{{.LIB_NAME}}_${ARCH}_${OS}"

          if [ -f "{{.LIB_PATH}}" ]; then
            file_size=$(stat -f%z "{{.LIB_PATH}}" 2>/dev/null || stat -c%s "{{.LIB_PATH}}" 2>/dev/null)
            echo "   Copying ${LIB_NAME}.a ($((file_size / 1024 / 1024))MB)"
            cp "{{.LIB_PATH}}" "$DEST_DIR/${LIB_NAME}.a"
            echo "âœ… Copied {{.LIB_PATH}} -> $DEST_DIR/$LIB_NAME"
          else
            echo "âš ï¸  Library not found: {{.LIB_PATH}}"
            exit 1
          fi
        fi
      - echo "âœ… Libraries in generated/{{.LIB_NAME}}/:"
      - ls -lah "generated/{{.LIB_NAME}}/"*{{.LIB_NAME}}*.a 2>/dev/null || echo "  (no .a files found)"
    silent: true

  test:
    desc: Run all tests
    deps: [ensure-lib]
    cmds:
      - echo "ðŸ§ª Running all tests..."
      - go test -v ./...
      - echo "âœ… All Go tests passed"
    silent: true

  test-coverage:
    desc: Run tests with coverage report
    deps: [ensure-lib]
    cmds:
      - echo "ðŸ“Š Running tests with coverage..."
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "âœ… Coverage report generated in coverage.html"
    silent: true

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "ðŸ§¹ Cleaning build artifacts..."
      - cd {{.BINDINGS_DIR}} && cargo clean
      - rm -rf generated/
      - echo "âœ… Clean complete"
    silent: true

  # Examples
  example:
    desc: Run the simple example
    deps:
      - task: adapter:bindings:build:all
        vars:
          PROFILE: release
    dir: examples/simple
    cmds:
      - echo "ðŸš€ Running simple example..."
      - go run .
    silent: true

  example:server:
    desc: Run the SLIM server
    deps:
      - task: adapter:bindings:build:all
        vars:
          PROFILE: release
    dir: cmd/server
    cmds:
      - echo "ðŸš€ Starting SLIM server..."
      - go run . {{.CLI_ARGS}}
    silent: true

  example:p2p:alice:
    desc: Run Alice (receiver) for point-to-point example
    deps:
      - task: adapter:bindings:build:all
        vars:
          PROFILE: release
    dir: examples/point_to_point
    cmds:
      - echo "ðŸ‘© Starting Alice (receiver)..."
      - go run . --local="org/alice/app" --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true

  example:p2p:bob:
    desc: Run Bob (sender) for point-to-point example
    deps:
      - task: adapter:bindings:build:all
        vars:
          PROFILE: release
    dir: examples/point_to_point
    cmds:
      - echo "ðŸ‘¨ Starting Bob (sender)..."
      - go run . --local="org/bob/app" --remote="org/alice/app" --message="Hello SLIM" --iterations=5 --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true

  example:group:moderator:
    desc: Run group moderator (creates session and invites participants)
    deps:
      - task: adapter:bindings:build:all
        vars:
          PROFILE: release
    dir: examples/group
    cmds:
      - echo "ðŸ‘‘ Starting group moderator..."
      - go run . --local="org/moderator/app" --remote="org/default/chat-room" --invites="org/alice/app,org/bob/app" --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true

  example:group:participant:alice:
    desc: Run group participant (waits for invitation)
    deps:
      - task: adapter:bindings:build:all
        vars:
          PROFILE: release
    dir: examples/group
    cmds:
      - echo "ðŸ‘¤ Starting group participant..."
      - go run . --local="org/alice/app" --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true

  example:group:participant:bob:
    desc: Run group participant (waits for invitation)
    deps:
      - task: adapter:bindings:build:all
        vars:
          PROFILE: release
    dir: examples/group
    cmds:
      - echo "ðŸ‘¤ Starting group participant..."
      - go run . --local="org/bob/app" --server="http://localhost:46357" {{.CLI_ARGS}}
    silent: true
