# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

env:
  SHARED_SECRET: "demo-secret-key-for-examples012345"

includes:
  rust:
    taskfile: ../../../tasks/rust.yaml
    internal: true

tasks:
  default:
    cmds:
      - task -l

  python:bindings:lint:
    desc: "Lint the Python bindings"
    cmds:
      - uv run ruff check
      - uv run ruff format --check
      - uv run mypy --ignore-missing-imports --explicit-package-bases .

  python:bindings:build:
    desc: "Build the Python bindings using Maturin"
    deps:
      - python:bindings:clean
    vars:
      PROFILE: '{{.PROFILE | default "debug"}}'
      RELEASE:
        sh: '[[ {{.PROFILE}} == "release" ]] && echo "--release" || echo ""'
    cmds:
      - echo "🔨 Building Python bindings..."
      - task: rust:toolchain:run-command
        vars:
          COMMAND: |
            uv run --no-cache maturin develop --uv {{.RELEASE}}
      - echo "✅ Build complete"

  python:bindings:test:
    desc: "Test the Python bindings"
    deps:
      - python:bindings:build
    cmds:
      - uv run --no-cache pytest -s {{.TESTS}}
    vars:
      TARGET: '{{.TESTS | default ""}}'

  python:bindings:test:integration:
    desc: Run integration tests only
    deps: [python:bindings:build]
    cmds:
      - echo "Running integration tests...\n"
      - SLIM_INTEGRATION_TEST=1 uv run pytest tests/integration_test.py -v -s
      - echo "✅ Integration tests passed"

  python:bindings:test:coverage:
    desc: "Test the Python bindings with coverage"
    deps:
      - python:bindings:build
    cmds:
      - uv run pytest --cov=slim_bindings --cov-report=lcov:coverage.lcov --cov-report=html --cov-report=term -s {{.TESTS}}
    vars:
      TARGET: '{{.TESTS | default ""}}'

  python:bindings:packaging:
    desc: "Generate Python wheels for multiple Python versions (3.10, 3.11, 3.12, 3.13, 3.14) using Maturin"
    vars:
      PROFILE: '{{.PROFILE | default "release"}}'
      RELEASE:
        sh: '[[ {{.PROFILE}} == "release" ]] && echo "--release" || echo ""'
      _TARGET:
        sh: 'rustc -vV | grep "host: " | cut -d" " -f2'
      TARGET: '{{.TARGET | default ._TARGET}}'
      ARCH:
        sh: 'echo {{.TARGET}} | cut -d"-" -f1'
      OS:
        sh: 'echo {{.TARGET}} | cut -d"-" -f3'
      C_LIB:
        sh: 'echo {{.TARGET}} | cut -d"-" -f4 || echo ""'
      INTERPRETERS: '{{.INTERPRETERS | default "3.10 3.11 3.12 3.13 3.14"}}'
    cmds:
      - uv python install {{.INTERPRETERS}}
      - task: rust:toolchain:run-command
        vars:
          COMMAND: |
            rustup target add {{.TARGET}}

            UV_ARGS=(
              --no-default-groups
              --group building
            )

            MATURIN_ARGS=(
              {{.RELEASE}}
              --out dist
              --target {{.TARGET}}
              --frozen
              -i {{.INTERPRETERS}}
            )

            if [[ "{{.C_LIB}}" = "gnu" ]]; then
              MATURIN_ARGS+=(
                --compatibility manylinux_2_28
                --zig
              )
            elif [[ "{{.C_LIB}}" = "musl" ]]; then
              MATURIN_ARGS+=(
                --compatibility musllinux_1_2
                --zig
              )
            fi

            # Workaround for windows
            if [[ "{{.OS}}" = "windows" ]]; then
              uv sync ${UV_ARGS[@]}
              uv run ${UV_ARGS[@]} maturin develop --uv {{.RELEASE}}

              # This file is a leftover from the previous build, delete it otherwise
              # maturin will try to add it to the wheel, and it will fail
              rm -f slim_bindings/*.pyd
            fi

            echo "Running maturin with the following args: ${MATURIN_ARGS[@]}"

            uv run                            \
              ${UV_ARGS[@]}                   \
              maturin build                   \
              ${MATURIN_ARGS[@]}

  python:bindings:clean:
    desc: Clean build artifacts
    cmds:
      - echo "🧹 Cleaning build artifacts..."
      - uv pip uninstall -y slim-bindings 2>/dev/null || true
      - rm -rf ../rust/target/debug/libslim_bindings.so
      - rm -rf ../rust/target/debug/libslim_bindings.dylib
      - rm -rf ../rust/target/debug/libslim_bindings.dll
      - rm -rf ../rust/target/debug/deps/libslim_bindings.so
      - rm -rf ../rust/target/debug/deps/libslim_bindings.dylib
      - rm -rf ../rust/target/debug/deps/libslim_bindings.dll
      - rm -rf .venv/lib/python*/site-packages/slim_bindings/
      - rm -rf .venv/lib/python*/site-packages/slim_bindings-*.dist-info/
      - rm -rf dist/
      - rm -rf build/
      - rm -rf *.egg-info/
      - rm -rf .pytest_cache/
      - rm -rf __pycache__/
      - rm -rf slim_bindings/__pycache__/
      - rm -rf slim_bindings/*.so
      - rm -rf slim_bindings/*.dylib
      - rm -rf slim_bindings/*.dll
      - rm -rf slim_bindings/*.pyd
      - rm -rf examples/__pycache__/
      - rm -rf examples/*/__pycache__/
      - rm -rf tests/__pycache__/
      - echo "✅ Clean complete"

  python:example:server:
    desc: "Run the server example"
    env:
      SLIM_INSTANCE_ID: server
    cmds:
      - uv run slim-bindings-server --slim "127.0.0.1:46357" {{.EXTRA_ARGS}}
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:p2p:alice:
    desc: "Point to Point example - Alice will listen for messages and echo them"
    cmds:
      - |
        uv run slim-bindings-p2p                                                      \
          --local agntcy/ns/alice                                                     \
          --shared-secret $SHARED_SECRET {{.EXTRA_ARGS}}
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:p2p:no-mls:bob:
    desc: "Point to Point example - Bob will send unencrypted messages to Alice"
    env:
      SLIM_INSTANCE_ID: bob
    cmds:
      - |
        uv run slim-bindings-p2p                                                      \
          --local agntcy/ns/bob                                                       \
          --shared-secret $SHARED_SECRET                                              \
          --remote agntcy/ns/alice                                                    \
          --message "hey there"                                                       \
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:p2p:mls:bob:
    desc: "Point to Point example - Bob will send encrypted messages to Alice"
    env:
      SLIM_INSTANCE_ID: bob
    cmds:
      - |
        uv run slim-bindings-p2p                                                      \
          --local agntcy/ns/bob                                                       \
          --shared-secret $SHARED_SECRET                                              \
          --remote agntcy/ns/alice                                                    \
          --message "hey there"                                                       \
          --enable-mls                                                                \
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:group:moderator:
    desc: "group moderator example - Creates a channel, invites participants, and sends encrypted messages"
    cmds:
      - |
        uv run slim-bindings-group                                                    \
          --local agntcy/ns/moderator                                                 \
          --shared-secret $SHARED_SECRET                                              \
          --remote agntcy/ns/chat                                                     \
          --invites agntcy/ns/client-1                                                \
          --invites agntcy/ns/client-2                                                \
          --enable-mls {{.EXTRA_ARGS}}
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:group:client-1:
    desc: "Group client example - Waits to be invited to a channel and receives encrypted messages"
    cmds:
      - |
        uv run slim-bindings-group                                                    \
          --local agntcy/ns/client-1                                                  \
          --shared-secret $SHARED_SECRET{{.EXTRA_ARGS}}
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:group:client-2:
    desc: "Group client example - Waits to be invited to a channel and receives encrypted messages"
    cmds:
      - |
        uv run slim-bindings-group                                                    \
          --local agntcy/ns/client-2                                                  \
          --shared-secret $SHARED_SECRET{{.EXTRA_ARGS}}
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'
