// Code generated by protoc-gen-slimrpc-go. DO NOT EDIT.
// source: example.proto

package types

import (
	"context"
	"fmt"
	
	slim_bindings "github.com/agntcy/slim/bindings/generated/slim_bindings"
	"google.golang.org/protobuf/proto"

)


// TestClient is the client API for Test service.
type TestClient interface {
	ExampleUnaryUnary(ctx context.Context, req *ExampleRequest) (*ExampleResponse, error)
}

type TestClientImpl struct {
	channel *slim_bindings.Channel
}

// NewTestClient creates a new Test client.
func NewTestClient(channel *slim_bindings.Channel) TestClient {
	return &TestClientImpl{
		channel: channel,
	}
}


func (c *TestClientImpl) ExampleUnaryUnary(ctx context.Context, req *ExampleRequest) (*ExampleResponse, error) {
	// Serialize request
	reqBytes, err := proto.Marshal(req)
	if err != nil {
		return nil, err
	}
	
	// Make RPC call
	respBytes, err := c.channel.CallUnaryAsync("example_service.Test", "ExampleUnaryUnary", reqBytes, nil)
	if err != nil {
		fmt.Printf("Error from CallUnaryAsync: %#v\n", err)
		rpcError, ok := err.(*slim_bindings.RpcError)
		if ok {
			err = rpcError.AsError()
			fmt.Printf("Got RPC ERROR: %#v\n", err)
		}
		return nil, err
	}
	
	// Deserialize response
	resp := &ExampleResponse{}
	if err := proto.Unmarshal(respBytes, resp); err != nil {
		return nil, err
	}
	
	return resp, nil
}


// TestServer is the server API for Test service.
// All implementations must embed UnimplementedTestServer
// for forward compatibility
type TestServer interface {
	ExampleUnaryUnary(ctx context.Context, req *ExampleRequest) (*ExampleResponse, error)
}

// UnimplementedTestServer must be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}


func (UnimplementedTestServer) ExampleUnaryUnary(ctx context.Context, req *ExampleRequest) (*ExampleResponse, error) {
	return nil, fmt.Errorf("method ExampleUnaryUnary not implemented")
}


// RegisterTestServer registers the server with slim_bindings.
func RegisterTestServer(server *slim_bindings.Server, impl TestServer) {
	server.RegisterUnaryUnary("example_service.Test", "ExampleUnaryUnary", &Test_ExampleUnaryUnary_Handler{impl: impl})
}


type Test_ExampleUnaryUnary_Handler struct {
	impl TestServer
}

func (h *Test_ExampleUnaryUnary_Handler) Handle(request []byte, rpcContext *slim_bindings.Context) ([]byte, error) {
	req := &ExampleRequest{}
	if err := proto.Unmarshal(request, req); err != nil {
		return nil, err
	}
	
	ctx := context.Background()
	// TODO: Add deadline from rpcContext to ctx if needed
	
	resp, err := h.impl.ExampleUnaryUnary(ctx, req)
	if err != nil {
		return nil, err
	}
	
	return proto.Marshal(resp)
}
