// Code generated by protoc-gen-slimrpc-go. DO NOT EDIT.
// source: example.proto

package types

import (
	"context"
	"fmt"

	slim_bindings "github.com/agntcy/slim-bindings-go"
	"github.com/agntcy/slim-bindings-go/slimrpc"
	"google.golang.org/protobuf/proto"
)

// TestClient is the client API for Test service.
type TestClient interface {
	ExampleUnaryUnary(ctx context.Context, req *ExampleRequest) (*ExampleResponse, error)
	ExampleUnaryStream(ctx context.Context, req *ExampleRequest) (slimrpc.ResponseStream[*ExampleResponse], error)
	ExampleUnaryStreamTwo(ctx context.Context, req *ExampleRequest) (slimrpc.ResponseStream[*ExampleResponse], error)
	ExampleStreamUnary(ctx context.Context) (slimrpc.ClientRequestStream[*ExampleRequest, *ExampleResponse], error)
	ExampleStreamStream(ctx context.Context) (slimrpc.ClientBidiStream[*ExampleRequest, *ExampleResponse], error)
}

type TestClientImpl struct {
	channel *slim_bindings.Channel
}

// NewTestClient creates a new Test client.
func NewTestClient(channel *slim_bindings.Channel) TestClient {
	return &TestClientImpl{
		channel: channel,
	}
}

func (c *TestClientImpl) ExampleUnaryUnary(ctx context.Context, req *ExampleRequest) (*ExampleResponse, error) {
	// Serialize request
	reqBytes, err := proto.Marshal(req)
	if err != nil {
		return nil, err
	}

	// Make RPC call
	respBytes, err := c.channel.CallUnaryAsync("example_service.Test", "ExampleUnaryUnary", reqBytes, nil)
	if err != nil {
		return nil, err
	}

	// Deserialize response
	resp := &ExampleResponse{}
	if err := proto.Unmarshal(respBytes, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

func (c *TestClientImpl) ExampleUnaryStream(ctx context.Context, req *ExampleRequest) (slimrpc.ResponseStream[*ExampleResponse], error) {
	// Serialize request
	reqBytes, err := proto.Marshal(req)
	if err != nil {
		return nil, err
	}

	// Make RPC call
	stream, err := c.channel.CallUnaryStreamAsync("example_service.Test", "ExampleUnaryStream", reqBytes, nil)
	if err != nil {
		return nil, err
	}

	return slimrpc.NewClientResponseStream[*ExampleResponse](stream), nil
}

func (c *TestClientImpl) ExampleUnaryStreamTwo(ctx context.Context, req *ExampleRequest) (slimrpc.ResponseStream[*ExampleResponse], error) {
	// Serialize request
	reqBytes, err := proto.Marshal(req)
	if err != nil {
		return nil, err
	}

	// Make RPC call
	stream, err := c.channel.CallUnaryStreamAsync("example_service.Test", "ExampleUnaryStreamTwo", reqBytes, nil)
	if err != nil {
		return nil, err
	}

	return slimrpc.NewClientResponseStream[*ExampleResponse](stream), nil
}

func (c *TestClientImpl) ExampleStreamUnary(ctx context.Context) (slimrpc.ClientRequestStream[*ExampleRequest, *ExampleResponse], error) {
	stream := c.channel.CallStreamUnary("example_service.Test", "ExampleStreamUnary", nil)
	return slimrpc.NewClientRequestStream[*ExampleRequest, *ExampleResponse](stream), nil
}

func (c *TestClientImpl) ExampleStreamStream(ctx context.Context) (slimrpc.ClientBidiStream[*ExampleRequest, *ExampleResponse], error) {
	stream := c.channel.CallStreamStream("example_service.Test", "ExampleStreamStream", nil)
	return slimrpc.NewClientBidiStream[*ExampleRequest, *ExampleResponse](stream), nil
}

// TestServer is the server API for Test service.
// All implementations must embed UnimplementedTestServer
// for forward compatibility
type TestServer interface {
	ExampleUnaryUnary(ctx context.Context, req *ExampleRequest) (*ExampleResponse, error)
	ExampleUnaryStream(req *ExampleRequest, stream slimrpc.RequestStream[*ExampleResponse]) error
	ExampleUnaryStreamTwo(req *ExampleRequest, stream slimrpc.RequestStream[*ExampleResponse]) error
	ExampleStreamUnary(stream slimrpc.ResponseStream[*ExampleRequest]) (*ExampleResponse, error)
	ExampleStreamStream(stream slimrpc.ServerBidiStream[*ExampleRequest, *ExampleResponse]) error
}

// UnimplementedTestServer must be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (UnimplementedTestServer) ExampleUnaryUnary(ctx context.Context, req *ExampleRequest) (*ExampleResponse, error) {
	return nil, fmt.Errorf("method ExampleUnaryUnary not implemented")
}

func (UnimplementedTestServer) ExampleUnaryStream(req *ExampleRequest, stream slimrpc.RequestStream[*ExampleResponse]) error {
	return fmt.Errorf("method ExampleUnaryStream not implemented")
}

func (UnimplementedTestServer) ExampleUnaryStreamTwo(req *ExampleRequest, stream slimrpc.RequestStream[*ExampleResponse]) error {
	return fmt.Errorf("method ExampleUnaryStreamTwo not implemented")
}

func (UnimplementedTestServer) ExampleStreamUnary(stream slimrpc.ResponseStream[*ExampleRequest]) (*ExampleResponse, error) {
	return nil, fmt.Errorf("method ExampleStreamUnary not implemented")
}

func (UnimplementedTestServer) ExampleStreamStream(stream slimrpc.ServerBidiStream[*ExampleRequest, *ExampleResponse]) error {
	return fmt.Errorf("method ExampleStreamStream not implemented")
}

// RegisterTestServer registers the server with slim_bindings.
func RegisterTestServer(server *slim_bindings.Server, impl TestServer) {
	server.RegisterUnaryUnary("example_service.Test", "ExampleUnaryUnary", &Test_ExampleUnaryUnary_Handler{impl: impl})
	server.RegisterUnaryStream("example_service.Test", "ExampleUnaryStream", &Test_ExampleUnaryStream_Handler{impl: impl})
	server.RegisterUnaryStream("example_service.Test", "ExampleUnaryStreamTwo", &Test_ExampleUnaryStreamTwo_Handler{impl: impl})
	server.RegisterStreamUnary("example_service.Test", "ExampleStreamUnary", &Test_ExampleStreamUnary_Handler{impl: impl})
	server.RegisterStreamStream("example_service.Test", "ExampleStreamStream", &Test_ExampleStreamStream_Handler{impl: impl})
}

type Test_ExampleUnaryUnary_Handler struct {
	impl TestServer
}

func (h *Test_ExampleUnaryUnary_Handler) Handle(request []byte, rpcContext *slim_bindings.Context) ([]byte, error) {
	req := &ExampleRequest{}
	if err := proto.Unmarshal(request, req); err != nil {
		return nil, err
	}

	ctx := context.Background()
	// TODO: Add deadline from rpcContext to ctx if needed

	resp, err := h.impl.ExampleUnaryUnary(ctx, req)
	if err != nil {
		return nil, err
	}

	return proto.Marshal(resp)
}

type Test_ExampleUnaryStream_Handler struct {
	impl TestServer
}

func (h *Test_ExampleUnaryStream_Handler) Handle(request []byte, rpcContext *slim_bindings.Context, sink *slim_bindings.ResponseSink) error {
	req := &ExampleRequest{}
	if err := proto.Unmarshal(request, req); err != nil {
		return err
	}

	stream := slimrpc.NewServerRequestStream[*ExampleResponse](sink)
	err := h.impl.ExampleUnaryStream(req, stream)

	// Close the stream after handler returns
	closeErr := sink.CloseAsync()
	if err == nil {
		err = closeErr
	}

	return err
}

type Test_ExampleUnaryStreamTwo_Handler struct {
	impl TestServer
}

func (h *Test_ExampleUnaryStreamTwo_Handler) Handle(request []byte, rpcContext *slim_bindings.Context, sink *slim_bindings.ResponseSink) error {
	req := &ExampleRequest{}
	if err := proto.Unmarshal(request, req); err != nil {
		return err
	}

	stream := slimrpc.NewServerRequestStream[*ExampleResponse](sink)
	err := h.impl.ExampleUnaryStreamTwo(req, stream)

	// Close the stream after handler returns
	closeErr := sink.CloseAsync()
	if err == nil {
		err = closeErr
	}

	return err
}

type Test_ExampleStreamUnary_Handler struct {
	impl TestServer
}

func (h *Test_ExampleStreamUnary_Handler) Handle(stream *slim_bindings.RequestStream, rpcContext *slim_bindings.Context) ([]byte, error) {
	serverStream := slimrpc.NewServerResponseStream[*ExampleRequest](stream)

	resp, err := h.impl.ExampleStreamUnary(serverStream)
	if err != nil {
		return nil, err
	}

	return proto.Marshal(resp)
}

type Test_ExampleStreamStream_Handler struct {
	impl TestServer
}

func (h *Test_ExampleStreamStream_Handler) Handle(stream *slim_bindings.RequestStream, rpcContext *slim_bindings.Context, sink *slim_bindings.ResponseSink) error {
	serverStream := slimrpc.NewServerBidiStream[*ExampleRequest, *ExampleResponse](stream, sink)

	err := h.impl.ExampleStreamStream(serverStream)

	// Close the stream after handler returns
	closeErr := sink.CloseAsync()
	if err == nil {
		err = closeErr
	}

	return err
}
