# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

tasks:
  python:example:server:
    desc: "Run the server example"
    env:
      SLIM_INSTANCE_ID: server
    cmds:
      - uv run --package slim-bindings-examples slim --slim "0.0.0.0:46357" {{.EXTRA_ARGS}}
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:p2p:alice:
    desc: "Point to Point example - Alice will listen for messages and echo them"
    cmds:
      - |
        uv run --package slim-bindings-examples anycast                               \
          --local agntcy/ns/alice                                                     \
          --slim '{"endpoint": "http://localhost:46357", "tls": {"insecure": true}}'  \
          --shared-secret "secret" {{.EXTRA_ARGS}}
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:p2p:anycast:bob:
    desc: "Anycast Point to Point example - Bob will send unencrypted messages to Alice"
    env:
      SLIM_INSTANCE_ID: bob
    cmds:
      - |
        uv run --package slim-bindings-examples anycast                               \
          --local agntcy/ns/bob                                                       \
          --slim '{"endpoint": "http://localhost:46357", "tls": {"insecure": true}}'  \
          --shared-secret "secret"                                                    \
          --remote agntcy/ns/alice                                                    \
          --message "hey there"                                                       \
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:p2p:unicast:no-mls:bob:
    desc: "Unicast Point to Point example - Bob will send unencrypted messages to Alice"
    env:
      SLIM_INSTANCE_ID: bob
    cmds:
      - |
        uv run --package slim-bindings-examples unicast                               \
          --local agntcy/ns/bob                                                       \
          --slim '{"endpoint": "http://localhost:46357", "tls": {"insecure": true}}'  \
          --shared-secret "secret"                                                    \
          --remote agntcy/ns/alice                                                    \
          --message "hey there"                                                       \
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:p2p:unicast:mls:bob:
    desc: "Unicast Point to Point example - Bob will send unencrypted messages to Alice"
    env:
      SLIM_INSTANCE_ID: bob
    cmds:
      - |
        uv run --package slim-bindings-examples unicast                               \
          --local agntcy/ns/bob                                                       \
          --slim '{"endpoint": "http://localhost:46357", "tls": {"insecure": true}}'  \
          --shared-secret "secret"                                                    \
          --remote agntcy/ns/alice                                                    \
          --message "hey there"                                                       \
          --enable-mls                                                                \
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:multicast:moderator:
    desc: "multicast moderator example - Creates a channel, invites participants, and sends encrypted messages"
    cmds:
      - |
        uv run --package slim-bindings-examples multicast                             \
          --local agntcy/ns/moderator                                                 \
          --slim '{"endpoint": "http://localhost:46357", "tls": {"insecure": true}}'  \
          --shared-secret "secret"                                                    \
          --remote agntcy/ns/chat                                                     \
          --invites agntcy/ns/client-1                                                \
          --invites agntcy/ns/client-2                                                \
          --enable-mls {{.EXTRA_ARGS}}
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:multicast:client-1:
    desc: "Multicast client example - Waits to be invited to a channel and receives encrypted messages"
    cmds:
      - |
        uv run --package slim-bindings-examples multicast                             \
          --local agntcy/ns/client-1                                                  \
          --slim '{"endpoint": "http://localhost:46357", "tls": {"insecure": true}}'  \
          --shared-secret "secret" {{.EXTRA_ARGS}}
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'

  python:example:multicast:client-2:
    desc: "Multicast client example - Waits to be invited to a channel and receives encrypted messages"
    cmds:
      - |
        uv run --package slim-bindings-examples multicast                             \
          --local agntcy/ns/client-2                                                  \
          --slim '{"endpoint": "http://localhost:46357", "tls": {"insecure": true}}'  \
          --shared-secret "secret" {{.EXTRA_ARGS}}
    vars:
      EXTRA_ARGS: '{{.EXTRA_ARGS | default ""}}'
