# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: "3"

silent: true

includes:
  tools:
    taskfile: ../tasks/tools.yaml
    flatten: true

vars:
  REPO_ROOT:
    sh: git rev-parse --show-toplevel

  OUTPUT_DIR: "{{.REPO_ROOT}}/.dist"

  CONTROL_PLANE_DIR: control-plane

  MAIN_MODULE: github.com/agntcy/slim

  # Explicit module paths for cross-platform compatibility (Windows + Unix)
  MODULES: "{{.REPO_ROOT}}/control-plane/common {{.REPO_ROOT}}/control-plane/control-plane {{.REPO_ROOT}}/control-plane/slimctl {{.REPO_ROOT}}/control-plane/token-service"

env:
  GOTOOLCHAIN: "go1.25.0+auto"

tasks:
  control-plane:foreach-module:
    internal: true
    desc: Run task for each module
    cmds:
      - |
        for dir in {{.MODULES}}; do
          pushd ${dir} > /dev/null
          echo "${dir}: running {{.CMD}}"
          {{.CMD}}
          popd > /dev/null
        done

  control-plane:modtidy:
    desc: Install go modules
    cmds:
      - task: control-plane:foreach-module
        vars:
          CMD: go mod tidy

  control-plane:gogen:
    desc: Run go generate
    cmds:
      - task: control-plane:foreach-module
        vars:
          CMD: go generate ./...

  control-plane:lint:
    desc: Run go linter
    deps:
      - tools
    cmds:
      - task: control-plane:gogen
      - task: control-plane:foreach-module
        vars:
          CMD: "echo ${PWD} && {{.TOOLS_INSTALL_DIR}}/golangci-lint run"

  control-plane:impi:
    desc: Run go impi
    deps:
      - tools
    cmds:
      - task: control-plane:gogen
      - task: control-plane:foreach-module
        vars:
          CMD: |
            {{.TOOLS_INSTALL_DIR}}/impi \
              --local github.com/agntcy/slim \
              --ignore-generated=true \
              --scheme stdThirdPartyLocal \
              ./...

  control-plane:vuln:
    desc: Run go govulncheck
    deps:
      - tools
    cmds:
      - task: control-plane:gogen
      - task: control-plane:foreach-module
        vars:
          CMD: "{{.TOOLS_INSTALL_DIR}}/govulncheck ./..."

  control-plane:coverage-reports:
    desc: Check test coverage
    deps:
      - tools
    cmds:
      - task: control-plane:gogen
      - task: control-plane:foreach-module
        vars:
          CMD: |
            {{.TOOLS_INSTALL_DIR}}/go-acc --output=$(basename  ${dir})-coverage.out ./...

  control-plane:coverage:
    desc: Show coverage in browser
    deps:
      - control-plane:coverage-reports
    cmds:
      - echo find . -name '*coverage.out' -execdir go tool cover -html=./{} \;

  control-plane:test:
    desc: Run go tests
    deps:
      - tools
    cmds:
      - task: control-plane:gogen
      - task: control-plane:foreach-module
        vars:
          CMD: go test --tags=test -failfast -v 2>&1 ./...

  control-plane:fetch:
    desc: Download go modules
    deps:
      - tools
    cmds:
      - task: control-plane:gogen
      - task: control-plane:foreach-module
        vars:
          CMD: "echo ${PWD} && go env && go mod download"

  control-plane:proto:generate:
    desc: Generate Go protobuf and gRPC code
    deps:
      - tools
    cmds:
      - |
        # Find binaries (with or without .exe extension for Windows compatibility)
        PROTOC="{{.REPO_ROOT}}/.tools/protoc"
        PROTOC_GEN_GO="{{.REPO_ROOT}}/.tools/protoc-gen-go"
        PROTOC_GEN_GO_GRPC="{{.REPO_ROOT}}/.tools/protoc-gen-go-grpc"

        [[ -f "${PROTOC}.exe" ]] && PROTOC="${PROTOC}.exe"
        [[ -f "${PROTOC_GEN_GO}.exe" ]] && PROTOC_GEN_GO="${PROTOC_GEN_GO}.exe"
        [[ -f "${PROTOC_GEN_GO_GRPC}.exe" ]] && PROTOC_GEN_GO_GRPC="${PROTOC_GEN_GO_GRPC}.exe"

        # On Windows, Git symlinks are stored as text files containing the target path.
        # Check if the controller.proto symlink is broken (small file with path content).
        CONTROLLER_PROTO="../proto/controller/v1/controller.proto"

        if [[ -f "$CONTROLLER_PROTO" && $(wc -c < "$CONTROLLER_PROTO") -lt 200 ]]; then
          echo "Resolving symlink for controller.proto (Windows compatibility)"
          # Temporarily copy the actual proto file over the broken symlink
          cp "{{.REPO_ROOT}}/data-plane/core/controller/proto/v1/controller.proto" "$CONTROLLER_PROTO"
          RESTORE_SYMLINK=1
        fi

        $PROTOC \
          --proto_path=../proto \
          --plugin=protoc-gen-go=$PROTOC_GEN_GO \
          --plugin=protoc-gen-go-grpc=$PROTOC_GEN_GO_GRPC \
          --go_out=paths=source_relative:./common/proto \
          --go-grpc_out=paths=source_relative:./common/proto \
          controller/v1/controller.proto controlplane/v1/controlplane.proto

        # Restore the symlink file if we modified it
        if [[ "${RESTORE_SYMLINK:-}" == "1" ]]; then
          git checkout "$CONTROLLER_PROTO" 2>/dev/null || true
        fi

  control-plane:slimctl:build:
    desc: Build slimctl
    deps:
      - control-plane:proto:generate
    dir: slimctl/cmd
    cmds:
      - task: control-plane:gogen
      - |
        go build -o \
          {{.OUTPUT_DIR}}/bin/slimctl \
          -ldflags \
          " \
            -X '{{.MAIN_MODULE}}/control-plane/slimctl/internal/cmd/version.semVersion={{.VERSION}}'
            -X '{{.MAIN_MODULE}}/control-plane/slimctl/internal/cmd/version.gitCommit={{.GIT_COMMIT}}'
            -X '{{.MAIN_MODULE}}/control-plane/slimctl/internal/cmd/version.buildDate={{.BUILD_DATE}}'
            {{.FLAGS}} \
          "
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
      BUILD_DATE:
        sh: date -u +'%Y-%m-%dT%H:%M:%SZ'
      VERSION:
        sh: pushd {{.REPO_ROOT}} > /dev/null && task version && popd > /dev/null

  control-plane:token-service:build:
    desc: Build token service
    dir: token-service/cmd
    cmds:
      - |
        go build -o \
          {{.OUTPUT_DIR}}/bin/slim-tks \
          -ldflags \
          " \
            -X '{{.MAIN_MODULE}}/control-plane/internal/cmd/version.semVersion={{.VERSION}}'
            -X '{{.MAIN_MODULE}}/control-plane/internal/cmd/version.gitCommit={{.GIT_COMMIT}}'
            -X '{{.MAIN_MODULE}}/control-plane/internal/cmd/version.buildDate={{.BUILD_DATE}}'
            {{.FLAGS}} \
          "
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
      BUILD_DATE:
        sh: date -u +'%Y-%m-%dT%H:%M:%SZ'
      VERSION:
        sh: pushd {{.REPO_ROOT}} > /dev/null && task version && popd > /dev/null

  control-plane:build:
    desc: Build go binaries
    deps:
      - control-plane:modtidy
    cmds:
      - task: control-plane:control-plane:build
      - task: control-plane:token-service:build
      - task: control-plane:slimctl:build


  #  control plane related tasks
  control-plane:control-plane:build:
    desc: Builds the control plane binary
    dir: control-plane/cmd
    deps:
      - control-plane:proto:generate
    cmds:
      - task: control-plane:modtidy
      - task: control-plane:gogen
      - |
        go build -o \
          {{.OUTPUT_DIR}}/bin/control-plane

  control-plane:control-plane:run:
    desc: Runs the control plane binary
    deps:
      - control-plane:control-plane:build
    cmds:
      - |
        {{.OUTPUT_DIR}}/bin/control-plane \
          --config {{.REPO_ROOT}}/control-plane/control-plane/config/config.yaml
