# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0
version: "3"

includes:
  rust:
    taskfile: ../../../tasks/rust.yaml
    internal: true

vars:
  PROFILE: '{{.PROFILE | default "debug"}}'
  BINDINGS_PACKAGE: agntcy-slim-bindings
  CURRENT_TARGET:
    sh: 'rustc -vV | sed -n "s|host: ||p"'
  TARGET: "{{.TARGET | default .CURRENT_TARGET}}"
  SHARED_SECRET: "a-very-long-shared-secret-abcdef1234567890"

tasks:
  default:
    cmds:
      - task -l

  bindings:build:all:
    desc: Build the Rust library with cross-compilation support
    dir: "{{.TASKFILE_DIR}}"
    silent: false
    aliases:
      - build
      - generate
    cmds:
      - echo "🦀 Building Rust bindings library... {{.TARGET}}"
      - task: rust:crossbuild
        vars:
          ARGS: --config 'profile.release.strip="none"'
          TARGET: "{{.TARGET}}"
          PROFILE: "{{.PROFILE}}"
      - echo "🦀 Rust bindings library built successfully."

  lint:
    desc: Run Rust format check and clippy for the bindings crate
    dir: "{{.TASKFILE_DIR}}/../.."
    cmds:
      - cargo fmt -p {{.BINDINGS_PACKAGE}} -- --check
      - cargo clippy -p {{.BINDINGS_PACKAGE}} --all-targets --locked --all-features -- -D warnings

  test:
    desc: Run the Rust tests for the bindings crate
    dir: "{{.TASKFILE_DIR}}/../.."
    vars:
      RELEASE:
        sh: '[[ {{.PROFILE}} == "release" ]] && echo "--release" || echo ""'
      ARGS: '{{.ARGS | default ""}}'
    cmds:
      - cargo test -p {{.BINDINGS_PACKAGE}} {{.RELEASE}} --locked --all-features --all-targets {{.ARGS}}

  clean:
    desc: Remove Cargo build artifacts for the bindings crate
    dir: "{{.TASKFILE_DIR}}/../.."
    cmds:
      - cargo clean -p {{.BINDINGS_PACKAGE}}

  example:p2p:sender:
    desc: Start point to point SLIM sender example
    cmds:
      - cargo run --example sender -- --local agntcy/ns/bob --shared-secret {{.SHARED_SECRET}}  --session-type p2p --participants agntcy/ns/alice

  example:group:sender:
    desc: Start group SLIM sender example (agntcy/ns/alice and agntcy/ns/charlie receivers need to be running)
    cmds:
      - cargo run --example sender -- --local agntcy/ns/bob --shared-secret {{.SHARED_SECRET}}  --session-type group --participants agntcy/ns/alice agntcy/ns/charlie

  example:receiver:
    desc: SLIM receiver example (set local name by the LOCAL environment variable)
    cmds:
      - cargo run --example receiver -- --local {{.LOCAL}} --shared-secret {{.SHARED_SECRET}}
