# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

includes:
  rust:
    taskfile: ../../../tasks/rust.yaml
    internal: true

tasks:
  default:
    cmds:
      - task -l

  bindings:build:all:
    desc: Build the Rust library with cross-compilation support
    dir: "{{.TASKFILE_DIR}}"
    silent: true
    cmds:
      - echo "🦀 Building Rust bindings library... {{.TARGET}}"
      - |
        TARGET_ARG=""
        [ -n "{{.TARGET}}" ] && TARGET_ARG="TARGET={{.TARGET}}"
        if [ "{{.TARGET}}" = "x86_64-unknown-linux-gnu" ]; then
          task rust:crossbuild $TARGET_ARG ARGS='--config profile.release.strip="none"'
        else
          task rust:crossbuild $TARGET_ARG
        fi
      - echo "🦀 Rust bindings library built successfully."
