# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

includes:
  rust:
    taskfile: ../../../tasks/rust.yaml
    internal: true
  tools:
    taskfile: ../../../tasks/tools.yaml
    internal: true
    flatten: true

env:
  PATH: "{{.TOOLS_INSTALL_DIR}}/zig:{{.PATH}}"

vars:
  GNU_CLIB_VERSION: 2.28

tasks:
  default:
    cmds:
      - task -l

  bindings:install-cargo-components:
    desc: Install required cargo components
    status:
      - which cargo-zigbuild
    cmds:
      - echo "🦀 Installing required cargo components..."
      - cargo install cargo-zigbuild

  bindings:build:all:
    desc: Build the Rust library with UniFFI
    dir: "{{.TASKFILE_DIR}}"
    deps:
      - tools:zig
      - tools:dlltool-wrapper
      - bindings:install-cargo-components
    silent: true
    cmds:
      - echo "🦀 Building Rust bindings library... {{.TARGET}}"
      - rustup target add {{.TARGET}}
      - |
        # Determine the correct libc version based on TARGET_ABI
        TARGET_ABI="{{.TARGET_ABI}}"
        TARGET_OS="{{.TARGET_OS}}"

        ARGS=()

        # Determine whether to use cargo build or cargo zigbuild
        # - Native builds: use regular cargo build with --target for consistent paths
        # - Apple targets (iOS, macOS): use regular cargo build (zigbuild not compatible)
        # - Linux/gnu targets: use zigbuild with libc version for gnu ABI
        # - Other cross-compilation targets: use zigbuild
        if [[ "{{.TARGET}}" == "" || "{{.TARGET}}" == "$(rustc -vV | sed -n 's|host: ||p')" ]]; then
          # Native build - explicitly specify target for consistent output paths
          ARGS=(
            "build"
            "--target"
            "{{.TARGET}}"
            {{.RELEASE}}
          )
        elif [[ "{{.TARGET}}" == *"apple-ios"* || "{{.TARGET}}" == *"apple-darwin"* ]]; then
          # Apple targets (iOS, iOS Simulator, macOS) - use regular cargo build
          ARGS=(
            "build"
            "--target"
            "{{.TARGET}}"
            {{.RELEASE}}
          )
        elif [[ "$TARGET_OS" == "linux" || "$TARGET_ABI" == "gnu" ]]; then
          # For Linux or gnu targets, use zigbuild with libc version for gnu ABI
          LIBC_VERSION=""
          if [[ "$TARGET_ABI" == "gnu" ]]; then
            LIBC_VERSION=".{{.GNU_CLIB_VERSION}}"
          fi

          ARGS=(
            "zigbuild"
            "--target"
            "{{.TARGET}}$LIBC_VERSION"
            {{.RELEASE}}
          )
        else
          # Other cross-compilation targets (e.g., Windows MSVC) - use zigbuild
          ARGS=(
            "zigbuild"
            "--target"
            "{{.TARGET}}"
            {{.RELEASE}}
          )
        fi

        echo cargo ${ARGS[*]}
        PATH="{{.TOOLS_INSTALL_DIR}}:$PATH" cargo "${ARGS[@]}"
      - echo "🦀 Rust bindings library built successfully."
