# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

includes:
  rust:
    taskfile: ../../../tasks/rust.yaml
    internal: true
  tools:
    taskfile: ../../../tasks/tools.yaml
    internal: true
    flatten: true

env:
  PATH: "{{.TOOLS_INSTALL_DIR}}/zig:{{.PATH}}"

tasks:
  default:
    cmds:
      - task -l

  bindings:install-cargo-components:
    desc: Install required cargo components
    cmds:
      - echo "🦀 Installing required cargo components..."
      - cargo install cargo-zigbuild

  bindings:build:all:
    desc: Build the Rust library with UniFFI
    dir: "{{.TASKFILE_DIR}}"
    deps:
      - tools:zig
      - tools:dlltool-wrapper
      - bindings:install-cargo-components
    silent: true
    cmds:
      - echo "🦀 Building Rust bindings library... {{.TARGET}}"
      - rustup target add {{.TARGET}}
      - |
        ARGS=()

        # Depending on the target, we can either use cargo-zigbuild or regular cargo build
        if [[ "{{.TARGET}}" == "" || "{{.TARGET}}" == "$(rustc -vV | sed -n 's|host: ||p')" ]]; then
          ARGS+=(
            "build"
          )
        else
          ARGS+=(
            "zigbuild"
          )
        fi

        ARGS+=(
          "--target"
          "{{.TARGET}}"
          {{.RELEASE}}
        )

        echo cargo ${ARGS[*]}
        PATH="{{.TOOLS_INSTALL_DIR}}:$PATH" cargo "${ARGS[@]}"
      - echo "🦀 Rust bindings library built successfully."
