# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

includes:
  rust:
    taskfile: ../../../tasks/rust.yaml
    internal: true

tasks:
  default:
    cmds:
      - task -l

  bindings:build:all:
    desc: Build the Rust library with cross-compilation support
    dir: "{{.TASKFILE_DIR}}"
    silent: true
    cmds:
      - echo "🦀 Building Rust bindings library... {{.TARGET}}"
      - task: rust:crossbuild
        vars:
          ARGS: --config 'profile.release.strip="none"'
      - echo "🦀 Rust bindings library built successfully."
