# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

includes:
  rust:
    taskfile: ../../../tasks/rust.yaml
    internal: true
  tools:
    taskfile: ../../../tasks/tools.yaml
    internal: true
    flatten: true

env:
  PATH: "{{.TOOLS_INSTALL_DIR}}/zig:{{.PATH}}"

vars:
  GNU_CLIB_VERSION: 2.28

tasks:
  default:
    cmds:
      - task -l

  bindings:install-cargo-components:
    desc: Install required cargo components
    cmds:
      - echo "🦀 Installing required cargo components..."
      - cargo install cargo-zigbuild

  bindings:build:all:
    desc: Build the Rust library with UniFFI
    dir: "{{.TASKFILE_DIR}}"
    deps:
      - tools:zig
      - tools:dlltool-wrapper
      - bindings:install-cargo-components
    silent: true
    cmds:
      - echo "🦀 Building Rust bindings library... {{.TARGET}}"
      - rustup target add {{.TARGET}}
      - |
        # Determine the correct libc version based on TARGET_ABI
        TARGET_ABI="{{.TARGET_ABI}}"
        TARGET_OS="{{.TARGET_OS}}"

        ARGS=()

        # Use regular cargo build for Windows, zigbuild for others
        if [[ "$TARGET_OS" == "linux" ]]; then
          # For Linux, use zigbuild with libc version for gnu targets
          LIBC_VERSION=""
          if [[ "$TARGET_ABI" == "gnu" ]]; then
            LIBC_VERSION=".{{.GNU_CLIB_VERSION}}"
          fi

          ARGS=(
            "zigbuild"
            "--target"
            "{{.TARGET}}$LIBC_VERSION"
            {{.RELEASE}}
          )
        else
          # For Windows/macOS, use regular cargo build without libc version
          ARGS=(
            "build"
            "--target"
            "{{.TARGET}}"
            {{.RELEASE}}
          )
        fi

        echo cargo ${ARGS[*]}
        PATH="{{.TOOLS_INSTALL_DIR}}:$PATH" cargo "${ARGS[@]}"
      - echo "🦀 Rust bindings library built successfully."
