# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

tasks:
  default:
    cmds:
      - task -l

  run:slim:
    desc: "Run SLIM gateway"
    dir: ".."
    cmds:
      - cargo run --bin slim -- --config ./config/base/server-config.yaml

  run:mock-app:server:
    desc: "Run the mock app server"
    dir: src/sdk-mock
    cmds:
      - cargo run -- --config ../../../config/base/client-config.yaml --local-app server --remote-app client

  run:mock-app:server-mls:
    desc: "Run the mock app server"
    dir: src/sdk-mock
    cmds:
      - cargo run -- --config ../../../config/base/client-config.yaml --local-app server --remote-app client --mls-group-id mls-group

  run:mock-app:client:
    desc: "Run the mock app client"
    dir: src/sdk-mock
    cmds:
      - cargo run -- --config ../../../config/base/client-config.yaml --local-app client --remote-app server --message "hey there!"

  run:mock-app:client-mls:
    desc: "Run the mock app client"
    dir: src/sdk-mock
    cmds:
      - cargo run -- --config ../../../config/base/client-config.yaml --local-app client --remote-app server --mls-group-id mls-group --message "hey there!"

  docker:build-all:
    desc: "Build all Docker images"
    dir: "../.."
    cmds:
      - docker build -t slim-server -f data-plane/Dockerfile .
      - docker build -t mock-app-server -f data-plane/examples/Dockerfile.mock-app --target=mock-app-server .
      - docker build -t mock-app-client -f data-plane/examples/Dockerfile.mock-app --target=mock-app-client .

  docker:compose-up:
    desc: "Start all services with Docker Compose"
    dir: "."
    cmds:
      - |
        # Ensure config directory exists
        mkdir -p config
        # Start the Docker Compose services
        docker compose up --build

  docker:compose-down:
    desc: "Stop all services with Docker Compose"
    dir: "."
    cmds:
      - docker compose down
