# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

tasks:
  default:
    cmds:
      - task -l

  run:slim:
    desc: "Run SLIM gateway"
    dir: ".."
    cmds:
      - cargo run --bin slim -- --config ./config/base/server-config.yaml

  run:mock-agent:server:
    desc: "Run the mock agent server"
    dir: src/sdk-mock
    cmds:
      - cargo run -- --config ../../../config/base/client-config.yaml --local-agent server --remote-agent client

  run:mock-agent:server-mls:
    desc: "Run the mock agent server"
    dir: src/sdk-mock
    cmds:
      - cargo run -- --config ../../../config/base/client-config.yaml --local-agent server --remote-agent client --mls-group-id mls-group

  run:mock-agent:client:
    desc: "Run the mock agent client"
    dir: src/sdk-mock
    cmds:
      - cargo run -- --config ../../../config/base/client-config.yaml --local-agent client --remote-agent server --message "hey there!"

  run:mock-agent:client-mls:
    desc: "Run the mock agent client"
    dir: src/sdk-mock
    cmds:
      - cargo run -- --config ../../../config/base/client-config.yaml --local-agent client --remote-agent server --mls-group-id mls-group --message "hey there!"

  docker:build-all:
    desc: "Build all Docker images"
    dir: "../.."
    cmds:
      - docker build -t slim-server -f data-plane/Dockerfile .
      - docker build -t mock-agent-server -f data-plane/examples/Dockerfile.mock-agent --target=mock-agent-server .
      - docker build -t mock-agent-client -f data-plane/examples/Dockerfile.mock-agent --target=mock-agent-client .

  docker:compose-up:
    desc: "Start all services with Docker Compose"
    dir: "."
    cmds:
      - |
        # Ensure config directory exists
        mkdir -p config
        # Start the Docker Compose services
        docker compose up --build

  docker:compose-down:
    desc: "Stop all services with Docker Compose"
    dir: "."
    cmds:
      - docker compose down
