# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

includes:
  rust:
    taskfile: ../rust/Taskfile.yaml
    internal: true

vars:
  # Rust bindings directory
  BINDINGS_DIR: "{{.TASKFILE_DIR}}/../rust"

  # Rust library name
  LIB_NAME: slim_bindings

  # Build profile (debug or release)
  PROFILE: '{{.PROFILE | default "release"}}'
  RELEASE:
    sh: '[[ {{.PROFILE}} == "release" ]] && echo "--release" || echo ""'

  # Current target
  CURRENT_TARGET:
    sh: 'rustc -vV | sed -n "s|host: ||p"'
  TARGET: "{{.TARGET | default .CURRENT_TARGET}}"

  # Target directory for built libraries
  TARGET_DIR: "{{.BINDINGS_DIR}}/../../target"
  LIB_PATH: "{{.TARGET_DIR}}/{{.TARGET}}/{{.PROFILE}}"

  # Runtimes directory for NuGet packaging
  RUNTIMES_DIR: "{{.TASKFILE_DIR}}/runtimes"

  # Generated bindings directory
  GENERATED_DIR: "{{.TASKFILE_DIR}}/Slim/generated"

  # Artifacts directory (CI mode)
  ARTIFACTS_DIR: '{{.ARTIFACTS_DIR | default "./artifacts"}}'

  # Target used for binding generation (most compatible)
  BINDGEN_TARGET: '{{.BINDGEN_TARGET | default "x86_64-unknown-linux-gnu"}}'

  # Output directory for NuGet packages
  OUTPUT_DIR: '{{.OUTPUT_DIR | default "./nupkg"}}'

  # Supported platforms for NuGet packaging
  # Format: TARGET|RID|LIB_EXT
  # Note: x86_64-pc-windows-gnu is excluded due to RID collision with MSVC.
  # .NET RIDs cannot differentiate between GNU and MSVC toolchains for win-x64.
  PLATFORMS: |
    x86_64-unknown-linux-gnu|linux-x64|so
    aarch64-unknown-linux-gnu|linux-arm64|so
    x86_64-unknown-linux-musl|linux-musl-x64|so
    aarch64-unknown-linux-musl|linux-musl-arm64|so
    x86_64-apple-darwin|osx-x64|dylib
    aarch64-apple-darwin|osx-arm64|dylib
    x86_64-pc-windows-msvc|win-x64|dll
    aarch64-pc-windows-msvc|win-arm64|dll

env:
  PATH: "{{.TOOLS_INSTALL_DIR}}/zig:{{.PATH}}"

tasks:
  default:
    desc: "List available tasks"
    cmds:
      - task -l

  resolve-version:
    desc: "Test version resolution (for debugging): Resolve version from VERSION, TAG_NAME, or Cargo.toml (in priority order)"
    vars:
      VERSION_PARAM: '{{.VERSION | default ""}}'
      TAG_NAME_PARAM: '{{.TAG_NAME | default ""}}'
    cmds:
      - |
        # Priority 1: Explicit VERSION parameter (highest priority)
        if [[ -n "{{.VERSION_PARAM}}" ]]; then
          echo "{{.VERSION_PARAM}}"
          exit 0
        fi

        # Priority 2: Extract from TAG_NAME parameter
        if [[ -n "{{.TAG_NAME_PARAM}}" ]]; then
          TAG="{{.TAG_NAME_PARAM}}"
          # Remove 'slim-bindings-' prefix if present
          VERSION="${TAG#slim-bindings-}"
          # Remove leading 'v' if present (e.g., v1.0.0 -> 1.0.0)
          VERSION="${VERSION#v}"
          echo "$VERSION"
          exit 0
        fi

        # Priority 3: Fallback to Cargo.toml
        grep '^version = ' ../rust/Cargo.toml | sed 's/version = "\(.*\)"/\1/'

  install-uniffi-bindgen-cs:
    desc: "Install uniffi-bindgen-cs for C# bindings generation"
    status:
      - which uniffi-bindgen-cs
    cmds:
      - cargo install uniffi-bindgen-cs --git https://github.com/NordSecurity/uniffi-bindgen-cs.git --tag v0.9.0+v0.28.3
    silent: true


  generate:
    desc: "Generate C# bindings from artifacts or local build"
    deps:
      - install-uniffi-bindgen-cs
    cmds:
      - |
        ARTIFACTS_DIR="{{.ARTIFACTS_DIR}}"
        BINDGEN_TARGET="{{.BINDGEN_TARGET}}"

        lib_file=""

        # Try CI artifacts directory first
        artifact_dir="$ARTIFACTS_DIR/bindings-${BINDGEN_TARGET}"

        if [[ -d "$artifact_dir" ]]; then
          lib_file=$(find "$artifact_dir" -maxdepth 1 -name "lib{{.LIB_NAME}}*.a" -type f | head -1)
        fi

        # Fall back to local build: build Rust library, then use its output
        if [[ -z "$lib_file" || ! -f "$lib_file" ]]; then
          echo "No CI artifacts found, building Rust library locally..."
          task rust:bindings:build:all PROFILE="{{.PROFILE}}"

          local_lib="{{.LIB_PATH}}/lib{{.LIB_NAME}}.a"
          if [[ -f "$local_lib" ]]; then
            echo "Using local build output: $local_lib"
            lib_file="$local_lib"
          fi
        fi

        if [[ -z "$lib_file" || ! -f "$lib_file" ]]; then
          echo "ERROR: Static library (.a) not found."
          echo "Checked CI artifacts dir: $artifact_dir"
          echo "Checked local build path: {{.LIB_PATH}}/lib{{.LIB_NAME}}.a"
          exit 1
        fi

        echo "Generating C# bindings from: $lib_file"

        rm -rf {{.GENERATED_DIR}}
        mkdir -p {{.GENERATED_DIR}}
        uniffi-bindgen-cs --library --out-dir {{.GENERATED_DIR}} "$lib_file"

        if [[ ! -f "{{.GENERATED_DIR}}/slim_bindings.cs" ]]; then
          echo "ERROR: Failed to generate slim_bindings.cs"
          exit 1
        fi

        echo "✅ C# bindings generated successfully"
      - task: copy:runtimes
    silent: true

  copy:runtimes:
    desc: "Copy runtime libraries from artifacts or local build to runtimes directory"
    cmds:
      - rm -rf {{.RUNTIMES_DIR}}
      - mkdir -p {{.RUNTIMES_DIR}}
      - |
        ARTIFACTS_DIR="{{.ARTIFACTS_DIR}}"
        runtime_count=0

        # Try CI artifacts directory first
        if [[ -d "$ARTIFACTS_DIR" ]] && ls "$ARTIFACTS_DIR"/bindings-* &>/dev/null; then
          echo "Copying runtime libraries from: $ARTIFACTS_DIR"

          # Iterate through all bindings-* artifact directories
          for target_dir in "$ARTIFACTS_DIR"/bindings-*; do
            if [[ ! -d "$target_dir" ]]; then
              continue
            fi

            # Extract target triple from directory name
            target=$(basename "$target_dir" | sed 's/^bindings-//')

            # Look up the target in PLATFORMS to get RID and extension
            rid=""
            ext=""
            while IFS='|' read -r platform_target platform_rid platform_ext; do
              if [[ "$platform_target" == "$target" ]]; then
                rid="$platform_rid"
                ext="$platform_ext"
                break
              fi
            done <<< "{{.PLATFORMS}}"

            # Skip if target not in our supported platforms list
            if [[ -z "$rid" || -z "$ext" ]]; then
              echo "  Skipping $target (not in PLATFORMS list)"
              continue
            fi

            echo "  Processing $target → $rid..."

            # Determine library name patterns (source with wildcard for arch/platform, destination with uniffi_ prefix)
            case "$ext" in
              so|dylib)
                lib_pattern="lib{{.LIB_NAME}}*.$ext"
                lib_name="libuniffi_{{.LIB_NAME}}.$ext"
                ;;
              dll)
                lib_pattern="{{.LIB_NAME}}*.$ext"
                lib_name="uniffi_{{.LIB_NAME}}.$ext"
                ;;
            esac

            # Find the runtime library
            src=$(find "$target_dir" -maxdepth 1 -name "$lib_pattern" -type f | head -1)

            if [[ -z "$src" || ! -f "$src" ]]; then
              echo "    ⚠️  Runtime library not found (pattern: $lib_pattern)"
              continue
            fi

            # Copy to runtimes directory
            runtime_dir="{{.RUNTIMES_DIR}}/$rid/native"
            mkdir -p "$runtime_dir"
            cp "$src" "$runtime_dir/$lib_name"
            echo "    ✅ Copied to $rid/native/$lib_name"
            runtime_count=$((runtime_count + 1))
          done
        fi

        # Fall back to local build output
        if [[ $runtime_count -eq 0 ]]; then
          echo "No CI artifacts found, copying from local build..."

          # Detect architecture
          ARCH=$(uname -m)
          case "$ARCH" in
            x86_64|amd64) ARCH_NAME="x86_64" ;;
            arm64|aarch64) ARCH_NAME="aarch64" ;;
          esac

          # Detect OS and set RID, extension, and library name
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          case "$OS" in
            darwin)
              case "$ARCH_NAME" in
                x86_64)  RID="osx-x64" ;;
                aarch64) RID="osx-arm64" ;;
              esac
              LIB_EXT="dylib"
              LIB_PREFIX="lib"
              DEST_NAME="libuniffi_{{.LIB_NAME}}.dylib"
              ;;
            linux)
              case "$ARCH_NAME" in
                x86_64)  RID="linux-x64" ;;
                aarch64) RID="linux-arm64" ;;
              esac
              LIB_EXT="so"
              LIB_PREFIX="lib"
              DEST_NAME="libuniffi_{{.LIB_NAME}}.so"
              ;;
            mingw*|msys*|cygwin*)
              case "$ARCH_NAME" in
                x86_64)  RID="win-x64" ;;
                aarch64) RID="win-arm64" ;;
              esac
              LIB_EXT="dll"
              LIB_PREFIX=""
              DEST_NAME="uniffi_{{.LIB_NAME}}.dll"
              ;;
          esac

          SRC="{{.LIB_PATH}}/${LIB_PREFIX}{{.LIB_NAME}}.${LIB_EXT}"

          if [[ ! -f "$SRC" ]]; then
            echo "⚠️  Shared library not found: $SRC"
            exit 1
          fi

          DEST_DIR="{{.RUNTIMES_DIR}}/$RID/native"
          mkdir -p "$DEST_DIR"
          cp "$SRC" "$DEST_DIR/$DEST_NAME"
          echo "  ✅ Copied $SRC → $DEST_DIR/$DEST_NAME"
          runtime_count=1
        fi

        echo ""
        echo "✅ Successfully copied $runtime_count runtime libraries:"
        find {{.RUNTIMES_DIR}} -type f -exec ls -lh {} \;
    silent: true

  build:
    desc: "Build the .NET solution (expects bindings already generated)"
    cmds:
      - |
        if [[ ! -f "{{.GENERATED_DIR}}/slim_bindings.cs" ]]; then
          echo "ERROR: C# bindings not found. Run 'task generate' first."
          exit 1
        fi
        echo "Building .NET solution..."
        dotnet build Slim.sln --configuration Release
        echo "✅ Build completed successfully"
    silent: true

  test:
    desc: "Run smoke tests (no server required)"
    cmds:
      - |
        echo "Running smoke tests..."
        dotnet test Slim.Tests/Slim.Tests.csproj --configuration Release --filter "FullyQualifiedName~SmokeTests" --verbosity normal
        echo "✅ Tests completed successfully"
    silent: true

  pack:
    desc: "Create NuGet package (expects runtimes already copied)"
    vars:
      VERSION_RESOLVED:
        sh: task resolve-version VERSION="{{.VERSION}}" TAG_NAME="{{.TAG_NAME}}"
    cmds:
      - |
        if [[ ! -d "{{.RUNTIMES_DIR}}" ]] || [[ -z "$(ls -A {{.RUNTIMES_DIR}})" ]]; then
          echo "ERROR: No runtime libraries found. Run 'task copy:runtimes' first."
          exit 1
        fi

        VERSION="{{.VERSION_RESOLVED}}"
        OUTPUT_DIR="{{.OUTPUT_DIR}}"

        echo "Creating NuGet package version $VERSION..."
        echo "Runtime libraries included:"
        ls -1 {{.RUNTIMES_DIR}}

        mkdir -p "$OUTPUT_DIR"
        dotnet pack Slim/Slim.csproj --configuration Release --output "$OUTPUT_DIR" -p:Version="$VERSION"

        echo ""
        echo "✅ Successfully created NuGet package:"
        ls -lh "$OUTPUT_DIR"/*.nupkg
    silent: true

  ci:
    desc: "Run complete CI pipeline: generate bindings, copy runtimes, build, test, and pack"
    vars:
      VERSION_RESOLVED:
        sh: task resolve-version VERSION="{{.VERSION}}" TAG_NAME="{{.TAG_NAME}}"
    cmds:
      - |
        echo "=================================================="
        echo "  .NET Bindings CI Pipeline"
        echo "=================================================="
        echo "Artifacts: {{.ARTIFACTS_DIR}}"
        echo "Output:    {{.OUTPUT_DIR}}"
        echo "Version:   {{.VERSION_RESOLVED}}"
        echo ""
      - task: generate
        vars:
          ARTIFACTS_DIR: "{{.ARTIFACTS_DIR}}"
      - task: copy:runtimes
        vars:
          ARTIFACTS_DIR: "{{.ARTIFACTS_DIR}}"
      - task: build
      - task: test
      - task: pack
        vars:
          VERSION: "{{.VERSION_RESOLVED}}"
          TAG_NAME: "{{.TAG_NAME}}"
          OUTPUT_DIR: "{{.OUTPUT_DIR}}"
      - |
        echo ""
        echo "=================================================="
        echo "  ✅ CI Pipeline completed successfully"
        echo "=================================================="
    silent: true

  clean:
    desc: "Clean all build artifacts"
    cmds:
      - |
        echo "Cleaning build artifacts..."
        dotnet clean Slim.sln 2>/dev/null || true
        rm -rf {{.RUNTIMES_DIR}} {{.GENERATED_DIR}} nupkg/ Slim/bin/ Slim/obj/ Slim.Tests/bin/ Slim.Tests/obj/
        echo "✅ Clean completed"
    silent: true
