# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Buf CI
on:
  push:
    paths:
      # Caution: This workflow could miss changes if the paths are not correctly specified.
      - "**.proto"
      - "**/buf.yaml"
      - "**/buf.lock"
      - "**/buf.md"
      - "**/README.md"
      - "**/LICENSE"
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
        with:
          token: ${{ secrets.BUF_TOKEN }}
          breaking_against: buf.build/agntcy/slim
