# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-test-and-build-integration-mcp-proxy

on:
  push:
    paths:
      - 'data-plane/python/integrations**'
      - 'data-plane/integrations/**'
    branches:
      - main
  pull_request:
    paths:
      - 'data-plane/python/integrations**'
      - 'data-plane/integrations/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  mcp-proxy-build-and-test:
    name: MCP proxy - build & test
    uses: ./.github/workflows/reusable-rust-build-and-test.yaml
    with:
      working-directory: ./data-plane/integrations/mcp-proxy
      task-prefix: mcp-proxy

  build-srpc:
    name: Build srpc
    uses: ./.github/workflows/reusable-python-build-and-test.yaml
    with:
      working-directory: ./data-plane/python/integrations
      prefix: srpc:python

  build-slima2a:
    name: Build slima2a
    uses: ./.github/workflows/reusable-python-build-and-test.yaml
    with:
      working-directory: ./data-plane/python/integrations
      prefix: slima2a:python

  build-mcp-wheels:
    name: Build slim mcp
    uses: ./.github/workflows/reusable-python-build-and-test.yaml
    with:
      working-directory: ./data-plane/python/integrations
      prefix: slim-mcp:python