# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-images

on:
  push:
    tags:
      - 'slim-*'
      - 'control-plane-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  prepare-build:
    name: Prepare Build
    outputs:
      targets: ${{ steps.all-targets.outputs.targets }}
      image-tag: ${{ steps.resolve.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Filter target
        id: resolve
        run: |
          # This assumes tags are in this form
          # slim-<component1>-<component2>-v<version>

          # strip slim- prefix from the tag
          _target=${GITHUB_REF_NAME#slim}

          # remove version to only get the component
          target=${_target%-v*}

          # If component is empty, set it to 'slim'
          if [[ -z "$target" ]]; then
            target="slim"
          else
            # remove the - from the beginning of the target if it exists
            target=${target#-}
          fi

          # get version only
          version=${_target##*-v}

          # set target and version as output
          echo target=${target} >> ${GITHUB_OUTPUT}
          echo version=${version} >> ${GITHUB_OUTPUT}

          # Print the target and version
          echo "Target: $target"
          echo "Version: $version"

      - name: List all targets
        id: all-targets
        uses: docker/bake-action/subaction/list-targets@a4d7f0b5b91c14a296d792d4ec53a9db17f02e67 # v5.5.0
        with:
          target: ${{ steps.resolve.outputs.target }}
        continue-on-error: true

  build-push:
    name: Build docker image - ${{ matrix.target }}
    needs: [prepare-build]
    if: ${{ needs.prepare-build.outputs.targets != '[]' && needs.prepare-build.outputs.targets != '' }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare-build.outputs.targets) }}
    uses: ./.github/workflows/reusable-docker-build-push.yaml
    permissions:
      contents: 'read'
      packages: 'write'
      attestations: 'write'
    with:
      bake-targets: ${{ matrix.target }}
      image-tag: ${{ needs.prepare-build.outputs.image-tag }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  test-integration:
    name: Run integration tests
    needs: [ build-push ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Trigger CSIT integration CI
        uses: ./.github/actions/trigger-integrations
        with:
          github-token: ${{ secrets.AGNTCY_BUILD_BOT_GH_TOKEN }}
