# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-images

on:
  push:
    tags:
      - 'slim-*'
      - 'control-plane-*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  prepare-build:
    name: Prepare Build
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.all-targets.outputs.matrix }}
      image-tag: ${{ steps.resolve.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Filter target
        id: resolve
        run: |
          # This assumes tags are in this form
          # slim-<component1>-<component2>-v<version>

          # strip slim- prefix from the tag
          _target=${GITHUB_REF_NAME#slim}

          # remove version to only get the component
          target=${_target%-v*}

          # If component is empty, set it to 'slim'
          if [[ -z "$target" ]]; then
            target="slim"
          else
            # remove the - from the beginning of the target if it exists
            target=${target#-}
          fi

          # get version only
          version=${_target##*-v}

          # set target and version as output
          echo "target=${target}" >> "${GITHUB_OUTPUT}"
          echo "version=${version}" >> "${GITHUB_OUTPUT}"

          # Print the target and version
          echo "Target: $target"
          echo "Version: $version"

      - name: List all targets
        id: all-targets
        uses: docker/bake-action/subaction/matrix@82490499d2e5613fcead7e128237ef0b0ea210f7 # v7.0.0
        with:
          target: ${{ steps.resolve.outputs.target }}
        continue-on-error: true

  build-push:
    name: Build docker image - ${{ matrix.target }}
    needs: [prepare-build]
    if: ${{ needs.prepare-build.outputs.matrix != '[]' && needs.prepare-build.outputs.matrix != '' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare-build.outputs.matrix) }}
    uses: ./.github/workflows/reusable-docker-build-push.yaml
    permissions:
      contents: 'read'
      packages: 'write'
      attestations: 'write'
    with:
      bake-targets: ${{ matrix.target }}
      image-tag: ${{ needs.prepare-build.outputs.image-tag }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  test-integration:
    name: Run integration tests
    needs: [ build-push ]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Trigger CSIT integration CI
        uses: ./.github/actions/trigger-integrations
        with:
          github-token: ${{ secrets.AGNTCY_BUILD_BOT_GH_TOKEN }}
