# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Build and Push

on:
  workflow_call:
    inputs:
      bake-targets:
        required: true
        type: string
        description: "Bake target"
      bake-file:
        required: false
        type: string
        description: "Bake file"
        default: "docker-bake.hcl"
      image-tag:
        required: true
        type: string
        description: "Image tag to use."
      image-repo:
        required: false
        type: string
        description: "Image repo to use."
        default: "ghcr.io/agntcy/slim"
    secrets:
      github-token:
        description: "github token"
        required: false

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Disk cleanup
        uses: ./.github/actions/cleanup-disk

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.github-token}}

      - name: Check available disk space
        run: df -h

      - name: Setup QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          tags: |
            type=raw,value=${{ inputs.image-tag }}
            type=raw,value=latest,enable=${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}

      - name: Build and push
        uses: docker/bake-action@82490499d2e5613fcead7e128237ef0b0ea210f7 # v7.0.0
        with:
          source: .
          files: |
            ${{ inputs.bake-file }}
            ${{ steps.metadata.outputs.bake-file }}
          targets: ${{ inputs.bake-targets }}
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
          provenance: false
          # set: |
          #   *.cache-from=type=gha
          #   *.cache-to=type=gha,mode=max
        env:
          IMAGE_REPO: ${{ inputs.image-repo }}
